/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#include "freertos/FreeRTOS.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {NI rc;
NI rootIdx;
};
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct TNimTypeV2 {void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
void* typeInfoV1;
};
struct RootObj {TNimTypeV2* m_type;};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {  Exception Sup;};
struct tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA {  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;NI32 errorCode;
};
struct tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA {  tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA Sup;NI32 code;
};
struct tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA {  tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA Sup;NI32 code;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__LoYD9cYK9aJvrcDizBN64qaQ)(NIM_BOOL isDestroyAction, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* s, TNimTypeV2* desc);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___I2LL6IIITMTZ7BlbO5vOYg)(tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA** dest);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___KwKNTWISQygz5QNhcV5orw)(tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA** dest);
static N_INLINE(NI, nimCStrLen)(NCSTRING a);

/* section: NIM_merge_DATA */
extern TNimTypeV2 NTIv2__JiOJBwL88TSI8X2PKXXlgA_;
extern TNimTypeV2 NTIv2__BeJgrOdDsczOwEWOZbRfKA_;
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__KDybzinjxZ9bYLUcaKcpPFQ_3 = { 7 | NIM_STRLIT_FLAG, "error: " };
static const NimStringV2 TM__KDybzinjxZ9bYLUcaKcpPFQ_4 = {7, (NimStrPayload*)&TM__KDybzinjxZ9bYLUcaKcpPFQ_3};
extern TNimTypeV2 NTIv2__jXXu17dImgF2rcF9bHHAzrA_;
extern TNimTypeV2 NTIv2__yoNlBGx0D2tRizIdhQuENw_;
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__KDybzinjxZ9bYLUcaKcpPFQ_7 = { 25 | NIM_STRLIT_FLAG, "string to large for array" };
static const NimStringV2 TM__KDybzinjxZ9bYLUcaKcpPFQ_8 = {25, (NimStrPayload*)&TM__KDybzinjxZ9bYLUcaKcpPFQ_7};

/* section: NIM_merge_VARS */
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 544 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;

#line 546 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 436 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics.nim"
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {	NI result;	nimfr_("-%", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics."
"nim");	result = (NI)0;
#line 437 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics.nim"
	nimln_(437, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics."
"nim");
#line 441 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics.nim"
	nimln_(441, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics."
"nim");	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));	popFrame();	return result;}

#line 414 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 396 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p) {	NIM_BOOL result;NIM_BOOL* nimErr_;	nimfr_("nimDecRefIsLastCyclicDyn", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");{nimErr_ = nimErrorFlag();	result = (NIM_BOOL)0;
#line 397 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
	nimln_(397, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");	{		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;		NI T5_;
#line 397 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"

#line 397 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		if (!!((p == NIM_NIL))) goto LA3_;

#line 398 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(398, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		nimln_(63, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		T5_ = (NI)0;		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 8));		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
#line 399 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(399, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");		{
#line 399 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"

#line 399 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
			if (!((NI)((*cell).rc & ((NI) -16)) == ((NI) 0))) goto LA8_;

#line 400 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
			nimln_(400, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");			result = NIM_TRUE;		}
		goto LA6_;
		LA8_: ;
		{			NI TM__KDybzinjxZ9bYLUcaKcpPFQ_2;
#line 403 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
			nimln_(403, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");			if (nimSubInt((*cell).rc, ((NI) 16), &TM__KDybzinjxZ9bYLUcaKcpPFQ_2)) { raiseOverflow(); goto BeforeRet_;};			(*cell).rc = (NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_2);		}
		LA6_: ;

#line 405 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(405, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");
#line 405 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		rememberCycle__LoYD9cYK9aJvrcDizBN64qaQ(result, cell, (*((TNimTypeV2**) (p))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___atv3i14bWKtHLJtkExojTA)(tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA** dest) {
#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	{		NIM_BOOL T3_;
#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLastCyclicDyn((*dest));		if (!T3_) goto LA4_;

#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		nimDestroyAndDispose((*dest));
	}
	LA4_: ;
}

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___I2LL6IIITMTZ7BlbO5vOYg)(tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA** dest) {
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	{		NIM_BOOL T3_;
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLastCyclicDyn((*dest));		if (!T3_) goto LA4_;

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		nimDestroyAndDispose((*dest));
	}
	LA4_: ;
}

#line 55 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA*, newEspError__2wCFtClOvrkQajXP7vJatA)(NimStringV2 msg, NI32 error) {	tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA* result;NIM_BOOL* nimErr_;	nimfr_("newEspError", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");{nimErr_ = nimErrorFlag();	result = (tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA*)0;
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	nimln_(56, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	eqdestroy___I2LL6IIITMTZ7BlbO5vOYg(&result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	result = (tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA*) nimNewObj(sizeof(tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA), NIM_ALIGNOF(tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA));	(*result).Sup.Sup.Sup.Sup.m_type = (&NTIv2__JiOJBwL88TSI8X2PKXXlgA_);	(*result).Sup.Sup.Sup.name = "NvsError";
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
	eqcopy___aBBXmHFBEivKqERloP6zmA((&(*result).Sup.Sup.Sup.message), msg);

#line 58 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	nimln_(58, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");	(*result).code = error;	}BeforeRet_: ;
	popFrame();	return result;}

#line 11 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size) {	void* T1_;
#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source_0, ((size_t) (size)));}

#line 2186 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size) {
#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"

#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimCopyMem(dest, source_0, size);
}

#line 94 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {{
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	{		void* T5_;		void* T6_;		NI TM__KDybzinjxZ9bYLUcaKcpPFQ_5;		NI TM__KDybzinjxZ9bYLUcaKcpPFQ_6;
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (!(((NI) 0) < src.len)) goto LA3_;

#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		T5_ = (void*)0;		T5_ = ((void*) ((&(*(*dest).p).data[(*dest).len])));		T6_ = (void*)0;		T6_ = ((void*) ((&(*src.p).data[((NI) 0)])));
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (nimAddInt(src.len, ((NI) 1), &TM__KDybzinjxZ9bYLUcaKcpPFQ_5)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_5)) < ((NI) 0) || ((NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_5)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_5), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(T5_, T6_, ((NI) ((NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_5))));

#line 98 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (nimAddInt((*dest).len, src.len, &TM__KDybzinjxZ9bYLUcaKcpPFQ_6)) { raiseOverflow(); goto BeforeRet_;};		(*dest).len = (NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_6);	}
	LA3_: ;
	}BeforeRet_: ;
}

#line 41 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(void, doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q)(NI32 ret) {NIM_BOOL* nimErr_;	nimfr_("doCheck", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");{nimErr_ = nimErrorFlag();
#line 42 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	nimln_(42, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");	{		NimStringV2 colontmpD_;		tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA* T6_;		NimStringV2 T7_;		NCSTRING T8_;
#line 42 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 42 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		if (!!((ret == ((NI32) 0)))) goto LA3_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;		T6_ = (tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA*)0;		T6_ = (tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA*) nimNewObj(sizeof(tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA), NIM_ALIGNOF(tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA));		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__BeJgrOdDsczOwEWOZbRfKA_);		(*T6_).Sup.Sup.name = "OSError";
#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		nimln_(43, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");		T7_.len = 0; T7_.p = NIM_NIL;
#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		T8_ = (NCSTRING)0;		T8_ = esp_err_to_name(ret);		colontmpD_ = cstrToNimstr(T8_);		T7_ = rawNewString(colontmpD_.len + 7);appendString((&T7_), TM__KDybzinjxZ9bYLUcaKcpPFQ_4);appendString((&T7_), colontmpD_);		(*T6_).Sup.Sup.message = T7_;		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		raiseExceptionEx((Exception*)T6_, "OSError", "doCheck", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im", 43);		goto LA5_;		{			LA5_:;		}
		{
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();}

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___KwKNTWISQygz5QNhcV5orw)(tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA** dest) {
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	{		NIM_BOOL T3_;
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLastCyclicDyn((*dest));		if (!T3_) goto LA4_;

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		nimDestroyAndDispose((*dest));
	}
	LA4_: ;
}

#line 55 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA*, newEspError__fwmtFMit0hAS9aJp9a7jOT1A)(NimStringV2 msg, NI32 error) {	tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA* result;NIM_BOOL* nimErr_;	nimfr_("newEspError", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");{nimErr_ = nimErrorFlag();	result = (tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA*)0;
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	nimln_(56, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	eqdestroy___KwKNTWISQygz5QNhcV5orw(&result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	result = (tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA*) nimNewObj(sizeof(tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA), NIM_ALIGNOF(tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA));	(*result).Sup.Sup.Sup.Sup.m_type = (&NTIv2__jXXu17dImgF2rcF9bHHAzrA_);	(*result).Sup.Sup.Sup.name = "EventError";
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
	eqcopy___aBBXmHFBEivKqERloP6zmA((&(*result).Sup.Sup.Sup.message), msg);

#line 58 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	nimln_(58, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");	(*result).code = error;	}BeforeRet_: ;
	popFrame();	return result;}

#line 48 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(NI, nimCStrLen)(NCSTRING a) {	NI result;	size_t T1_;	result = (NI)0;
#line 50 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 50 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 50 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	T1_ = (size_t)0;	T1_ = strlen(a);	result = ((NI) (T1_));	return result;}

#line 60 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(void, setFromString__ubRii7LYgSM9apFvSWh9ckcA)(NU8* val, NI valLen_0, NCSTRING str) {	NI lstr;	nimfr_("setFromString", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");{
#line 61 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	nimln_(61, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");
#line 61 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	lstr = (str ? nimCStrLen(str) : 0);
#line 62 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	nimln_(62, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");	{		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T5_;
#line 62 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 62 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		if (!(valLen_0 < lstr)) goto LA3_;
		T5_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;		T5_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) nimNewObj(sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw), NIM_ALIGNOF(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));		(*T5_).Sup.Sup.Sup.m_type = (&NTIv2__yoNlBGx0D2tRizIdhQuENw_);		(*T5_).Sup.Sup.name = "ValueError";		(*T5_).Sup.Sup.message = TM__KDybzinjxZ9bYLUcaKcpPFQ_8;		(*T5_).Sup.Sup.parent = ((Exception*) NIM_NIL);
#line 63 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		nimln_(63, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");		raiseExceptionEx((Exception*)T5_, "ValueError", "setFromString", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im", 63);		goto BeforeRet_;	}
	LA3_: ;

#line 65 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	nimln_(65, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");	if ((lstr) < ((NI) 0) || (lstr) > ((NI) 2147483647)){ raiseRangeErrorI(lstr, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 65 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) (val)), ((void*) (str)), ((NI) (lstr)));
	}BeforeRet_: ;
	popFrame();}
