/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include "nvs_flash.h"
#include "esp_log.h"
#include <string.h>
#include "freertos/FreeRTOS.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyTuple__0F3Kz25HWtRatQmCDVHWEA tyTuple__0F3Kz25HWtRatQmCDVHWEA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct TNimTypeV2 {void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
void* typeInfoV1;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {NI rc;
NI rootIdx;
};
struct RootObj {TNimTypeV2* m_type;};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {  Exception Sup;};
struct tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA {  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;NI32 errorCode;
};
struct tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA {  tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA Sup;NI32 code;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {NI len;
NI cap;
tyTuple__0F3Kz25HWtRatQmCDVHWEA* d;
};
struct tyTuple__0F3Kz25HWtRatQmCDVHWEA {
tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* Field0;
TNimTypeV2* Field1;
};
typedef tyTuple__0F3Kz25HWtRatQmCDVHWEA tyUncheckedArray__JDjQWOF6l7jz1gUppkfhwA[1];
struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ {tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w traceStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w toFree;
NI freed;
NI touched;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA*, newEspError__2wCFtClOvrkQajXP7vJatA)(NimStringV2 msg, NI32 error);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___9bFJbrj9aRQCH3Cq7aMMwd2g)(tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA* dest);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__LoYD9cYK9aJvrcDizBN64qaQ)(NIM_BOOL isDestroyAction, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* s, TNimTypeV2* desc);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___4fQQqvAqifkWGVa4g39cI5A)(tySequence__uB9b75OUPRENsBAu4AnoePA* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___zXMAlK2HRYidyULlN22cww)(tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA* dest, void* env);
static N_INLINE(void, nimTraceRefDyn)(void* q, void* env);
static N_INLINE(void, add__A2hu7ps9a7fQ6dTDoPajZ5gsystem)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* c, TNimTypeV2* t);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOCONV(void*, allocSharedImpl)(NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___kDvIcrGphqE2lmGa3RNr5A)(NimStringV2* dest, void* env);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___9cqRrToT354sdOysDOB1O2A)(tySequence__uB9b75OUPRENsBAu4AnoePA* dest, void* env);
N_LIB_PRIVATE N_NIMCALL(void, eqdispose___9bFJbrj9aRQCH3Cq7aMMwd2g_2)(tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdispose___4fQQqvAqifkWGVa4g39cI5A_2)(tySequence__uB9b75OUPRENsBAu4AnoePA* dest);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);

/* section: NIM_merge_DATA */
N_LIB_PRIVATE TNimTypeV2 NTIv2__JiOJBwL88TSI8X2PKXXlgA_;
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__V9bFn0kpzxTsN8MHza8M9a0A_8 = { 7 | NIM_STRLIT_FLAG, "Error (" };
static const NimStringV2 TM__V9bFn0kpzxTsN8MHza8M9a0A_9 = {7, (NimStrPayload*)&TM__V9bFn0kpzxTsN8MHza8M9a0A_8};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__V9bFn0kpzxTsN8MHza8M9a0A_12 = { 15 | NIM_STRLIT_FLAG, ") erahsing NVS " };
static const NimStringV2 TM__V9bFn0kpzxTsN8MHza8M9a0A_13 = {15, (NimStrPayload*)&TM__V9bFn0kpzxTsN8MHza8M9a0A_12};
static const NimStringV2 TM__V9bFn0kpzxTsN8MHza8M9a0A_14 = {7, (NimStrPayload*)&TM__V9bFn0kpzxTsN8MHza8M9a0A_8};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__V9bFn0kpzxTsN8MHza8M9a0A_15 = { 19 | NIM_STRLIT_FLAG, ") initializing NVS " };
static const NimStringV2 TM__V9bFn0kpzxTsN8MHza8M9a0A_16 = {19, (NimStrPayload*)&TM__V9bFn0kpzxTsN8MHza8M9a0A_15};
static const NimStringV2 TM__V9bFn0kpzxTsN8MHza8M9a0A_17 = {7, (NimStrPayload*)&TM__V9bFn0kpzxTsN8MHza8M9a0A_8};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__V9bFn0kpzxTsN8MHza8M9a0A_18 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__V9bFn0kpzxTsN8MHza8M9a0A_19 = {1, (NimStrPayload*)&TM__V9bFn0kpzxTsN8MHza8M9a0A_18};

/* section: NIM_merge_VARS */
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 90 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {	NCSTRING result;	result = (NCSTRING)0;
#line 91 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	{
#line 91 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (!(s.len == ((NI) 0))) goto LA3_;

#line 91 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		result = "";	}
	goto LA1_;
	LA3_: ;
	{
#line 92 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		result = ((NCSTRING) ((*s.p).data));	}
	LA1_: ;
	return result;}

#line 544 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;

#line 546 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 436 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics.nim"
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {	NI result;	nimfr_("-%", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics."
"nim");	result = (NI)0;
#line 437 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics.nim"
	nimln_(437, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics."
"nim");
#line 441 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics.nim"
	nimln_(441, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics."
"nim");	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));	popFrame();	return result;}

#line 414 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 396 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p) {	NIM_BOOL result;NIM_BOOL* nimErr_;	nimfr_("nimDecRefIsLastCyclicDyn", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");{nimErr_ = nimErrorFlag();	result = (NIM_BOOL)0;
#line 397 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
	nimln_(397, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");	{		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;		NI T5_;
#line 397 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"

#line 397 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		if (!!((p == NIM_NIL))) goto LA3_;

#line 398 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(398, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		nimln_(63, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		T5_ = (NI)0;		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 8));		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
#line 399 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(399, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");		{
#line 399 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"

#line 399 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
			if (!((NI)((*cell).rc & ((NI) -16)) == ((NI) 0))) goto LA8_;

#line 400 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
			nimln_(400, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");			result = NIM_TRUE;		}
		goto LA6_;
		LA8_: ;
		{			NI TM__V9bFn0kpzxTsN8MHza8M9a0A_2;
#line 403 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
			nimln_(403, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");			if (nimSubInt((*cell).rc, ((NI) 16), &TM__V9bFn0kpzxTsN8MHza8M9a0A_2)) { raiseOverflow(); goto BeforeRet_;};			(*cell).rc = (NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_2);		}
		LA6_: ;

#line 405 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(405, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");
#line 405 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		rememberCycle__LoYD9cYK9aJvrcDizBN64qaQ(result, cell, (*((TNimTypeV2**) (p))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___9bFJbrj9aRQCH3Cq7aMMwd2g)(tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA* dest) {
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	{		NIM_BOOL T3_;
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLastCyclicDyn((*dest).Sup.Sup.Sup.parent);		if (!T3_) goto LA4_;

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		nimDestroyAndDispose((*dest).Sup.Sup.Sup.parent);
	}
	LA4_: ;

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).Sup.Sup.Sup.message));

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	eqdestroy___4fQQqvAqifkWGVa4g39cI5A((&(*dest).Sup.Sup.Sup.trace));

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	{		NIM_BOOL T8_;
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		T8_ = (NIM_BOOL)0;		T8_ = nimDecRefIsLastCyclicDyn((*dest).Sup.Sup.Sup.up);		if (!T8_) goto LA9_;

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		nimDestroyAndDispose((*dest).Sup.Sup.Sup.up);
	}
	LA9_: ;
}

#line 122 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 117 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 117 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 117 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		T3_ = (a == ((NI) (-2147483647 -1)));		if (!(T3_)) goto LA4_;

#line 117 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		T3_ = (b == ((NI) -1));		LA4_: ;
		if (!T3_) goto LA5_;

#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	goto LA1_;
	LA5_: ;
	{
#line 120 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"

#line 120 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		(*res) = (NI)(a / b);	}
	LA1_: ;
	return result;}

#line 11 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size) {	void* T1_;
#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source_0, ((size_t) (size)));}

#line 2186 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size) {
#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"

#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimCopyMem(dest, source_0, size);
}

#line 19 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
static N_INLINE(void, add__A2hu7ps9a7fQ6dTDoPajZ5gsystem)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* c, TNimTypeV2* t) {	tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* colontmp_;	TNimTypeV2* colontmp__2;	NI TM__V9bFn0kpzxTsN8MHza8M9a0A_7;	nimfr_("add", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");{
#line 20 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
	nimln_(20, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");	{		NI TM__V9bFn0kpzxTsN8MHza8M9a0A_3;		NI TM__V9bFn0kpzxTsN8MHza8M9a0A_4;		tyTuple__0F3Kz25HWtRatQmCDVHWEA* d;		NI TM__V9bFn0kpzxTsN8MHza8M9a0A_5;		void* T5_;		void* T6_;		NI TM__V9bFn0kpzxTsN8MHza8M9a0A_6;
#line 20 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		if (!((*s).cap <= (*s).len)) goto LA3_;

#line 21 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		nimln_(21, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");
#line 21 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"

#line 21 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s).cap, ((NI) 3), &TM__V9bFn0kpzxTsN8MHza8M9a0A_3)) { raiseOverflow(); goto BeforeRet_;};		if (((NI) 2) == 0){ raiseDivByZero(); goto BeforeRet_;}		if (nimDivInt((NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_3), ((NI) 2), &TM__V9bFn0kpzxTsN8MHza8M9a0A_4)) { raiseOverflow(); goto BeforeRet_;};		(*s).cap = (NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_4);
#line 23 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		nimln_(23, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");
#line 23 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"

#line 23 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s).cap, ((NI) 8), &TM__V9bFn0kpzxTsN8MHza8M9a0A_5)) { raiseOverflow(); goto BeforeRet_;};		if (((NU) ((NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_5))) > (NU)(((NI) 2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;}
#line 23 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		T5_ = (void*)0;		T5_ = allocSharedImpl(((NI) (((NU) ((NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_5))))));		d = ((tyTuple__0F3Kz25HWtRatQmCDVHWEA*) (T5_));
#line 26 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		nimln_(26, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");		T6_ = (void*)0;		T6_ = ((void*) ((*s).d));
#line 26 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s).len, ((NI) 8), &TM__V9bFn0kpzxTsN8MHza8M9a0A_6)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_6)) < ((NI) 0) || ((NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_6)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_6), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 26 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) (d)), T6_, ((NI) ((NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_6))));

#line 28 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		nimln_(28, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");
#line 28 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		deallocShared(((void*) ((*s).d)));

#line 31 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		nimln_(31, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");		(*s).d = d;	}
	LA3_: ;

#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
	nimln_(33, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");	colontmp_ = c;
#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
	colontmp__2 = t;
#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
	(*s).d[(*s).len].Field0 = colontmp_;	(*s).d[(*s).len].Field1 = colontmp__2;
#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
	nimln_(34, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");	if (nimAddInt((*s).len, ((NI) 1), &TM__V9bFn0kpzxTsN8MHza8M9a0A_7)) { raiseOverflow(); goto BeforeRet_;};	(*s).len = (NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_7);	}BeforeRet_: ;
	popFrame();}

#line 99 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
static N_INLINE(void, nimTraceRefDyn)(void* q, void* env) {	void** p;	nimfr_("nimTraceRefDyn", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");
#line 100 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
	nimln_(100, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");	p = ((void**) (q));
#line 101 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
	nimln_(101, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");	{		tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ* j;		NI T5_;
#line 101 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"

#line 101 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		if (!!(((*p) == NIM_NIL))) goto LA3_;

#line 102 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(102, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");		j = ((tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ*) (env));
#line 103 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(103, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		nimln_(63, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		T5_ = (NI)0;		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) ((*p))), ((NI) 8));
#line 103 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(103, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");		add__A2hu7ps9a7fQ6dTDoPajZ5gsystem((&(*j).traceStack), ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_)), (*((TNimTypeV2**) ((*p)))));
	}
	LA3_: ;
	popFrame();}

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___zXMAlK2HRYidyULlN22cww)(tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA* dest, void* env) {
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	nimTraceRefDyn(&(*dest).Sup.Sup.Sup.parent, env);

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	eqtrace___kDvIcrGphqE2lmGa3RNr5A((&(*dest).Sup.Sup.Sup.message), env);

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	eqtrace___9cqRrToT354sdOysDOB1O2A((&(*dest).Sup.Sup.Sup.trace), env);

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	nimTraceRefDyn(&(*dest).Sup.Sup.Sup.up, env);
}

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdispose___9bFJbrj9aRQCH3Cq7aMMwd2g_2)(tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA* dest) {
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2((&(*dest).Sup.Sup.Sup.message));

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	eqdispose___4fQQqvAqifkWGVa4g39cI5A_2((&(*dest).Sup.Sup.Sup.trace));
}

#line 94 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {{
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	{		void* T5_;		void* T6_;		NI TM__V9bFn0kpzxTsN8MHza8M9a0A_10;		NI TM__V9bFn0kpzxTsN8MHza8M9a0A_11;
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (!(((NI) 0) < src.len)) goto LA3_;

#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		T5_ = (void*)0;		T5_ = ((void*) ((&(*(*dest).p).data[(*dest).len])));		T6_ = (void*)0;		T6_ = ((void*) ((&(*src.p).data[((NI) 0)])));
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (nimAddInt(src.len, ((NI) 1), &TM__V9bFn0kpzxTsN8MHza8M9a0A_10)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_10)) < ((NI) 0) || ((NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_10)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_10), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(T5_, T6_, ((NI) ((NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_10))));

#line 98 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (nimAddInt((*dest).len, src.len, &TM__V9bFn0kpzxTsN8MHza8M9a0A_11)) { raiseOverflow(); goto BeforeRet_;};		(*dest).len = (NI)(TM__V9bFn0kpzxTsN8MHza8M9a0A_11);	}
	LA3_: ;
	}BeforeRet_: ;
}

#line 29 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
N_LIB_PRIVATE N_NIMCALL(void, initNvs__MuYOO9bzgkDRfMUjRf4ypjw)(NimStringV2 part_name) {	NI32 nvs_error;NIM_BOOL* nimErr_;	nimfr_("initNvs", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim");{nimErr_ = nimErrorFlag();
#line 31 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
	nimln_(31, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim");
#line 31 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
	nvs_error = nvs_flash_init_partition(nimToCStringConv(part_name));
#line 33 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
	nimln_(33, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim");	{		NIM_BOOL T3_;
#line 33 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		T3_ = (NIM_BOOL)0;
#line 33 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		T3_ = (nvs_error == ((NI32) 4365));		if (T3_) goto LA4_;

#line 33 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		T3_ = (nvs_error == ((NI32) 4368));		LA4_: ;
		if (!T3_) goto LA5_;

#line 34 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		nimln_(34, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim");
#line 34 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		ESP_LOGI("NVS", "NVS partition: %s was truncated and needs to be erased", nimToCStringConv(part_name));

#line 36 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		nimln_(36, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim");
#line 36 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		nvs_error = nvs_flash_erase_partition(nimToCStringConv(part_name));
#line 37 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		nimln_(37, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim");		{			NimStringV2 colontmpD_;			NimStringV2 colontmpD__2;			NimStringV2 T12_;			NCSTRING T13_;			tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA* T14_;
#line 37 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 37 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
			if (!!((((NI32) 0) == nvs_error))) goto LA9_;
			colontmpD_.len = 0; colontmpD_.p = NIM_NIL;			colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
#line 38 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
			nimln_(38, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim");
#line 38 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 38 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
			T12_.len = 0; T12_.p = NIM_NIL;
#line 38 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 38 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 38 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 38 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
			T13_ = (NCSTRING)0;			T13_ = esp_err_to_name(nvs_error);			colontmpD_ = cstrToNimstr(T13_);			T12_ = rawNewString(colontmpD_.len + part_name.len + 22);appendString((&T12_), TM__V9bFn0kpzxTsN8MHza8M9a0A_9);appendString((&T12_), colontmpD_);appendString((&T12_), TM__V9bFn0kpzxTsN8MHza8M9a0A_13);appendString((&T12_), part_name);			colontmpD__2 = T12_;
#line 38 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
			T14_ = (tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA*)0;			T14_ = newEspError__2wCFtClOvrkQajXP7vJatA(colontmpD__2, nvs_error);			if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
#line 38 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
			raiseExceptionEx((Exception*)T14_, "NvsError", "initNvs", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim", 38);			goto LA11_;			{				LA11_:;			}
			{
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
				nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
				eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
				eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		}
		LA9_: ;

#line 39 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		nimln_(39, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim");
#line 39 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		ESP_LOGI("NVS", "NVS partition: %s was erased. Initializing it", nimToCStringConv(part_name));

#line 40 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		nimln_(40, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim");
#line 40 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		nvs_error = nvs_flash_init_partition(nimToCStringConv(part_name));
#line 41 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		nimln_(41, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim");		{			NimStringV2 colontmpD__3;			NimStringV2 colontmpD__4;			NimStringV2 T22_;			NCSTRING T23_;			tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA* T24_;
#line 41 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 41 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
			if (!!((((NI32) 0) == nvs_error))) goto LA19_;
			colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;			colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
#line 42 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
			nimln_(42, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim");
#line 42 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 42 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
			T22_.len = 0; T22_.p = NIM_NIL;
#line 42 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 42 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 42 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 42 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
			T23_ = (NCSTRING)0;			T23_ = esp_err_to_name(nvs_error);			colontmpD__3 = cstrToNimstr(T23_);			T22_ = rawNewString(colontmpD__3.len + part_name.len + 26);appendString((&T22_), TM__V9bFn0kpzxTsN8MHza8M9a0A_14);appendString((&T22_), colontmpD__3);appendString((&T22_), TM__V9bFn0kpzxTsN8MHza8M9a0A_16);appendString((&T22_), part_name);			colontmpD__4 = T22_;
#line 42 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
			T24_ = (tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA*)0;			T24_ = newEspError__2wCFtClOvrkQajXP7vJatA(colontmpD__4, nvs_error);			if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
#line 42 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
			raiseExceptionEx((Exception*)T24_, "NvsError", "initNvs", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim", 42);			goto LA21_;			{				LA21_:;			}
			{
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
				nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
				eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__4));

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
				eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__3));
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		}
		LA19_: ;
	}
	LA5_: ;

#line 44 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
	nimln_(44, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim");	{		NimStringV2 colontmpD__5;		NimStringV2 colontmpD__6;		NimStringV2 T32_;		NCSTRING T33_;		tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA* T34_;
#line 44 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 44 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		if (!!((((NI32) 0) == nvs_error))) goto LA29_;
		colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;		colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
#line 45 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		nimln_(45, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim");
#line 45 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 45 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		T32_.len = 0; T32_.p = NIM_NIL;
#line 45 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 45 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 45 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"

#line 45 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		T33_ = (NCSTRING)0;		T33_ = esp_err_to_name(nvs_error);		colontmpD__5 = cstrToNimstr(T33_);		T32_ = rawNewString(colontmpD__5.len + 8);appendString((&T32_), TM__V9bFn0kpzxTsN8MHza8M9a0A_17);appendString((&T32_), colontmpD__5);appendString((&T32_), TM__V9bFn0kpzxTsN8MHza8M9a0A_19);		colontmpD__6 = T32_;
#line 45 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		T34_ = (tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA*)0;		T34_ = newEspError__2wCFtClOvrkQajXP7vJatA(colontmpD__6, nvs_error);		if (NIM_UNLIKELY(*nimErr_)) goto LA31_;
#line 45 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils.nim"
		raiseExceptionEx((Exception*)T34_, "NvsError", "initNvs", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/nvs_utils"
".nim", 45);		goto LA31_;		{			LA31_:;		}
		{
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__6));

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__5));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA29_: ;
	}BeforeRet_: ;
	popFrame();}
N_LIB_PRIVATE N_NIMCALL(void, nesper_nvs_utilsDatInit000)(void) {

#line 999999 "generated_not_to_break_here"

/* section: NIM_merge_TYPE_INIT3 */
NTIv2__JiOJBwL88TSI8X2PKXXlgA_.destructor = (void*)eqdestroy___9bFJbrj9aRQCH3Cq7aMMwd2g; NTIv2__JiOJBwL88TSI8X2PKXXlgA_.size = sizeof(tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA); NTIv2__JiOJBwL88TSI8X2PKXXlgA_.align = NIM_ALIGNOF(tyObject_NvsError__JiOJBwL88TSI8X2PKXXlgA); NTIv2__JiOJBwL88TSI8X2PKXXlgA_.name = "|nesper.nvs_utils.NvsError|OSError|CatchableError|Exception|Roo"
"tObj|";
; NTIv2__JiOJBwL88TSI8X2PKXXlgA_.traceImpl = (void*)eqtrace___zXMAlK2HRYidyULlN22cww; NTIv2__JiOJBwL88TSI8X2PKXXlgA_.disposeImpl = (void*)eqdispose___9bFJbrj9aRQCH3Cq7aMMwd2g_2;}

