/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_AsyncHttpServercolonObjectType___9blhbIPPCWUB8g9b1PZ6GMnw tyObject_AsyncHttpServercolonObjectType___9blhbIPPCWUB8g9b1PZ6GMnw;
typedef struct tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_AsyncSocketDesc__D7quBEmo0QGfBsms9bXpWfg tyObject_AsyncSocketDesc__D7quBEmo0QGfBsms9bXpWfg;
typedef struct tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ;
typedef struct Exception Exception;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ;
typedef struct tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg;
typedef struct tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tyObject_HttpHeaderscolonObjectType___GM611pWlOrQ7hvMPcuAACA tyObject_HttpHeaderscolonObjectType___GM611pWlOrQ7hvMPcuAACA;
typedef struct tyTuple__kN8up2W6YKc5YA9avn5mV5w tyTuple__kN8up2W6YKc5YA9avn5mV5w;
typedef struct tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ;
typedef struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyTuple__0F3Kz25HWtRatQmCDVHWEA tyTuple__0F3Kz25HWtRatQmCDVHWEA;
typedef struct tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ;
typedef struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_AsyncHttpServercolonObjectType___9blhbIPPCWUB8g9b1PZ6GMnw {tyObject_AsyncSocketDesc__D7quBEmo0QGfBsms9bXpWfg* socket;
NIM_BOOL reuseAddr;
NIM_BOOL reusePort;
NI maxBody;
NI maxFDs;
};
struct TNimTypeV2 {void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
void* typeInfoV1;
};
struct RootObj {TNimTypeV2* m_type;};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
struct tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ {tyProc__HzVCwACFYM9cx9aV62PdjtuA function;
tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ* next;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA {  RootObj Sup;tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ callbacks;
NIM_BOOL finished;
Exception* error;
NimStringV2 errorStackTrace;
tySequence__uB9b75OUPRENsBAu4AnoePA stackTrace;
NI id;
NimStringV2 fromProc;
};
struct tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w {  tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA Sup;};
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, ClP_0) (tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ* request, void* ClE_0);
void* ClE_0;
} tyProc__czO9bLH6rWgTeb5AIcTKy5g;
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {NI rc;
NI rootIdx;
};
typedef NU8 tyEnum_HttpMethod__wfZHspwVKQPl9aWhkIcMrAA;
struct tyTuple__kN8up2W6YKc5YA9avn5mV5w {
NimStringV2 Field0;
NI Field1;
NI Field2;
};
struct tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ {NimStringV2 scheme;
NimStringV2 username;
NimStringV2 password;
NimStringV2 hostname;
NimStringV2 port;
NimStringV2 path;
NimStringV2 query;
NimStringV2 anchor;
NIM_BOOL opaque;
NIM_BOOL isIpv6;
};
struct tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ {tyObject_AsyncSocketDesc__D7quBEmo0QGfBsms9bXpWfg* client;
tyEnum_HttpMethod__wfZHspwVKQPl9aWhkIcMrAA reqMethod;
tyObject_HttpHeaderscolonObjectType___GM611pWlOrQ7hvMPcuAACA* headers;
tyTuple__kN8up2W6YKc5YA9avn5mV5w protocol;
tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ url;
NimStringV2 hostname;
NimStringV2 body;
};
typedef struct {
N_NIMCALL_PTR(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__uz49bJm19cqLWB77G7nLz3FA;
struct tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg {  RootObj Sup;NI colonstate_;
tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ req1;
tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* retFuture2;
tyProc__uz49bJm19cqLWB77G7nLz3FA nameIterVarX60gensym03_;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {NI len;
NI cap;
tyTuple__0F3Kz25HWtRatQmCDVHWEA* d;
};
struct tyTuple__0F3Kz25HWtRatQmCDVHWEA {
tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* Field0;
TNimTypeV2* Field1;
};
typedef tyTuple__0F3Kz25HWtRatQmCDVHWEA tyUncheckedArray__JDjQWOF6l7jz1gUppkfhwA[1];
struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ {tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w traceStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w toFree;
NI freed;
NI touched;
};
struct tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA {  RootObj Sup;NI colonstate_;
tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* internalTmpFutureX60gensym21_;
tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg* colonup_;
tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* result3;
};
typedef NimStringV2 tyArray__Re75IspeoxXy2oCZHwcRrA[2];
typedef N_CLOSURE_PTR(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*, TM__i1bE7XNEbzMS0CSGC81AaQ_19) (void);
typedef N_CLOSURE_PTR(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*, TM__i1bE7XNEbzMS0CSGC81AaQ_20) (void);
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA {  Exception Sup;};
struct tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ {  tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA Sup;};
typedef N_CLOSURE_PTR(void, TM__i1bE7XNEbzMS0CSGC81AaQ_24) (void);
typedef N_CLOSURE_PTR(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, TM__i1bE7XNEbzMS0CSGC81AaQ_25) (tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ* request, void* ClE_0);
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, run_server)(void);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_AsyncHttpServercolonObjectType___9blhbIPPCWUB8g9b1PZ6GMnw*, newAsyncHttpServer__3nt12aazkrwWwKRGH9bCj9bw)(NIM_BOOL reuseAddr, NIM_BOOL reusePort, NI maxBody);
N_LIB_PRIVATE N_NIMCALL(void, waitFor__zz9aVsJN0aTuFUXvzKrFo9cA)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* fut);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, serve__3Hwhe9cgs9cAS9aGgqE9bUP4yQ)(tyObject_AsyncHttpServercolonObjectType___9blhbIPPCWUB8g9b1PZ6GMnw* server, NU16 port, tyProc__czO9bLH6rWgTeb5AIcTKy5g callback, NimStringV2 address, NI assumedDescriptorsPerRequest);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, cb__I5nsTFwo9b6YJEDWE9cuf8eg)(tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ* req);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___Xa4sMYLA6aTU0cX1tdcobQ)(tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg** dest);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__LoYD9cYK9aJvrcDizBN64qaQ)(NIM_BOOL isDestroyAction, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* s, TNimTypeV2* desc);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___f4uvZ3JtBP7FuMnpJfOAXw)(tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg* dest);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___L44M9bKySk5Aux1X65E2M6w)(tyObject_AsyncSocketDesc__D7quBEmo0QGfBsms9bXpWfg* dest);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___gczQO0vzLYPQ2o5V9bLxOCQ)(tyObject_HttpHeaderscolonObjectType___GM611pWlOrQ7hvMPcuAACA* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___x0KYadoHRzeGb59bPN9a9aJQg)(tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg* dest, void* env);
static N_INLINE(void, nimTraceRef)(void* q, TNimTypeV2* desc, void* env);
static N_INLINE(void, add__A2hu7ps9a7fQ6dTDoPajZ5gsystem)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* c, TNimTypeV2* t);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOCONV(void*, allocSharedImpl)(NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___kDvIcrGphqE2lmGa3RNr5A)(NimStringV2* dest, void* env);
static N_INLINE(void, nimTraceRefDyn)(void* q, void* env);
N_LIB_PRIVATE N_NIMCALL(void, eqdispose___f4uvZ3JtBP7FuMnpJfOAXw_2)(tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___bw3oImDi8kfZ15dkDEz30w)(tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ* dest, tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ* src);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___ldMjcNJxoGs4TI2BzBMsVQ_2)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w** dest, tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, newFuture__O5FiTIx7b9aJMbTMTl7J2SQ)(NimStringV2 fromProc);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___jOdQ6K9cO5ptDh0xCPNpgpw)(tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___IVtaRNKPn7vjx4gLQQ39a9cg)(tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___8yqEppn5EKXxztXgdMUejQ)(tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA* dest, void* env);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___n48PTZE7DXcCLSudzdGWEQ)(tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg** dest, tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg* src);
static N_INLINE(void, nimIncRefCyclic)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___qFCY9cDCItk3PpsKistRZ1Q)(tyProc__uz49bJm19cqLWB77G7nLz3FA* dest, tyProc__uz49bJm19cqLWB77G7nLz3FA src);
N_LIB_PRIVATE N_CLOSURE(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*, cbIter__7jG5vexm7X9cqDocVA9bg6ZA)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimIntToStr)(NI x);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___ANG79cPfZ9aF0EzkBrohSSEw)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA** dest, tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, respond__tA4fbg9cx0zS1ZvSTtksr9bQ)(tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ* req, NI code, NimStringV2 content, tyObject_HttpHeaderscolonObjectType___GM611pWlOrQ7hvMPcuAACA* headers);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ANG79cPfZ9aF0EzkBrohSSEw_2)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA** dest, tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* src);
N_LIB_PRIVATE N_NIMCALL(void, read__kYv5uOSTaUb7hZbxPjTMHA_3)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future);
N_LIB_PRIVATE N_NIMCALL(void, complete__kYv5uOSTaUb7hZbxPjTMHA)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_CLOSURE(void, cbNimAsyncContinue__eTZHJ9cv3b5tytAAowSG09bw)(void* ClE_0);
static N_INLINE(NIM_BOOL, finished__SDzjUskCcAHghx1ZNCiJfwsystem)(tyProc__uz49bJm19cqLWB77G7nLz3FA x);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished__Cn8FMZpHNs40shvQ9cZz69aA_2)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* future);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished__zLPHIdTAe2mgu9c9c1y5dGIQ)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatSingleElem)(NimStringV2 formatstr, NimStringV2 a);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, addCallback__LPYaMz3j7An9cL9cbuTYEaOQ_2)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* future, tyProc__HzVCwACFYM9cx9aV62PdjtuA cb);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___fLSV5a9byBEbWv3rkCuCFwQ)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA** dest);
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(void, fail__KP9b34veEV0ehqMJglv63VQ)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future, Exception* error);
static N_INLINE(Exception*, getCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___rR9boD7urcxl7uyUtE46AOA)(Exception** dest, Exception* src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___9b46FHs5hLnvqpMZEZWi31w)(Exception** dest);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ldMjcNJxoGs4TI2BzBMsVQ)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w** dest, tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___n0oRld2HbzUzjAQ8qYbJqA)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ws9aI8XDuykqtPjQJyQs9cyg)(tyObject_AsyncHttpServercolonObjectType___9blhbIPPCWUB8g9b1PZ6GMnw** dest);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__i1bE7XNEbzMS0CSGC81AaQ_3 = { 33 | NIM_STRLIT_FLAG, "starting http server on port 8181" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__i1bE7XNEbzMS0CSGC81AaQ_2 = {{33, (NimStrPayload*)&TM__i1bE7XNEbzMS0CSGC81AaQ_3}}
;
N_LIB_PRIVATE TNimTypeV2 NTIv2__WRm2INbtmtncVdpT7B5jCg_;
extern TNimTypeV2 NTIv2__D7quBEmo0QGfBsms9bXpWfg_;
extern TNimTypeV2 NTIv2__GM611pWlOrQ7hvMPcuAACA_;
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__i1bE7XNEbzMS0CSGC81AaQ_11 = { 2 | NIM_STRLIT_FLAG, "cb" };
static const NimStringV2 TM__i1bE7XNEbzMS0CSGC81AaQ_12 = {2, (NimStrPayload*)&TM__i1bE7XNEbzMS0CSGC81AaQ_11};
N_LIB_PRIVATE TNimTypeV2 NTIv2__mKOKJv9cJB5BrKiB4M7SPjA_;
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__i1bE7XNEbzMS0CSGC81AaQ_15 = { 5 | NIM_STRLIT_FLAG, "req #" };
static const NimStringV2 TM__i1bE7XNEbzMS0CSGC81AaQ_16 = {5, (NimStrPayload*)&TM__i1bE7XNEbzMS0CSGC81AaQ_15};
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__i1bE7XNEbzMS0CSGC81AaQ_17 = { 30 | NIM_STRLIT_FLAG, "Hello World from nim on ESP32\012" };
static const NimStringV2 TM__i1bE7XNEbzMS0CSGC81AaQ_18 = {30, (NimStrPayload*)&TM__i1bE7XNEbzMS0CSGC81AaQ_17};
static const struct {
  NI cap; NIM_CHAR data[69+1];
} TM__i1bE7XNEbzMS0CSGC81AaQ_21 = { 69 | NIM_STRLIT_FLAG, "Async procedure ($1) yielded `nil`, are you await\'ing a `nil` F"
"uture\?" };
static const NimStringV2 TM__i1bE7XNEbzMS0CSGC81AaQ_22 = {69, (NimStrPayload*)&TM__i1bE7XNEbzMS0CSGC81AaQ_21};
extern TNimTypeV2 NTIv2__PtYxPmY5X0dorfvxAFbJpQ_;
static const NimStringV2 TM__i1bE7XNEbzMS0CSGC81AaQ_23 = {2, (NimStrPayload*)&TM__i1bE7XNEbzMS0CSGC81AaQ_11};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__i1bE7XNEbzMS0CSGC81AaQ_26 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__i1bE7XNEbzMS0CSGC81AaQ_27 = {0, (NimStrPayload*)&TM__i1bE7XNEbzMS0CSGC81AaQ_26};

/* section: NIM_merge_VARS */
N_LIB_PRIVATE NI count__zvvHvrQxPSNLzYJUrcYUsA = ((NI) 0);
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
extern NIM_THREADVAR Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
extern NIM_THREADVAR Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
extern NIM_THREADVAR Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;

/* section: NIM_merge_PROCS */

#line 544 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;

#line 546 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 436 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics.nim"
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {	NI result;	nimfr_("-%", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics."
"nim");	result = (NI)0;
#line 437 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics.nim"
	nimln_(437, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics."
"nim");
#line 441 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics.nim"
	nimln_(441, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics."
"nim");	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));	popFrame();	return result;}

#line 414 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 396 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p) {	NIM_BOOL result;NIM_BOOL* nimErr_;	nimfr_("nimDecRefIsLastCyclicDyn", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");{nimErr_ = nimErrorFlag();	result = (NIM_BOOL)0;
#line 397 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
	nimln_(397, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");	{		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;		NI T5_;
#line 397 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"

#line 397 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		if (!!((p == NIM_NIL))) goto LA3_;

#line 398 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(398, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		nimln_(63, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		T5_ = (NI)0;		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 8));		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
#line 399 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(399, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");		{
#line 399 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"

#line 399 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
			if (!((NI)((*cell).rc & ((NI) -16)) == ((NI) 0))) goto LA8_;

#line 400 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
			nimln_(400, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");			result = NIM_TRUE;		}
		goto LA6_;
		LA8_: ;
		{			NI TM__i1bE7XNEbzMS0CSGC81AaQ_4;
#line 403 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
			nimln_(403, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");			if (nimSubInt((*cell).rc, ((NI) 16), &TM__i1bE7XNEbzMS0CSGC81AaQ_4)) { raiseOverflow(); goto BeforeRet_;};			(*cell).rc = (NI)(TM__i1bE7XNEbzMS0CSGC81AaQ_4);		}
		LA6_: ;

#line 405 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(405, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");
#line 405 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		rememberCycle__LoYD9cYK9aJvrcDizBN64qaQ(result, cell, (*((TNimTypeV2**) (p))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___Xa4sMYLA6aTU0cX1tdcobQ)(tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg** dest) {
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	{		NIM_BOOL T3_;
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"

#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLastCyclicDyn((*dest));		if (!T3_) goto LA4_;

#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"

#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
		nimDestroyAndDispose((*dest));
	}
	LA4_: ;
}

#line 186 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {	NIM_BOOL result;	nimfr_("nimDecRefIsLast", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");{	result = (NIM_BOOL)0;
#line 187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
	nimln_(187, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");	{		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;		NI T5_;
#line 187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"

#line 187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		if (!!((p == NIM_NIL))) goto LA3_;

#line 188 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		nimln_(188, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		nimln_(63, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		T5_ = (NI)0;		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 8));		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
#line 195 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		nimln_(195, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");		{
#line 195 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"

#line 195 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
			if (!((NI)((*cell).rc & ((NI) -16)) == ((NI) 0))) goto LA8_;

#line 196 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
			nimln_(196, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");			result = NIM_TRUE;		}
		goto LA6_;
		LA8_: ;
		{			NI TM__i1bE7XNEbzMS0CSGC81AaQ_5;
#line 200 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
			nimln_(200, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");			if (nimSubInt((*cell).rc, ((NI) 16), &TM__i1bE7XNEbzMS0CSGC81AaQ_5)) { raiseOverflow(); goto BeforeRet_;};			(*cell).rc = (NI)(TM__i1bE7XNEbzMS0CSGC81AaQ_5);		}
		LA6_: ;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___f4uvZ3JtBP7FuMnpJfOAXw)(tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg* dest) {
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	{		NIM_BOOL T3_;
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLast((*dest).req1.client);		if (!T3_) goto LA4_;

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		eqdestroy___L44M9bKySk5Aux1X65E2M6w((*dest).req1.client);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		nimRawDispose((*dest).req1.client, ((NI) 4));
	}
	LA4_: ;

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	{		NIM_BOOL T8_;
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		T8_ = (NIM_BOOL)0;		T8_ = nimDecRefIsLast((*dest).req1.headers);		if (!T8_) goto LA9_;

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		eqdestroy___gczQO0vzLYPQ2o5V9bLxOCQ((*dest).req1.headers);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		nimRawDispose((*dest).req1.headers, ((NI) 4));
	}
	LA9_: ;

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).req1.protocol.Field0));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).req1.url.scheme));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).req1.url.username));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).req1.url.password));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).req1.url.hostname));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).req1.url.port));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).req1.url.path));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).req1.url.query));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).req1.url.anchor));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).req1.hostname));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).req1.body));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	{		NIM_BOOL T13_;
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		T13_ = (NIM_BOOL)0;		T13_ = nimDecRefIsLastCyclicDyn((*dest).retFuture2);		if (!T13_) goto LA14_;

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		nimDestroyAndDispose((*dest).retFuture2);
	}
	LA14_: ;

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	{		NIM_BOOL T18_;
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		T18_ = (NIM_BOOL)0;		T18_ = nimDecRefIsLastCyclicDyn((*dest).nameIterVarX60gensym03_.ClE_0);		if (!T18_) goto LA19_;

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		nimDestroyAndDispose((*dest).nameIterVarX60gensym03_.ClE_0);
	}
	LA19_: ;
}

#line 122 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 117 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 117 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 117 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		T3_ = (a == ((NI) (-2147483647 -1)));		if (!(T3_)) goto LA4_;

#line 117 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		T3_ = (b == ((NI) -1));		LA4_: ;
		if (!T3_) goto LA5_;

#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	goto LA1_;
	LA5_: ;
	{
#line 120 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"

#line 120 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		(*res) = (NI)(a / b);	}
	LA1_: ;
	return result;}

#line 11 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size) {	void* T1_;
#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source_0, ((size_t) (size)));}

#line 2186 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size) {
#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"

#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimCopyMem(dest, source_0, size);
}

#line 19 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
static N_INLINE(void, add__A2hu7ps9a7fQ6dTDoPajZ5gsystem)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* c, TNimTypeV2* t) {	tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* colontmp_;	TNimTypeV2* colontmp__2;	NI TM__i1bE7XNEbzMS0CSGC81AaQ_10;	nimfr_("add", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");{
#line 20 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
	nimln_(20, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");	{		NI TM__i1bE7XNEbzMS0CSGC81AaQ_6;		NI TM__i1bE7XNEbzMS0CSGC81AaQ_7;		tyTuple__0F3Kz25HWtRatQmCDVHWEA* d;		NI TM__i1bE7XNEbzMS0CSGC81AaQ_8;		void* T5_;		void* T6_;		NI TM__i1bE7XNEbzMS0CSGC81AaQ_9;
#line 20 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		if (!((*s).cap <= (*s).len)) goto LA3_;

#line 21 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		nimln_(21, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");
#line 21 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"

#line 21 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s).cap, ((NI) 3), &TM__i1bE7XNEbzMS0CSGC81AaQ_6)) { raiseOverflow(); goto BeforeRet_;};		if (((NI) 2) == 0){ raiseDivByZero(); goto BeforeRet_;}		if (nimDivInt((NI)(TM__i1bE7XNEbzMS0CSGC81AaQ_6), ((NI) 2), &TM__i1bE7XNEbzMS0CSGC81AaQ_7)) { raiseOverflow(); goto BeforeRet_;};		(*s).cap = (NI)(TM__i1bE7XNEbzMS0CSGC81AaQ_7);
#line 23 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		nimln_(23, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");
#line 23 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"

#line 23 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s).cap, ((NI) 8), &TM__i1bE7XNEbzMS0CSGC81AaQ_8)) { raiseOverflow(); goto BeforeRet_;};		if (((NU) ((NI)(TM__i1bE7XNEbzMS0CSGC81AaQ_8))) > (NU)(((NI) 2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;}
#line 23 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		T5_ = (void*)0;		T5_ = allocSharedImpl(((NI) (((NU) ((NI)(TM__i1bE7XNEbzMS0CSGC81AaQ_8))))));		d = ((tyTuple__0F3Kz25HWtRatQmCDVHWEA*) (T5_));
#line 26 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		nimln_(26, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");		T6_ = (void*)0;		T6_ = ((void*) ((*s).d));
#line 26 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s).len, ((NI) 8), &TM__i1bE7XNEbzMS0CSGC81AaQ_9)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__i1bE7XNEbzMS0CSGC81AaQ_9)) < ((NI) 0) || ((NI)(TM__i1bE7XNEbzMS0CSGC81AaQ_9)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__i1bE7XNEbzMS0CSGC81AaQ_9), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 26 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) (d)), T6_, ((NI) ((NI)(TM__i1bE7XNEbzMS0CSGC81AaQ_9))));

#line 28 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		nimln_(28, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");
#line 28 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		deallocShared(((void*) ((*s).d)));

#line 31 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
		nimln_(31, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");		(*s).d = d;	}
	LA3_: ;

#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
	nimln_(33, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");	colontmp_ = c;
#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
	colontmp__2 = t;
#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
	(*s).d[(*s).len].Field0 = colontmp_;	(*s).d[(*s).len].Field1 = colontmp__2;
#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2.nim"
	nimln_(34, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/cellseqs_v2."
"nim");	if (nimAddInt((*s).len, ((NI) 1), &TM__i1bE7XNEbzMS0CSGC81AaQ_10)) { raiseOverflow(); goto BeforeRet_;};	(*s).len = (NI)(TM__i1bE7XNEbzMS0CSGC81AaQ_10);	}BeforeRet_: ;
	popFrame();}

#line 93 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
static N_INLINE(void, nimTraceRef)(void* q, TNimTypeV2* desc, void* env) {	void** p;	nimfr_("nimTraceRef", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");
#line 94 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
	nimln_(94, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");	p = ((void**) (q));
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
	nimln_(95, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");	{		tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ* j;		NI T5_;
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"

#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		if (!!(((*p) == NIM_NIL))) goto LA3_;

#line 96 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(96, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");		j = ((tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ*) (env));
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(97, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		nimln_(63, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		T5_ = (NI)0;		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) ((*p))), ((NI) 8));
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(97, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");		add__A2hu7ps9a7fQ6dTDoPajZ5gsystem((&(*j).traceStack), ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_)), desc);
	}
	LA3_: ;
	popFrame();}

#line 99 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
static N_INLINE(void, nimTraceRefDyn)(void* q, void* env) {	void** p;	nimfr_("nimTraceRefDyn", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");
#line 100 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
	nimln_(100, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");	p = ((void**) (q));
#line 101 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
	nimln_(101, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");	{		tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ* j;		NI T5_;
#line 101 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"

#line 101 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		if (!!(((*p) == NIM_NIL))) goto LA3_;

#line 102 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(102, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");		j = ((tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ*) (env));
#line 103 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(103, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		nimln_(63, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		T5_ = (NI)0;		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) ((*p))), ((NI) 8));
#line 103 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
		nimln_(103, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");		add__A2hu7ps9a7fQ6dTDoPajZ5gsystem((&(*j).traceStack), ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_)), (*((TNimTypeV2**) ((*p)))));
	}
	LA3_: ;
	popFrame();}

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___x0KYadoHRzeGb59bPN9a9aJQg)(tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg* dest, void* env) {
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	nimTraceRef(&(*dest).req1.client, (&NTIv2__D7quBEmo0QGfBsms9bXpWfg_), env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	nimTraceRef(&(*dest).req1.headers, (&NTIv2__GM611pWlOrQ7hvMPcuAACA_), env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqtrace___kDvIcrGphqE2lmGa3RNr5A((&(*dest).req1.protocol.Field0), env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqtrace___kDvIcrGphqE2lmGa3RNr5A((&(*dest).req1.url.scheme), env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqtrace___kDvIcrGphqE2lmGa3RNr5A((&(*dest).req1.url.username), env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqtrace___kDvIcrGphqE2lmGa3RNr5A((&(*dest).req1.url.password), env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqtrace___kDvIcrGphqE2lmGa3RNr5A((&(*dest).req1.url.hostname), env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqtrace___kDvIcrGphqE2lmGa3RNr5A((&(*dest).req1.url.port), env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqtrace___kDvIcrGphqE2lmGa3RNr5A((&(*dest).req1.url.path), env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqtrace___kDvIcrGphqE2lmGa3RNr5A((&(*dest).req1.url.query), env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqtrace___kDvIcrGphqE2lmGa3RNr5A((&(*dest).req1.url.anchor), env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqtrace___kDvIcrGphqE2lmGa3RNr5A((&(*dest).req1.hostname), env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqtrace___kDvIcrGphqE2lmGa3RNr5A((&(*dest).req1.body), env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	nimTraceRefDyn(&(*dest).retFuture2, env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	nimTraceRefDyn((&(*dest).nameIterVarX60gensym03_.ClE_0), env);
}

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdispose___f4uvZ3JtBP7FuMnpJfOAXw_2)(tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg* dest) {
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2((&(*dest).req1.protocol.Field0));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2((&(*dest).req1.url.scheme));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2((&(*dest).req1.url.username));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2((&(*dest).req1.url.password));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2((&(*dest).req1.url.hostname));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2((&(*dest).req1.url.port));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2((&(*dest).req1.url.path));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2((&(*dest).req1.url.query));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2((&(*dest).req1.url.anchor));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2((&(*dest).req1.hostname));

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2((&(*dest).req1.body));
}

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___jOdQ6K9cO5ptDh0xCPNpgpw)(tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA** dest) {
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	{		NIM_BOOL T3_;
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLastCyclicDyn((*dest));		if (!T3_) goto LA4_;

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		nimDestroyAndDispose((*dest));
	}
	LA4_: ;
}

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___IVtaRNKPn7vjx4gLQQ39a9cg)(tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA* dest) {
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	{		NIM_BOOL T3_;
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLastCyclicDyn((*dest).internalTmpFutureX60gensym21_);		if (!T3_) goto LA4_;

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		nimDestroyAndDispose((*dest).internalTmpFutureX60gensym21_);
	}
	LA4_: ;

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	{		NIM_BOOL T8_;
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		T8_ = (NIM_BOOL)0;		T8_ = nimDecRefIsLastCyclicDyn((*dest).colonup_);		if (!T8_) goto LA9_;

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		nimDestroyAndDispose((*dest).colonup_);
	}
	LA9_: ;

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	{		NIM_BOOL T13_;
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		T13_ = (NIM_BOOL)0;		T13_ = nimDecRefIsLastCyclicDyn((*dest).result3);		if (!T13_) goto LA14_;

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		nimDestroyAndDispose((*dest).result3);
	}
	LA14_: ;
}

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___8yqEppn5EKXxztXgdMUejQ)(tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA* dest, void* env) {
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	nimTraceRefDyn(&(*dest).internalTmpFutureX60gensym21_, env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	nimTraceRefDyn(&(*dest).colonup_, env);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	nimTraceRefDyn(&(*dest).result3, env);
}

#line 42 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
static N_INLINE(void, nimIncRefCyclic)(void* p) {	tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* h;	NI T1_;	NI TM__i1bE7XNEbzMS0CSGC81AaQ_13;	nimfr_("nimIncRefCyclic", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");{
#line 43 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
	nimln_(43, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
	nimln_(63, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
	T1_ = (NI)0;	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 8));	h = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T1_));
#line 44 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
	nimln_(44, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");	if (nimAddInt((*h).rc, ((NI) 16), &TM__i1bE7XNEbzMS0CSGC81AaQ_13)) { raiseOverflow(); goto BeforeRet_;};	(*h).rc = (NI)(TM__i1bE7XNEbzMS0CSGC81AaQ_13);
#line 38 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
	nimln_(38, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim");
#line 38 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/orc.nim"
	(*h).rc = (NI)((*h).rc & ((NI) -4));	}BeforeRet_: ;
	popFrame();}

#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___n48PTZE7DXcCLSudzdGWEQ)(tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg** dest, tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg* src) {	tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg* colontmp_;
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	colontmp_ = (*dest);
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	{		if (!src) goto LA3_;

#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"

#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
		nimIncRefCyclic(src);
	}
	LA3_: ;

#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	(*dest) = src;
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	{		NIM_BOOL T7_;
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"

#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
		T7_ = (NIM_BOOL)0;		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);		if (!T7_) goto LA8_;

#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"

#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
		nimDestroyAndDispose(colontmp_);
	}
	LA8_: ;
}

#line 218 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
N_LIB_PRIVATE N_CLOSURE(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*, cbIter__7jG5vexm7X9cqDocVA9bg6ZA)(void* ClE_0) {	tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* result;	tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA* colonenvP_;NIM_BOOL* nimErr_;	nimfr_("cbIter", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");{nimErr_ = nimErrorFlag();	result = (tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*)0;	colonenvP_ = (tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA*) ClE_0;
#line 7 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	nimln_(7, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");	while (1) {		if (!1) goto LA1;
		{			switch ((*colonenvP_).colonstate_) {
			case -1:
			 goto BeforeRet_;
			case 0: goto STATE0;
			case 1: goto STATE1;
			case 2: goto STATE2;
			case 3: goto STATE3;
			}
			STATE0: ;			{				NimStringV2 colontmpD_;				NI TM__i1bE7XNEbzMS0CSGC81AaQ_14;				tyArray__Re75IspeoxXy2oCZHwcRrA T5_;				tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* T6_;				tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* T7_;				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
#line 7 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
				if (nimAddInt(count__zvvHvrQxPSNLzYJUrcYUsA, ((NI) 1), &TM__i1bE7XNEbzMS0CSGC81AaQ_14)) { raiseOverflow(); goto LA4_;};				count__zvvHvrQxPSNLzYJUrcYUsA = (NI)(TM__i1bE7XNEbzMS0CSGC81AaQ_14);
#line 8 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
				nimln_(8, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");				T5_[0] = TM__i1bE7XNEbzMS0CSGC81AaQ_16;
#line 8 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"

#line 8 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
				colontmpD_ = nimIntToStr(count__zvvHvrQxPSNLzYJUrcYUsA);				T5_[1] = colontmpD_;				echoBinSafe(T5_, 2);
#line 158 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.nim"
				nimln_(158, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.n"
"im");
#line 9 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
				nimln_(9, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");
#line 9 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
				T6_ = (tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*)0;				T6_ = respond__tA4fbg9cx0zS1ZvSTtksr9bQ((&(*(*colonenvP_).colonup_).req1), ((NI) 200), TM__i1bE7XNEbzMS0CSGC81AaQ_18, ((tyObject_HttpHeaderscolonObjectType___GM611pWlOrQ7hvMPcuAACA*) NIM_NIL));				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;				T7_ = (tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*)0;				T7_ = &T6_->Sup;
#line 158 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.nim"
				nimln_(158, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.n"
"im");				eqsink___ANG79cPfZ9aF0EzkBrohSSEw(&(*colonenvP_).internalTmpFutureX60gensym21_, T7_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;				(*colonenvP_).colonstate_ = ((NI) 1);
#line 144 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				nimln_(144, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");
#line 158 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.nim"
				nimln_(158, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.n"
"im");
#line 158 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.nim"
				eqcopy___ANG79cPfZ9aF0EzkBrohSSEw_2(&result, (*colonenvP_).internalTmpFutureX60gensym21_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
				nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
				eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
				goto BeforeRet_;
				{					LA4_:;				}
				{
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
					eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;			}
			STATE1: ;
#line 145 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
			nimln_(145, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");
#line 145 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
			read__kYv5uOSTaUb7hZbxPjTMHA_3(((tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*) ((*colonenvP_).internalTmpFutureX60gensym21_)));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;			(*colonenvP_).colonstate_ = ((NI) 2);
#line 9 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
			nimln_(9, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");			goto LA2;
			STATE2: ;
#line 7 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
			nimln_(7, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");
#line 7 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
			complete__kYv5uOSTaUb7hZbxPjTMHA((*(*colonenvP_).colonup_).retFuture2);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;			(*colonenvP_).colonstate_ = ((NI) 3);			goto LA2;
			STATE3: ;			(*colonenvP_).colonstate_ = ((NI) -1);			goto LA2;
		} LA2: ;
	} LA1: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 22 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 24 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 2400 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
static N_INLINE(NIM_BOOL, finished__SDzjUskCcAHghx1ZNCiJfwsystem)(tyProc__uz49bJm19cqLWB77G7nLz3FA x) {	NIM_BOOL result;	nimfr_("finished", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");	result = (NIM_BOOL)0;
#line 2402 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimln_(2402, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");	    result = ((NI*) x.ClE_0)[1] < 0;
    
	popFrame();	return result;}

#line 2359 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
static N_INLINE(Exception*, getCurrentException)(void) {	Exception* result;	nimfr_("getCurrentException", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");	result = (Exception*)0;
#line 327 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/threads.nim"
	nimln_(327, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/threads.nim");
#line 327 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/threads.nim"
	eqcopy___rR9boD7urcxl7uyUtE46AOA(&result, currException__9bVPeDJlYTi9bQApZpfH8wjg);
	popFrame();	return result;}

#line 124 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, popCurrentException)(void) {
#line 327 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/threads.nim"

#line 327 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/threads.nim"
	eqcopy___rR9boD7urcxl7uyUtE46AOA(&currException__9bVPeDJlYTi9bQApZpfH8wjg, (*currException__9bVPeDJlYTi9bQApZpfH8wjg).up);
}

#line 261 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
N_LIB_PRIVATE N_CLOSURE(void, cbNimAsyncContinue__eTZHJ9cv3b5tytAAowSG09bw)(void* ClE_0) {	tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg* colonenvP_;NIM_BOOL oldNimErrFin7_;NIM_BOOL* nimErr_;	nimfr_("cbNimAsyncContinue", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");{nimErr_ = nimErrorFlag();	colonenvP_ = (tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg*) ClE_0;
#line 28 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	nimln_(28, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");	{		NIM_BOOL T4_;		tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* nextX60gensym0_;		tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* T8_;
#line 28 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 28 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 28 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		T4_ = (NIM_BOOL)0;		T4_ = finished__SDzjUskCcAHghx1ZNCiJfwsystem((*colonenvP_).nameIterVarX60gensym03_);		if (!!(T4_)) goto LA5_;
		nextX60gensym0_ = (tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*)0;
#line 29 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		nimln_(29, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");		T8_ = (tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*)0;		T8_ = (*colonenvP_).nameIterVarX60gensym03_.ClP_0((*colonenvP_).nameIterVarX60gensym03_.ClE_0);		if (NIM_UNLIKELY(*nimErr_)) goto LA7_;		nextX60gensym0_ = T8_;		{
#line 31 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
			nimln_(31, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");			while (1) {				NIM_BOOL T11_;				tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* T13_;
#line 31 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				T11_ = (NIM_BOOL)0;
#line 31 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 31 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				T11_ = !((nextX60gensym0_ == 0));				if (!(T11_)) goto LA12_;

#line 31 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 31 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				T11_ = finished__Cn8FMZpHNs40shvQ9cZz69aA_2(nextX60gensym0_);				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;				LA12_: ;
				if (!T11_) goto LA10;

#line 158 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.nim"
				nimln_(158, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.n"
"im");
#line 32 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				nimln_(32, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");				T13_ = (tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*)0;				T13_ = (*colonenvP_).nameIterVarX60gensym03_.ClP_0((*colonenvP_).nameIterVarX60gensym03_.ClE_0);				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
#line 158 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.nim"
				nimln_(158, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.n"
"im");				eqsink___ANG79cPfZ9aF0EzkBrohSSEw(&nextX60gensym0_, T13_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				nimln_(33, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");				{					NIM_BOOL T16_;
#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
					T16_ = (NIM_BOOL)0;					T16_ = finished__SDzjUskCcAHghx1ZNCiJfwsystem((*colonenvP_).nameIterVarX60gensym03_);					if (!T16_) goto LA17_;

#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
					nimln_(34, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");					goto LA9;
				}
				LA17_: ;
			} LA10: ;
		} LA9: ;

#line 36 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		nimln_(36, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");		{
#line 36 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
			if (!(nextX60gensym0_ == ((tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*) NIM_NIL))) goto LA21_;

#line 37 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
			nimln_(37, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");			{				NIM_BOOL T25_;				NimStringV2 msgX60gensym0_;				tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ* T28_;
#line 37 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 37 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 37 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				T25_ = (NIM_BOOL)0;				T25_ = finished__zLPHIdTAe2mgu9c9c1y5dGIQ((*colonenvP_).retFuture2);				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;				if (!!(T25_)) goto LA26_;

#line 38 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				nimln_(38, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");				msgX60gensym0_ = TM__i1bE7XNEbzMS0CSGC81AaQ_22;				T28_ = (tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ*)0;				T28_ = (tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ*) nimNewObj(sizeof(tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ), NIM_ALIGNOF(tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ));				(*T28_).Sup.Sup.Sup.m_type = (&NTIv2__PtYxPmY5X0dorfvxAFbJpQ_);				(*T28_).Sup.Sup.name = "AssertionDefect";
#line 40 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				nimln_(40, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");
#line 40 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				(*T28_).Sup.Sup.message = nsuFormatSingleElem(msgX60gensym0_, TM__i1bE7XNEbzMS0CSGC81AaQ_23);				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;				(*T28_).Sup.Sup.parent = ((Exception*) NIM_NIL);
#line 40 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				raiseExceptionEx((Exception*)T28_, "AssertionDefect", "cbNimAsyncContinue", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim", 40);				goto LA7_;			}
			LA26_: ;
		}
		goto LA19_;
		LA21_: ;
		{			tyProc__HzVCwACFYM9cx9aV62PdjtuA T30_;
#line 44 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
			nimln_(44, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");			nimZeroMem((void*)(&T30_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));			T30_.ClP_0 = cbNimAsyncContinue__eTZHJ9cv3b5tytAAowSG09bw; T30_.ClE_0 = colonenvP_;
#line 44 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
			addCallback__LPYaMz3j7An9cL9cbuTYEaOQ_2(nextX60gensym0_, T30_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA7_;		}
		LA19_: ;
		{			LA7_:;		}
		{			oldNimErrFin7_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 158 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.nim"
			nimln_(158, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.n"
"im");
#line 158 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.nim"
			eqdestroy___fLSV5a9byBEbWv3rkCuCFwQ(&nextX60gensym0_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;			*nimErr_ = oldNimErrFin7_;		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	}
	LA5_: ;
	if (NIM_UNLIKELY(*nimErr_)) {		LA1_:;		{			*nimErr_ = NIM_FALSE;
#line 48 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
			nimln_(48, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");			{				NIM_BOOL T38_;
#line 48 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 48 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				T38_ = (NIM_BOOL)0;				T38_ = finished__zLPHIdTAe2mgu9c9c1y5dGIQ((*colonenvP_).retFuture2);				if (NIM_UNLIKELY(*nimErr_)) goto LA34_;				if (!T38_) goto LA39_;

#line 51 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				nimln_(51, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");				reraiseException();				goto LA34_;			}
			goto LA36_;
			LA39_: ;
			{				Exception* colontmpD_;				colontmpD_ = (Exception*)0;
#line 53 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				nimln_(53, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");
#line 53 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"

#line 53 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				colontmpD_ = getCurrentException();
#line 53 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
				fail__KP9b34veEV0ehqMJglv63VQ((*colonenvP_).retFuture2, colontmpD_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA42_;				{					LA42_:;				}
				{
#line 327 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/threads.nim"
					nimln_(327, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/threads.nim");
#line 327 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/threads.nim"
					eqdestroy___9b46FHs5hLnvqpMZEZWi31w(&colontmpD_);
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA34_;			}
			LA36_: ;
			popCurrentException();			LA34_:;		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, cb__I5nsTFwo9b6YJEDWE9cuf8eg)(tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ* req) {	tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* result;	tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg* colonenv_;	tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA* colonenv__2;	tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* T2_;	tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA* blitTmp;	tyProc__uz49bJm19cqLWB77G7nLz3FA T3_;	tyProc__HzVCwACFYM9cx9aV62PdjtuA T4_;NIM_BOOL oldNimErrFin1_;NIM_BOOL* nimErr_;	nimfr_("cb", "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");{nimErr_ = nimErrorFlag();	result = (tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*)0;	colonenv_ = (tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg*)0;	colonenv__2 = (tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA*)0;
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	nimln_(6, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	eqdestroy___Xa4sMYLA6aTU0cX1tdcobQ(&colonenv_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 240 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimln_(240, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");	colonenv_ = (tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg*) nimNewObj(sizeof(tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg), NIM_ALIGNOF(tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg));	(*colonenv_).Sup.m_type = (&NTIv2__WRm2INbtmtncVdpT7B5jCg_);
#line 200 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	nimln_(200, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");
#line 200 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqcopy___bw3oImDi8kfZ15dkDEz30w((&(*colonenv_).req1), req);

#line 158 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.nim"
	nimln_(158, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.n"
"im");
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	nimln_(6, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	T2_ = (tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*)0;	T2_ = newFuture__O5FiTIx7b9aJMbTMTl7J2SQ(TM__i1bE7XNEbzMS0CSGC81AaQ_12);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 158 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.nim"
	nimln_(158, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.n"
"im");	eqsink___ldMjcNJxoGs4TI2BzBMsVQ_2(&(*colonenv_).retFuture2, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	nimln_(262, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdestroy___jOdQ6K9cO5ptDh0xCPNpgpw(&colonenv__2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 240 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimln_(240, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");	colonenv__2 = (tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA*) nimNewObj(sizeof(tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA), NIM_ALIGNOF(tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA));	(*colonenv__2).Sup.m_type = (&NTIv2__mKOKJv9cJB5BrKiB4M7SPjA_);
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	nimln_(6, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	eqcopy___n48PTZE7DXcCLSudzdGWEQ(&(*colonenv__2).colonup_, colonenv_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 2400 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimln_(2400, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	nimln_(262, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");	blitTmp = colonenv__2;
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	colonenv__2 = 0;	nimZeroMem((void*)(&T3_), sizeof(tyProc__uz49bJm19cqLWB77G7nLz3FA));	T3_.ClP_0 = cbIter__7jG5vexm7X9cqDocVA9bg6ZA; T3_.ClE_0 = blitTmp;
#line 2400 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimln_(2400, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");	eqsink___qFCY9cDCItk3PpsKistRZ1Q((&(*colonenv_).nameIterVarX60gensym03_), T3_);

#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	nimln_(262, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");	nimZeroMem((void*)(&T4_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));	T4_.ClP_0 = cbNimAsyncContinue__eTZHJ9cv3b5tytAAowSG09bw; T4_.ClE_0 = colonenv_;	T4_.ClE_0? T4_.ClP_0(T4_.ClE_0):((TM__i1bE7XNEbzMS0CSGC81AaQ_24)(T4_.ClP_0))();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 9 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	nimln_(9, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");
#line 158 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.nim"
	nimln_(158, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.n"
"im");
#line 158 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.nim"
	eqcopy___ldMjcNJxoGs4TI2BzBMsVQ(&result, (*colonenv_).retFuture2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	nimln_(262, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
	eqdestroy___jOdQ6K9cO5ptDh0xCPNpgpw(&colonenv__2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	nimln_(6, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	eqdestroy___Xa4sMYLA6aTU0cX1tdcobQ(&colonenv_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	goto BeforeRet_;
	{		LA1_:;	}
	{		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		nimln_(262, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim");
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncmacro.nim"
		eqdestroy___jOdQ6K9cO5ptDh0xCPNpgpw(&colonenv__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
		nimln_(6, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");
#line 6 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
		eqdestroy___Xa4sMYLA6aTU0cX1tdcobQ(&colonenv_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		*nimErr_ = oldNimErrFin1_;	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 12 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
N_LIB_PRIVATE N_NIMCALL(void, run_server)(void) {	tyObject_AsyncHttpServercolonObjectType___9blhbIPPCWUB8g9b1PZ6GMnw* server;	tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* colontmpD_;	tyProc__czO9bLH6rWgTeb5AIcTKy5g T2_;NIM_BOOL oldNimErrFin1_;NIM_BOOL* nimErr_;	nimfr_("run_server", "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");{nimErr_ = nimErrorFlag();	server = (tyObject_AsyncHttpServercolonObjectType___9blhbIPPCWUB8g9b1PZ6GMnw*)0;	colontmpD_ = (tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*)0;
#line 13 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	nimln_(13, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");	echoBinSafe(TM__i1bE7XNEbzMS0CSGC81AaQ_2, 1);
#line 14 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	nimln_(14, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");
#line 14 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	server = newAsyncHttpServer__3nt12aazkrwWwKRGH9bCj9bw(NIM_TRUE, NIM_FALSE, ((NI) 8388608));	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 16 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	nimln_(16, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src"
"/esp32_ads115_playground/server.nim");
#line 16 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	nimZeroMem((void*)(&T2_), sizeof(tyProc__czO9bLH6rWgTeb5AIcTKy5g));	T2_.ClP_0 = ((TM__i1bE7XNEbzMS0CSGC81AaQ_25) (cb__I5nsTFwo9b6YJEDWE9cuf8eg)); T2_.ClE_0 = NIM_NIL;
#line 16 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	colontmpD_ = serve__3Hwhe9cgs9cAS9aGgqE9bUP4yQ(server, ((NU16) 8181), T2_, TM__i1bE7XNEbzMS0CSGC81AaQ_27, ((NI) -1));	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 16 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/src/esp32_ads115_playground/server.nim"
	waitFor__zz9aVsJN0aTuFUXvzKrFo9cA(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	{		LA1_:;	}
	{		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 158 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.nim"
		nimln_(158, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.n"
"im");
#line 158 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asyncfutures.nim"
		eqdestroy___n0oRld2HbzUzjAQ8qYbJqA(&colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asynchttpserver.nim"
		nimln_(78, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asynchttpserve"
"r.nim");
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/asynchttpserver.nim"
		eqdestroy___ws9aI8XDuykqtPjQJyQs9cyg(&server);
		*nimErr_ = oldNimErrFin1_;	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}
N_LIB_PRIVATE N_NIMCALL(void, esp32_ads115_playground_serverDatInit000)(void) {

#line 999999 "generated_not_to_break_here"

/* section: NIM_merge_TYPE_INIT3 */
NTIv2__WRm2INbtmtncVdpT7B5jCg_.destructor = (void*)eqdestroy___f4uvZ3JtBP7FuMnpJfOAXw; NTIv2__WRm2INbtmtncVdpT7B5jCg_.size = sizeof(tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg); NTIv2__WRm2INbtmtncVdpT7B5jCg_.align = NIM_ALIGNOF(tyObject_Env_serverdotnim_cb___WRm2INbtmtncVdpT7B5jCg); NTIv2__WRm2INbtmtncVdpT7B5jCg_.name = "|esp32_ads115_playground.server.Env_server.nim_cb|RootObj|";
; NTIv2__WRm2INbtmtncVdpT7B5jCg_.traceImpl = (void*)eqtrace___x0KYadoHRzeGb59bPN9a9aJQg; NTIv2__WRm2INbtmtncVdpT7B5jCg_.disposeImpl = (void*)eqdispose___f4uvZ3JtBP7FuMnpJfOAXw_2;NTIv2__mKOKJv9cJB5BrKiB4M7SPjA_.destructor = (void*)eqdestroy___IVtaRNKPn7vjx4gLQQ39a9cg; NTIv2__mKOKJv9cJB5BrKiB4M7SPjA_.size = sizeof(tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA); NTIv2__mKOKJv9cJB5BrKiB4M7SPjA_.align = NIM_ALIGNOF(tyObject_Env_asyncmacrodotnim_cbIter___mKOKJv9cJB5BrKiB4M7SPjA); NTIv2__mKOKJv9cJB5BrKiB4M7SPjA_.name = "|esp32_ads115_playground.server.Env_asyncmacro.nim_cbIter|RootO"
"bj|";
; NTIv2__mKOKJv9cJB5BrKiB4M7SPjA_.traceImpl = (void*)eqtrace___8yqEppn5EKXxztXgdMUejQ; NTIv2__mKOKJv9cJB5BrKiB4M7SPjA_.disposeImpl = (void*)NIM_NIL;}

