/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include "lwip/ip4_addr.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;

/* section: NIM_merge_TYPES */
typedef NU8 tyEnum_IpAddressFamily__iqqacz9cr9bcNjYY74E10wPA;
typedef NU8 tyArray__qtqsWM5aXmcpMIVmvq3kAA[16];
typedef NU8 tyArray__H8qf9bpC2ziYA2earmO8m7w[4];
struct tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA {tyEnum_IpAddressFamily__iqqacz9cr9bcNjYY74E10wPA family;
union{
struct {tyArray__qtqsWM5aXmcpMIVmvq3kAA address_v6;
} _family_1;
struct {tyArray__H8qf9bpC2ziYA2earmO8m7w address_v4;
} _family_2;
};
};
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};

/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA, toIpAddress__051sv62Ac43xDiPs9cz29b7Q)(NU32 address);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError)(NimStringV2 f);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[78+1];
} TM__9b2PQDvx1zCPsnz9apKpdsBA_2 = { 78 | NIM_STRLIT_FLAG, "\'address_v4\' is not accessible using discriminant \'family\' of t"
"ype \'IpAddress\'" };
static const NimStringV2 TM__9b2PQDvx1zCPsnz9apKpdsBA_3 = {78, (NimStrPayload*)&TM__9b2PQDvx1zCPsnz9apKpdsBA_2};

/* section: NIM_merge_VARS */
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */

#line 22 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 24 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 414 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 544 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;

#line 546 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 55 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA, toIpAddress__051sv62Ac43xDiPs9cz29b7Q)(NU32 address) {	tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA result;	nimfr_("toIpAddress", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils"
".nim");{	nimZeroMem((void*)(&result), sizeof(tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA));
#line 56 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils.nim"
	nimln_(56, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils"
".nim");	nimZeroMem((void*)(&result), sizeof(tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA));	result.family = ((tyEnum_IpAddressFamily__iqqacz9cr9bcNjYY74E10wPA) 1);	{		NI i;		NI res;		i = (NI)0;
#line 77 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
		nimln_(77, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");		res = ((NI) 0);		{
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
			nimln_(78, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");			while (1) {				NI TM__9b2PQDvx1zCPsnz9apKpdsBA_4;				NI TM__9b2PQDvx1zCPsnz9apKpdsBA_5;
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
				if (!(res <= ((NI) 3))) goto LA3;

#line 57 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils.nim"
				nimln_(57, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils"
".nim");				i = res;				if (!(((2 &((NU8)1<<((NU)(result.family)&7U)))!=0))){ raiseFieldError(TM__9b2PQDvx1zCPsnz9apKpdsBA_3); goto BeforeRet_;}				if ((NU)(i) > (NU)(3)){ raiseIndexError2(i, 3); goto BeforeRet_;}
#line 58 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils.nim"
				nimln_(58, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils"
".nim");
#line 58 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils.nim"

#line 58 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils.nim"
				if (nimMulInt(i, ((NI) 8), &TM__9b2PQDvx1zCPsnz9apKpdsBA_4)) { raiseOverflow(); goto BeforeRet_;};				result._family_2.address_v4[(i)- 0] = ((NU8) ((NU32)((NU32)(address) >> (NU32)((NI)(TM__9b2PQDvx1zCPsnz9apKpdsBA_4)))));
#line 80 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
				nimln_(80, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");				if (nimAddInt(res, ((NI) 1), &TM__9b2PQDvx1zCPsnz9apKpdsBA_5)) { raiseOverflow(); goto BeforeRet_;};				res = (NI)(TM__9b2PQDvx1zCPsnz9apKpdsBA_5);			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();	return result;}

#line 66 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA, toIpAddress__vKwhMp00EN2WY60Wl5KhKw)(ip4_addr_t ip_0) {	tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA result;NIM_BOOL* nimErr_;	nimfr_("toIpAddress", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils"
".nim");{nimErr_ = nimErrorFlag();	nimZeroMem((void*)(&result), sizeof(tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA));
#line 67 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils.nim"
	nimln_(67, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils"
".nim");
#line 67 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/net_utils.nim"
	result = toIpAddress__051sv62Ac43xDiPs9cz29b7Q(ip_0.addr);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}
