/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <freertos/FreeRTOS.h>
                      #include "freertos/event_groups.h" 
#include <freertos/FreeRTOS.h>
#include "esp_log.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA;

/* section: NIM_merge_TYPES */
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef NU8 tyEnum_IpAddressFamily__iqqacz9cr9bcNjYY74E10wPA;
typedef NU8 tyArray__qtqsWM5aXmcpMIVmvq3kAA[16];
typedef NU8 tyArray__H8qf9bpC2ziYA2earmO8m7w[4];
struct tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA {tyEnum_IpAddressFamily__iqqacz9cr9bcNjYY74E10wPA family;
union{
struct {tyArray__qtqsWM5aXmcpMIVmvq3kAA address_v6;
} _family_1;
struct {tyArray__H8qf9bpC2ziYA2earmO8m7w address_v4;
} _family_2;
};
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, app_main)(void);
N_NIMCALL(void, NimMain)(void);
N_LIB_PRIVATE N_NIMCALL(void, networkingStart__dD9aD4KwhdbrSXYXd61wpPw)(NIM_BOOL startNvs);
N_LIB_PRIVATE N_NIMCALL(void, doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q)(NI32 ret);
N_LIB_PRIVATE N_NIMCALL(NI32, networkingConnect__QPWTXSkQRoYwvMaeCcHCeg)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___cbhSLBlQm0h9cO9cfQ8lXDaw)(tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA address);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(void, run_server)(void);
N_LIB_PRIVATE N_NIMCALL(NI32, networkingDisconnect__QPWTXSkQRoYwvMaeCcHCeg_2)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringV2 msg);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_optionsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_nativesocketsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, nesper_nvs_utilsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, nesper_eventsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_tablesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_asyncfuturesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_selectorsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_asyncdispatchDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_asyncnetDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_httpcoreDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_asynchttpserverDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, esp32_ads115_playground_serverDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[111+1];
} TM__oWI4Gum6MBU79bZZj0J2cBQ_2 = { 111 | NIM_STRLIT_FLAG, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/main.nim(43, 10) `false` shouldn\'t reach here!" };
static const NimStringV2 TM__oWI4Gum6MBU79bZZj0J2cBQ_3 = {111, (NimStrPayload*)&TM__oWI4Gum6MBU79bZZj0J2cBQ_2};

/* section: NIM_merge_VARS */
extern void* networkConnectEventGroup__nmpo6Y9aPj9ceX9a5QPnFjH1Q;
extern NCSTRING networkConnectionName__WyuSNx19cWYWra9bxa5KG0vQ;
extern tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA networkIpAddr__37g5rmL1egFynkJj9cvRUzQ;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */

#line 90 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {	NCSTRING result;	result = (NCSTRING)0;
#line 91 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	{
#line 91 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (!(s.len == ((NI) 0))) goto LA3_;

#line 91 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		result = "";	}
	goto LA1_;
	LA3_: ;
	{
#line 92 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		result = ((NCSTRING) ((*s.p).data));	}
	LA1_: ;
	return result;}

#line 414 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 544 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;

#line 546 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 23 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(void, app_main)(void) {	NimStringV2 colontmpD_;	NI32 T2_;	NU32 T3_;	NI32 T4_;NIM_BOOL* nimErr_;	nimfr_("app_main", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");{nimErr_ = nimErrorFlag();	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
#line 24 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	nimln_(24, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");
#line 24 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	NimMain();

#line 23 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	nimln_(23, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/main.nim");
#line 23 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	networkingStart__dD9aD4KwhdbrSXYXd61wpPw(NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 29 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	nimln_(29, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/main.nim");
#line 30 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	nimln_(30, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/main.nim");
#line 30 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	T2_ = (NI32)0;	T2_ = networkingConnect__QPWTXSkQRoYwvMaeCcHCeg();	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 29 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	nimln_(29, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/main.nim");	doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q(T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 34 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_networking.nim"
	nimln_(34, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_networking.nim");
#line 34 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_networking.nim"

#line 34 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_networking.nim"
	T3_ = (NU32)0;	T3_ = xEventGroupWaitBits(networkConnectEventGroup__nmpo6Y9aPj9ceX9a5QPnFjH1Q, ((NU32) 2), ((int) 1), ((int) 1), portMAX_DELAY);	(void)(T3_);

#line 34 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	nimln_(34, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/main.nim");
#line 34 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	ESP_LOGI("main", "Connected to %s", networkConnectionName__WyuSNx19cWYWra9bxa5KG0vQ);

#line 35 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	nimln_(35, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/main.nim");
#line 35 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"

#line 35 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	colontmpD_ = dollar___cbhSLBlQm0h9cO9cfQ8lXDaw(networkIpAddr__37g5rmL1egFynkJj9cvRUzQ);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 35 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	ESP_LOGI("main", "IPv4 address: %s", nimToCStringConv(colontmpD_));

#line 36 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	nimln_(36, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/main.nim");
#line 36 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	ESP_LOGI("main", "network setup!\012");

#line 37 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	nimln_(37, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/main.nim");
#line 37 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	run_server();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 40 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	nimln_(40, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/main.nim");
#line 41 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	nimln_(41, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/main.nim");
#line 41 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	T4_ = (NI32)0;	T4_ = networkingDisconnect__QPWTXSkQRoYwvMaeCcHCeg_2();	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 40 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	nimln_(40, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/main.nim");	doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q(T4_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 43 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
	nimln_(43, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/main.nim");	{		if (!NIM_TRUE) goto LA7_;

#line 43 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"

#line 43 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/main.nim"
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__oWI4Gum6MBU79bZZj0J2cBQ_3);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	}
	LA7_: ;
	{		LA1_:;	}
	{
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
		nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 2161 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
static N_INLINE(void, initStackBottomWith)(void* locals) {}

N_LIB_PRIVATE void PreMainInner(void) {
	stdlib_nativesocketsInit000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	systemDatInit000();
	stdlib_optionsDatInit000();
	nesper_nvs_utilsDatInit000();
	nesper_eventsDatInit000();
	stdlib_tablesDatInit000();
	stdlib_asyncfuturesDatInit000();
	stdlib_selectorsDatInit000();
	stdlib_asyncdispatchDatInit000();
	stdlib_asyncnetDatInit000();
	stdlib_httpcoreDatInit000();
	stdlib_asynchttpserverDatInit000();
	esp32_ads115_playground_serverDatInit000();
	(*inner)();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {

#line 999999 "generated_not_to_break_here"
{
}
}

