/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include "tcpip_adapter.h"
#include "esp_event.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;

/* section: NIM_merge_TYPES */
typedef NU8 tyEnum_IpAddressFamily__iqqacz9cr9bcNjYY74E10wPA;
typedef NU8 tyArray__qtqsWM5aXmcpMIVmvq3kAA[16];
typedef NU8 tyArray__H8qf9bpC2ziYA2earmO8m7w[4];
struct tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA {tyEnum_IpAddressFamily__iqqacz9cr9bcNjYY74E10wPA family;
union{
struct {tyArray__qtqsWM5aXmcpMIVmvq3kAA address_v6;
} _family_1;
struct {tyArray__H8qf9bpC2ziYA2earmO8m7w address_v4;
} _family_2;
};
};
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, initNvs__MuYOO9bzgkDRfMUjRf4ypjw)(NimStringV2 part_name);
N_LIB_PRIVATE N_NIMCALL(void, doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q)(NI32 ret);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__FZhwp43MWIn9caXdDMMrEtA_2 = { 3 | NIM_STRLIT_FLAG, "nvs" };
static const NimStringV2 TM__FZhwp43MWIn9caXdDMMrEtA_3 = {3, (NimStrPayload*)&TM__FZhwp43MWIn9caXdDMMrEtA_2};

/* section: NIM_merge_VARS */
N_LIB_PRIVATE void* networkConnectEventGroup__nmpo6Y9aPj9ceX9a5QPnFjH1Q;
N_LIB_PRIVATE tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA networkIpAddr__37g5rmL1egFynkJj9cvRUzQ;
N_LIB_PRIVATE NCSTRING networkConnectionName__WyuSNx19cWYWra9bxa5KG0vQ;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */

#line 414 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 544 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;

#line 546 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 16 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_networking.nim"
N_LIB_PRIVATE N_NIMCALL(void, networkingStart__dD9aD4KwhdbrSXYXd61wpPw)(NIM_BOOL startNvs) {	NI32 T5_;NIM_BOOL* nimErr_;	nimfr_("networkingStart", "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_networking.nim");{nimErr_ = nimErrorFlag();
#line 20 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_networking.nim"
	nimln_(20, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_networking.nim");	{		if (!startNvs) goto LA3_;

#line 21 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_networking.nim"
		nimln_(21, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_networking.nim");
#line 21 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_networking.nim"
		initNvs__MuYOO9bzgkDRfMUjRf4ypjw(TM__FZhwp43MWIn9caXdDMMrEtA_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;

#line 25 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_networking.nim"
	nimln_(25, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_networking.nim");
#line 25 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_networking.nim"
	tcpip_adapter_init();

#line 30 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_networking.nim"
	nimln_(30, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_networking.nim");
#line 30 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_networking.nim"

#line 30 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_networking.nim"
	T5_ = (NI32)0;	T5_ = esp_event_loop_create_default();
#line 30 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_networking.nim"
	doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q(T5_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}
