/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <freertos/FreeRTOS.h>
                      #include "freertos/event_groups.h" 
#include "esp_wifi.h"
#include "esp_wifi_types.h"
#include "esp_event.h"
#include "esp_log.h"
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "tcpip_adapter.h"
#include "lwip/ip4_addr.h"
#include "esp_event_legacy.h"
#include "lwip/ip6_addr.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
typedef N_CDECL_PTR(NI32, tyProc__s7kEKFaFK8kLXuhDn4mzMA) (system_event_t* event);
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct TNimTypeV2 {void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
void* typeInfoV1;
};
struct RootObj {TNimTypeV2* m_type;};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
typedef NI32 tyEnum_tcpip_adapter_if_t__PEBEviLlkUUY9ceooWbPAEQ;
typedef NU8 tyEnum_IpAddressFamily__iqqacz9cr9bcNjYY74E10wPA;
typedef NU8 tyArray__qtqsWM5aXmcpMIVmvq3kAA[16];
typedef NU8 tyArray__H8qf9bpC2ziYA2earmO8m7w[4];
struct tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA {tyEnum_IpAddressFamily__iqqacz9cr9bcNjYY74E10wPA family;
union{
struct {tyArray__qtqsWM5aXmcpMIVmvq3kAA address_v6;
} _family_1;
struct {tyArray__H8qf9bpC2ziYA2earmO8m7w address_v4;
} _family_2;
};
};
typedef NI32 tyEnum_wifi_storage_t__V9bp3oj47VwwWqMieAivHAQ;
typedef NU8 tyArray__vEOa9c5qaE9ajWxR5R4zwfQg[32];
typedef NU8 tyArray__w5VB8h5K8DB3oWrO5U2wqg[64];
typedef NI32 tyEnum_wifi_auth_mode_t__CBw5vwoM1UZigTS51XiT6w;
typedef NI32 tyEnum_wifi_scan_method_t__WFl9aQHusEobZ9aJFhF5SIjg;
typedef NU8 tyArray__9cZQ9c8IqkFU8PfW4YTh44AQ[6];
typedef NI32 tyEnum_wifi_sort_method_t__rYF8vvv6PCslvKPXxG6Icg;
typedef NI32 tyEnum_wifi_mode_t__S2nRJJAgwwJiIUP8qNxDsw;
typedef NI32 tyEnum_esp_interface_t__RI0zKHj8l73pvqKZi9blurQ;
typedef NI32 tyEnum_system_event_id_t__XCQCjHkNb9cDoanjo7sgtnQ;
typedef NU8 tyArray__cdsir9aPB24hAk6k77P9b9bCA[8];
typedef NI32 tyEnum_wifi_event_sta_wps_fail_reason_t__KmWObxx6qP1E5Qzl0YNbbg;
typedef NU32 tyArray__FleBT9cC2nxhgiXmSYYnEKA[4];
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, wifiStart__9cjBuhsNjNjxOdp8g3aRJsA)(void);
N_LIB_PRIVATE N_NIMCALL(wifi_init_config_t, wifi_init_config_default__v9aEoJTWI9a7H65c9cz2ZEqIw)(void);
N_LIB_PRIVATE N_CDECL(void, onWifiDisconnect__kSBHaIcYkybBtM9aE24vSlA)(void* arg_0, NCSTRING event_base, NI32 event_id_0, void* event_data);
N_LIB_PRIVATE N_NIMCALL(void, doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q)(NI32 ret);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA*, newEspError__fwmtFMit0hAS9aJp9a7jOT1A)(NimStringV2 msg, NI32 error);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_CDECL(void, ipReceivedHandler__kSBHaIcYkybBtM9aE24vSlA_2)(void* arg_0, NCSTRING event_base, NI32 event_id_0, void* event_data);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___Ai9a6F9b9aMiawDJZ2TeoENGQ)(ip4_addr_t x);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA, toIpAddress__vKwhMp00EN2WY60Wl5KhKw)(ip4_addr_t ip_0);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___cbhSLBlQm0h9cO9cfQ8lXDaw)(tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA address);
N_LIB_PRIVATE N_NIMCALL(void, setFromString__ubRii7LYgSM9apFvSWh9ckcA)(NU8* val, NI valLen_0, NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(void, wifiStop__9cjBuhsNjNjxOdp8g3aRJsA_2)(void);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__anLaQLUPdevdHSYyM9cXyWQ_2 = { 10 | NIM_STRLIT_FLAG, "register: " };
static const NimStringV2 TM__anLaQLUPdevdHSYyM9cXyWQ_3 = {10, (NimStrPayload*)&TM__anLaQLUPdevdHSYyM9cXyWQ_2};
static const NimStringV2 TM__anLaQLUPdevdHSYyM9cXyWQ_6 = {10, (NimStrPayload*)&TM__anLaQLUPdevdHSYyM9cXyWQ_2};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__anLaQLUPdevdHSYyM9cXyWQ_7 = { 12 | NIM_STRLIT_FLAG, "unregister: " };
static const NimStringV2 TM__anLaQLUPdevdHSYyM9cXyWQ_8 = {12, (NimStrPayload*)&TM__anLaQLUPdevdHSYyM9cXyWQ_7};
static const NimStringV2 TM__anLaQLUPdevdHSYyM9cXyWQ_9 = {12, (NimStrPayload*)&TM__anLaQLUPdevdHSYyM9cXyWQ_7};

/* section: NIM_merge_VARS */
extern void* networkConnectEventGroup__nmpo6Y9aPj9ceX9a5QPnFjH1Q;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA networkIpAddr__37g5rmL1egFynkJj9cvRUzQ;
extern NCSTRING networkConnectionName__WyuSNx19cWYWra9bxa5KG0vQ;

/* section: NIM_merge_PROCS */

#line 414 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 544 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;

#line 546 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 31 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
N_LIB_PRIVATE N_CDECL(void, onWifiDisconnect__kSBHaIcYkybBtM9aE24vSlA)(void* arg_0, NCSTRING event_base, NI32 event_id_0, void* event_data) {	NI32 T1_;NIM_BOOL* nimErr_;	nimfr_("onWifiDisconnect", "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");{nimErr_ = nimErrorFlag();
#line 35 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(35, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 35 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	ESP_LOGI("wifi", "Wi-Fi disconnected, trying to reconnect...");

#line 36 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(36, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 36 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"

#line 36 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	T1_ = (NI32)0;	T1_ = esp_wifi_connect();
#line 36 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 11 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size) {	void* T1_;
#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source_0, ((size_t) (size)));}

#line 2186 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size) {
#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"

#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimCopyMem(dest, source_0, size);
}

#line 94 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {{
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	{		void* T5_;		void* T6_;		NI TM__anLaQLUPdevdHSYyM9cXyWQ_4;		NI TM__anLaQLUPdevdHSYyM9cXyWQ_5;
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (!(((NI) 0) < src.len)) goto LA3_;

#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		T5_ = (void*)0;		T5_ = ((void*) ((&(*(*dest).p).data[(*dest).len])));		T6_ = (void*)0;		T6_ = ((void*) ((&(*src.p).data[((NI) 0)])));
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (nimAddInt(src.len, ((NI) 1), &TM__anLaQLUPdevdHSYyM9cXyWQ_4)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__anLaQLUPdevdHSYyM9cXyWQ_4)) < ((NI) 0) || ((NI)(TM__anLaQLUPdevdHSYyM9cXyWQ_4)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__anLaQLUPdevdHSYyM9cXyWQ_4), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(T5_, T6_, ((NI) ((NI)(TM__anLaQLUPdevdHSYyM9cXyWQ_4))));

#line 98 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (nimAddInt((*dest).len, src.len, &TM__anLaQLUPdevdHSYyM9cXyWQ_5)) { raiseOverflow(); goto BeforeRet_;};		(*dest).len = (NI)(TM__anLaQLUPdevdHSYyM9cXyWQ_5);	}
	LA3_: ;
	}BeforeRet_: ;
}

#line 90 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {	NCSTRING result;	result = (NCSTRING)0;
#line 91 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	{
#line 91 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (!(s.len == ((NI) 0))) goto LA3_;

#line 91 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		result = "";	}
	goto LA1_;
	LA3_: ;
	{
#line 92 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		result = ((NCSTRING) ((*s.p).data));	}
	LA1_: ;
	return result;}

#line 22 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 24 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 21 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
N_LIB_PRIVATE N_CDECL(void, ipReceivedHandler__kSBHaIcYkybBtM9aE24vSlA_2)(void* arg_0, NCSTRING event_base, NI32 event_id_0, void* event_data) {	NimStringV2 colontmpD_;	NimStringV2 colontmpD__2;	ip_event_got_ip_t* event;	tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA T1_;	NU32 T2_;NIM_BOOL* nimErr_;	nimfr_("ipReceivedHandler", "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");{nimErr_ = nimErrorFlag();	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
#line 23 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(23, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");	event = ((ip_event_got_ip_t*) (event_data));
#line 24 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(24, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 24 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"

#line 24 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	colontmpD_ = dollar___Ai9a6F9b9aMiawDJZ2TeoENGQ((*event).ip_info.ip);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 24 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	ESP_LOGI("wifi", "event.ip_info.ip: %s", nimToCStringConv(colontmpD_));

#line 26 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(26, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 26 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimZeroMem((void*)(&T1_), sizeof(tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA));	T1_ = toIpAddress__vKwhMp00EN2WY60Wl5KhKw((*event).ip_info.ip);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	networkIpAddr__37g5rmL1egFynkJj9cvRUzQ = T1_;
#line 28 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(28, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 28 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"

#line 28 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	colontmpD__2 = dollar___cbhSLBlQm0h9cO9cfQ8lXDaw(networkIpAddr__37g5rmL1egFynkJj9cvRUzQ);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 28 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	ESP_LOGW("wifi", "got event ip: %s", nimToCStringConv(colontmpD__2));

#line 29 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(29, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 29 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"

#line 29 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	T2_ = (NU32)0;	T2_ = xEventGroupSetBits(networkConnectEventGroup__nmpo6Y9aPj9ceX9a5QPnFjH1Q, ((NU32) 2));	(void)(T2_);

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}BeforeRet_: ;
	popFrame();}

#line 38 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
N_LIB_PRIVATE N_NIMCALL(void, wifiStart__9cjBuhsNjNjxOdp8g3aRJsA)(void) {	wifi_init_config_t wcfg;	NI32 T1_;	NCSTRING evt_baseX60gensym1_;	NI32 retX60gensym1_;	NCSTRING evt_baseX60gensym3_;	NI32 retX60gensym3_;	NI32 T22_;	wifi_config_t wifi_config;	NI32 T23_;	NI32 T24_;	NI32 T25_;	NI32 T26_;NIM_BOOL* nimErr_;	nimfr_("wifiStart", "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");{nimErr_ = nimErrorFlag();
#line 40 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(40, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 40 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	wcfg = wifi_init_config_default__v9aEoJTWI9a7H65c9cz2ZEqIw();	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 42 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(42, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 42 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"

#line 42 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	T1_ = (NI32)0;	T1_ = esp_wifi_init((&wcfg));	(void)(T1_);

#line 30 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
	nimln_(30, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");	evt_baseX60gensym1_ = WIFI_EVENT;
#line 38 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
	nimln_(38, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");
#line 39 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
	nimln_(39, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");	retX60gensym1_ = esp_event_handler_register(evt_baseX60gensym1_, ((int) 5), onWifiDisconnect__kSBHaIcYkybBtM9aE24vSlA, NIM_NIL);
#line 44 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(44, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");	{		NimStringV2 colontmpD_;		NimStringV2 colontmpD__2;		NimStringV2 T7_;		NCSTRING T8_;		tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA* T9_;
#line 45 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		nimln_(45, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");
#line 45 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		if (!!((retX60gensym1_ == ((NI32) 0)))) goto LA4_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		nimln_(46, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");
#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		T7_.len = 0; T7_.p = NIM_NIL;
#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		T8_ = (NCSTRING)0;		T8_ = esp_err_to_name(retX60gensym1_);		colontmpD_ = cstrToNimstr(T8_);		T7_ = rawNewString(colontmpD_.len + 10);appendString((&T7_), TM__anLaQLUPdevdHSYyM9cXyWQ_3);appendString((&T7_), colontmpD_);		colontmpD__2 = T7_;
#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		T9_ = (tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA*)0;		T9_ = newEspError__fwmtFMit0hAS9aJp9a7jOT1A(colontmpD__2, retX60gensym1_);		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		raiseExceptionEx((Exception*)T9_, "EventError", "wifiStart", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m", 46);		goto LA6_;		{			LA6_:;		}
		{
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA4_: ;

#line 30 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
	nimln_(30, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");	evt_baseX60gensym3_ = IP_EVENT;
#line 38 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
	nimln_(38, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");
#line 39 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
	nimln_(39, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");	retX60gensym3_ = esp_event_handler_register(evt_baseX60gensym3_, ((int) 0), ipReceivedHandler__kSBHaIcYkybBtM9aE24vSlA_2, NIM_NIL);
#line 45 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(45, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");	{		NimStringV2 colontmpD__3;		NimStringV2 colontmpD__4;		NimStringV2 T17_;		NCSTRING T18_;		tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA* T19_;
#line 45 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		nimln_(45, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");
#line 45 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		if (!!((retX60gensym3_ == ((NI32) 0)))) goto LA14_;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;		colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		nimln_(46, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");
#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		T17_.len = 0; T17_.p = NIM_NIL;
#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		T18_ = (NCSTRING)0;		T18_ = esp_err_to_name(retX60gensym3_);		colontmpD__3 = cstrToNimstr(T18_);		T17_ = rawNewString(colontmpD__3.len + 10);appendString((&T17_), TM__anLaQLUPdevdHSYyM9cXyWQ_6);appendString((&T17_), colontmpD__3);		colontmpD__4 = T17_;
#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		T19_ = (tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA*)0;		T19_ = newEspError__fwmtFMit0hAS9aJp9a7jOT1A(colontmpD__4, retX60gensym3_);		if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
#line 46 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		raiseExceptionEx((Exception*)T19_, "EventError", "wifiStart", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m", 46);		goto LA16_;		{			LA16_:;		}
		{
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__4));

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__3));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA14_: ;

#line 47 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(47, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 47 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"

#line 47 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	T22_ = (NI32)0;	T22_ = esp_wifi_set_storage(((tyEnum_wifi_storage_t__V9bp3oj47VwwWqMieAivHAQ) 1));
#line 47 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q(T22_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	nimZeroMem((void*)(&wifi_config), sizeof(wifi_config_t));
#line 50 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(50, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 50 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	setFromString__ubRii7LYgSM9apFvSWh9ckcA(wifi_config.sta.ssid, 32, "CenturyLink6529-5G");
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 51 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(51, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 51 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	setFromString__ubRii7LYgSM9apFvSWh9ckcA(wifi_config.sta.password, 64, "n5ynzs6vt6td9p");
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 53 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(53, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 53 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	ESP_LOGI("wifi", "Connecting to %s...", wifi_config.sta.ssid);

#line 54 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(54, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 54 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"

#line 54 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	T23_ = (NI32)0;	T23_ = esp_wifi_set_mode(((tyEnum_wifi_mode_t__S2nRJJAgwwJiIUP8qNxDsw) 1));
#line 54 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q(T23_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 55 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(55, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 55 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"

#line 55 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	T24_ = (NI32)0;	T24_ = esp_wifi_set_config(((tyEnum_esp_interface_t__RI0zKHj8l73pvqKZi9blurQ) 0), (&wifi_config));
#line 55 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q(T24_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 56 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(56, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 56 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"

#line 56 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	T25_ = (NI32)0;	T25_ = esp_wifi_start();
#line 56 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q(T25_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 57 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(57, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 57 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"

#line 57 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	T26_ = (NI32)0;	T26_ = esp_wifi_connect();
#line 57 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q(T26_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 59 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(59, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");	networkConnectionName__WyuSNx19cWYWra9bxa5KG0vQ = "CenturyLink6529-5G";	}BeforeRet_: ;
	popFrame();}

#line 69 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
N_LIB_PRIVATE N_NIMCALL(NI32, networkingConnect__QPWTXSkQRoYwvMaeCcHCeg)(void) {	NI32 result;NIM_BOOL* nimErr_;	nimfr_("networkingConnect", "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");{nimErr_ = nimErrorFlag();	result = (NI32)0;
#line 70 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(70, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");	{
#line 70 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"

#line 70 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
		if (!!((networkConnectEventGroup__nmpo6Y9aPj9ceX9a5QPnFjH1Q == NIM_NIL))) goto LA3_;

#line 71 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
		nimln_(71, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 71 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
		result = ((NI32) 259);		goto BeforeRet_;
	}
	LA3_: ;

#line 73 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(73, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 73 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	networkConnectEventGroup__nmpo6Y9aPj9ceX9a5QPnFjH1Q = xEventGroupCreate();
#line 75 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(75, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 75 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	wifiStart__9cjBuhsNjNjxOdp8g3aRJsA();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 61 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
N_LIB_PRIVATE N_NIMCALL(void, wifiStop__9cjBuhsNjNjxOdp8g3aRJsA_2)(void) {	NCSTRING evt_baseX60gensym10_;	NI32 retX60gensym10_;	NCSTRING evt_baseX60gensym12_;	NI32 retX60gensym12_;	NI32 T21_;	NI32 T22_;NIM_BOOL* nimErr_;	nimfr_("wifiStop", "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");{nimErr_ = nimErrorFlag();
#line 116 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
	nimln_(116, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");	evt_baseX60gensym10_ = WIFI_EVENT;
#line 124 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
	nimln_(124, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");
#line 124 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
	retX60gensym10_ = esp_event_handler_unregister(evt_baseX60gensym10_, ((int) 5), onWifiDisconnect__kSBHaIcYkybBtM9aE24vSlA);
#line 63 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(63, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");	{		NimStringV2 colontmpD_;		NimStringV2 colontmpD__2;		NimStringV2 T6_;		NCSTRING T7_;		tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA* T8_;
#line 129 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		nimln_(129, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");
#line 129 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		if (!!((retX60gensym10_ == ((NI32) 0)))) goto LA3_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		nimln_(130, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");
#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		T6_.len = 0; T6_.p = NIM_NIL;
#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		T7_ = (NCSTRING)0;		T7_ = esp_err_to_name(retX60gensym10_);		colontmpD_ = cstrToNimstr(T7_);		T6_ = rawNewString(colontmpD_.len + 12);appendString((&T6_), TM__anLaQLUPdevdHSYyM9cXyWQ_8);appendString((&T6_), colontmpD_);		colontmpD__2 = T6_;
#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		T8_ = (tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA*)0;		T8_ = newEspError__fwmtFMit0hAS9aJp9a7jOT1A(colontmpD__2, retX60gensym10_);		if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		raiseExceptionEx((Exception*)T8_, "EventError", "wifiStop", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m", 130);		goto LA5_;		{			LA5_:;		}
		{
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;

#line 116 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
	nimln_(116, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");	evt_baseX60gensym12_ = IP_EVENT;
#line 124 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
	nimln_(124, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");
#line 124 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
	retX60gensym12_ = esp_event_handler_unregister(evt_baseX60gensym12_, ((int) 0), ipReceivedHandler__kSBHaIcYkybBtM9aE24vSlA_2);
#line 64 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(64, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");	{		NimStringV2 colontmpD__3;		NimStringV2 colontmpD__4;		NimStringV2 T16_;		NCSTRING T17_;		tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA* T18_;
#line 129 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		nimln_(129, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");
#line 129 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		if (!!((retX60gensym12_ == ((NI32) 0)))) goto LA13_;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;		colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		nimln_(130, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m");
#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		T16_.len = 0; T16_.p = NIM_NIL;
#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"

#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		T17_ = (NCSTRING)0;		T17_ = esp_err_to_name(retX60gensym12_);		colontmpD__3 = cstrToNimstr(T17_);		T16_ = rawNewString(colontmpD__3.len + 12);appendString((&T16_), TM__anLaQLUPdevdHSYyM9cXyWQ_9);appendString((&T16_), colontmpD__3);		colontmpD__4 = T16_;
#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		T18_ = (tyObject_EventError__jXXu17dImgF2rcF9bHHAzrA*)0;		T18_ = newEspError__fwmtFMit0hAS9aJp9a7jOT1A(colontmpD__4, retX60gensym12_);		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
#line 130 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.nim"
		raiseExceptionEx((Exception*)T18_, "EventError", "wifiStop", "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/events.ni"
"m", 130);		goto LA15_;		{			LA15_:;		}
		{
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__4));

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__3));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA13_: ;

#line 66 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(66, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 66 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"

#line 66 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	T21_ = (NI32)0;	T21_ = esp_wifi_stop();
#line 66 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q(T21_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 67 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(67, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 67 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"

#line 67 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	T22_ = (NI32)0;	T22_ = esp_wifi_deinit();
#line 67 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	doCheck__NdjoXjIhd8Q1zCYjQ5ZY0Q(T22_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 82 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
N_LIB_PRIVATE N_NIMCALL(NI32, networkingDisconnect__QPWTXSkQRoYwvMaeCcHCeg_2)(void) {	NI32 result;NIM_BOOL* nimErr_;	nimfr_("networkingDisconnect", "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");{nimErr_ = nimErrorFlag();	result = (NI32)0;
#line 83 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(83, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");	{
#line 83 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
		if (!(networkConnectEventGroup__nmpo6Y9aPj9ceX9a5QPnFjH1Q == NIM_NIL)) goto LA3_;

#line 84 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
		nimln_(84, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 84 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
		result = ((NI32) 259);		goto BeforeRet_;
	}
	LA3_: ;

#line 86 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(86, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 86 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	vEventGroupDelete(networkConnectEventGroup__nmpo6Y9aPj9ceX9a5QPnFjH1Q);

#line 87 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(87, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");	networkConnectEventGroup__nmpo6Y9aPj9ceX9a5QPnFjH1Q = NIM_NIL;
#line 88 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(88, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 88 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	wifiStop__9cjBuhsNjNjxOdp8g3aRJsA_2();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 89 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(89, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 89 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	ESP_LOGI("wifi", "Disconnected from %s", networkConnectionName__WyuSNx19cWYWra9bxa5KG0vQ);

#line 90 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(90, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");	networkConnectionName__WyuSNx19cWYWra9bxa5KG0vQ = ((NCSTRING) NIM_NIL);
#line 92 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	nimln_(92, "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/mai"
"n/setup_wifi.nim");
#line 92 "/home/elcritch/projects/bessel/mcus/esp32_ads115_playground/main/setup_wifi.nim"
	result = ((NI32) 0);	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}
