/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <sys/socket.h>
#include <errno.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA;

/* section: NIM_merge_TYPES */
typedef NU8 tyEnum_SOBool__SDlZUtKctfhvUZ58547HWQ;
typedef NU8 tySet_tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg;
typedef NU8 tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg;
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef NU8 tyEnum_IpAddressFamily__iqqacz9cr9bcNjYY74E10wPA;
typedef NU8 tyArray__qtqsWM5aXmcpMIVmvq3kAA[16];
typedef NU8 tyArray__H8qf9bpC2ziYA2earmO8m7w[4];
struct tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA {tyEnum_IpAddressFamily__iqqacz9cr9bcNjYY74E10wPA family;
union{
struct {tyArray__qtqsWM5aXmcpMIVmvq3kAA address_v6;
} _family_1;
struct {tyArray__H8qf9bpC2ziYA2earmO8m7w address_v4;
} _family_2;
};
};

/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___M2d4UEGH9cZOvte6rEhvUTQ)(NU64 x);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError)(NimStringV2 f);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__XqsrSBxhOTPgLQ9cX4MmV4A_3 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__XqsrSBxhOTPgLQ9cX4MmV4A_4 = {0, (NimStrPayload*)&TM__XqsrSBxhOTPgLQ9cX4MmV4A_3};
static const struct {
  NI cap; NIM_CHAR data[78+1];
} TM__XqsrSBxhOTPgLQ9cX4MmV4A_7 = { 78 | NIM_STRLIT_FLAG, "\'address_v4\' is not accessible using discriminant \'family\' of t"
"ype \'IpAddress\'" };
static const NimStringV2 TM__XqsrSBxhOTPgLQ9cX4MmV4A_8 = {78, (NimStrPayload*)&TM__XqsrSBxhOTPgLQ9cX4MmV4A_7};
static const struct {
  NI cap; NIM_CHAR data[78+1];
} TM__XqsrSBxhOTPgLQ9cX4MmV4A_12 = { 78 | NIM_STRLIT_FLAG, "\'address_v6\' is not accessible using discriminant \'family\' of t"
"ype \'IpAddress\'" };
static const NimStringV2 TM__XqsrSBxhOTPgLQ9cX4MmV4A_13 = {78, (NimStrPayload*)&TM__XqsrSBxhOTPgLQ9cX4MmV4A_12};
static const NimStringV2 TM__XqsrSBxhOTPgLQ9cX4MmV4A_15 = {78, (NimStrPayload*)&TM__XqsrSBxhOTPgLQ9cX4MmV4A_12};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__XqsrSBxhOTPgLQ9cX4MmV4A_20 = { 2 | NIM_STRLIT_FLAG, "::" };
static const NimStringV2 TM__XqsrSBxhOTPgLQ9cX4MmV4A_21 = {2, (NimStrPayload*)&TM__XqsrSBxhOTPgLQ9cX4MmV4A_20};
static const NimStringV2 TM__XqsrSBxhOTPgLQ9cX4MmV4A_22 = {78, (NimStrPayload*)&TM__XqsrSBxhOTPgLQ9cX4MmV4A_12};
static const NimStringV2 TM__XqsrSBxhOTPgLQ9cX4MmV4A_24 = {78, (NimStrPayload*)&TM__XqsrSBxhOTPgLQ9cX4MmV4A_12};
static const NimStringV2 TM__XqsrSBxhOTPgLQ9cX4MmV4A_28 = {2, (NimStrPayload*)&TM__XqsrSBxhOTPgLQ9cX4MmV4A_20};

/* section: NIM_merge_VARS */
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 544 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;

#line 546 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 1197 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
N_LIB_PRIVATE N_NIMCALL(int, toCInt__jdGcpZaHg8FvJJ7dgE9b75w)(tyEnum_SOBool__SDlZUtKctfhvUZ58547HWQ opt) {	int result;	int colontmpD_;	int colontmpD__2;	int colontmpD__3;	int colontmpD__4;	int colontmpD__5;	int colontmpD__6;	int colontmpD__7;	int colontmpD__8;	int colontmpD__9;	nimfr_("toCInt", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");	result = (int)0;	colontmpD_ = (int)0;	colontmpD__2 = (int)0;	colontmpD__3 = (int)0;	colontmpD__4 = (int)0;	colontmpD__5 = (int)0;	colontmpD__6 = (int)0;	colontmpD__7 = (int)0;	colontmpD__8 = (int)0;	colontmpD__9 = (int)0;
#line 1198 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
	nimln_(1198, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");
#line 1199 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
	nimln_(1199, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");	switch (opt) {
	case ((tyEnum_SOBool__SDlZUtKctfhvUZ58547HWQ) 0):
	{
#line 1200 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
		nimln_(1200, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");		colontmpD_ = SO_ACCEPTCONN;		result = colontmpD_;	}
	break;
	case ((tyEnum_SOBool__SDlZUtKctfhvUZ58547HWQ) 1):
	{
#line 1201 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
		nimln_(1201, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");		colontmpD__2 = SO_BROADCAST;		result = colontmpD__2;	}
	break;
	case ((tyEnum_SOBool__SDlZUtKctfhvUZ58547HWQ) 2):
	{
#line 1202 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
		nimln_(1202, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");		colontmpD__3 = SO_DEBUG;		result = colontmpD__3;	}
	break;
	case ((tyEnum_SOBool__SDlZUtKctfhvUZ58547HWQ) 3):
	{
#line 1203 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
		nimln_(1203, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");		colontmpD__4 = SO_DONTROUTE;		result = colontmpD__4;	}
	break;
	case ((tyEnum_SOBool__SDlZUtKctfhvUZ58547HWQ) 4):
	{
#line 1204 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
		nimln_(1204, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");		colontmpD__5 = SO_KEEPALIVE;		result = colontmpD__5;	}
	break;
	case ((tyEnum_SOBool__SDlZUtKctfhvUZ58547HWQ) 5):
	{
#line 1205 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
		nimln_(1205, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");		colontmpD__6 = SO_OOBINLINE;		result = colontmpD__6;	}
	break;
	case ((tyEnum_SOBool__SDlZUtKctfhvUZ58547HWQ) 6):
	{
#line 1206 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
		nimln_(1206, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");		colontmpD__7 = SO_REUSEADDR;		result = colontmpD__7;	}
	break;
	case ((tyEnum_SOBool__SDlZUtKctfhvUZ58547HWQ) 7):
	{
#line 1207 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
		nimln_(1207, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");		colontmpD__8 = SO_REUSEPORT;		result = colontmpD__8;	}
	break;
	case ((tyEnum_SOBool__SDlZUtKctfhvUZ58547HWQ) 8):
	{
#line 1208 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
		nimln_(1208, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");		colontmpD__9 = ((int) 1);		result = colontmpD__9;	}
	break;
	}
	popFrame();	return result;}

#line 204 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isDisconnectionError__XxybNfLJKXhPAkMhmPhNzQ)(tySet_tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg flags_0, NI32 lastError) {	NIM_BOOL result;	NIM_BOOL T1_;	NIM_BOOL T3_;	NIM_BOOL T4_;	nimfr_("isDisconnectionError", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");	result = (NIM_BOOL)0;
#line 206 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
	nimln_(206, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");
#line 217 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
	nimln_(217, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");	T1_ = (NIM_BOOL)0;
#line 217 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
	T1_ = ((flags_0 &((NU8)1<<((NU)(((tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg) 1))&7U)))!=0);	if (!(T1_)) goto LA2_;

#line 219 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
	nimln_(219, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");	T3_ = (NIM_BOOL)0;
#line 218 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
	nimln_(218, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");	T4_ = (NIM_BOOL)0;
#line 218 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
	T4_ = (lastError == ECONNRESET);	if (T4_) goto LA5_;

#line 219 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
	nimln_(219, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");	T4_ = (lastError == EPIPE);	LA5_: ;
	T3_ = T4_;	if (T3_) goto LA6_;

#line 220 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
	nimln_(220, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");	T3_ = (lastError == ENETRESET);	LA6_: ;
	T1_ = T3_;	LA2_: ;
	result = T1_;	popFrame();	return result;}

#line 222 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
N_LIB_PRIVATE N_NIMCALL(int, toOSFlags__o0FbRanOjUQrx1x33AiBQA)(tySet_tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg socketFlags) {	int result;	nimfr_("toOSFlags", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");{	result = (int)0;	{		tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg f;		NI i;		f = (tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg)0;
#line 52 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
		nimln_(52, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.ni"
"m");		i = ((NI) 0);		{
#line 53 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
			nimln_(53, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.ni"
"m");			while (1) {				NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_2;
#line 53 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
				if (!(i <= ((NI) 1))) goto LA3;

#line 54 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
				nimln_(54, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.ni"
"m");				{
#line 54 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
					if ((i) < ((tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg) 0) || (i) > ((tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg) 1)){ raiseRangeErrorI(i, ((tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg) 0), ((tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg) 1)); goto BeforeRet_;}					if (!((socketFlags &((NU8)1<<((NU)(((tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg) (i)))&7U)))!=0)) goto LA6_;

#line 224 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
					nimln_(224, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");					if ((i) < ((tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg) 0) || (i) > ((tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg) 1)){ raiseRangeErrorI(i, ((tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg) 0), ((tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg) 1)); goto BeforeRet_;}					f = ((tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg) (i));					{
#line 225 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
						nimln_(225, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");						switch (f) {
						case ((tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg) 0):
						{
#line 227 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(227, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");
#line 227 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							result = (NI32)(result | ((NI32) 1));						}
						break;
						case ((tyEnum_SocketFlag__4xio0cAXR7XG4pF9bVcpxEg) 1):
						{
#line 228 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(228, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");							goto LA8;
						}
						break;
						}
					} LA8: ;
				}
				LA6_: ;

#line 55 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
				nimln_(55, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.ni"
"m");				if (nimAddInt(i, ((NI) 1), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_2)) { raiseOverflow(); goto BeforeRet_;};				i = (NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_2);			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();	return result;}

#line 65 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c) {	NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_5;	NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_6;{
#line 67 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"

#line 67 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	prepareAdd(s, ((NI) 1));

#line 68 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	(*(*s).p).data[(*s).len] = c;
#line 69 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	if (nimAddInt((*s).len, ((NI) 1), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_5)) { raiseOverflow(); goto BeforeRet_;};
#line 69 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	(*(*s).p).data[(NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_5)] = 0;
#line 70 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	if (nimAddInt((*s).len, ((NI) 1), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_6)) { raiseOverflow(); goto BeforeRet_;};	(*s).len = (NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_6);	}BeforeRet_: ;
}

#line 11 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size) {	void* T1_;
#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source_0, ((size_t) (size)));}

#line 2186 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size) {
#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"

#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimCopyMem(dest, source_0, size);
}

#line 94 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {{
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	{		void* T5_;		void* T6_;		NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_9;		NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_10;
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (!(((NI) 0) < src.len)) goto LA3_;

#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		T5_ = (void*)0;		T5_ = ((void*) ((&(*(*dest).p).data[(*dest).len])));		T6_ = (void*)0;		T6_ = ((void*) ((&(*src.p).data[((NI) 0)])));
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (nimAddInt(src.len, ((NI) 1), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_9)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_9)) < ((NI) 0) || ((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_9)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_9), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(T5_, T6_, ((NI) ((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_9))));

#line 98 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (nimAddInt((*dest).len, src.len, &TM__XqsrSBxhOTPgLQ9cX4MmV4A_10)) { raiseOverflow(); goto BeforeRet_;};		(*dest).len = (NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_10);	}
	LA3_: ;
	}BeforeRet_: ;
}

#line 414 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 1786 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___cbhSLBlQm0h9cO9cfQ8lXDaw)(tyObject_IpAddress__t0yd6ha54oWXm7nwZ4QqfA address) {	NimStringV2 result;NIM_BOOL* nimErr_;	nimfr_("$", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;
#line 1788 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
	nimln_(1788, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");	result = TM__XqsrSBxhOTPgLQ9cX4MmV4A_4;
#line 1789 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
	nimln_(1789, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");	switch (address.family) {
	case ((tyEnum_IpAddressFamily__iqqacz9cr9bcNjYY74E10wPA) 1):
	{		{			NI i;			NI res;			i = (NI)0;
#line 77 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
			nimln_(77, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");			res = ((NI) 0);			{
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
				nimln_(78, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");				while (1) {					NimStringV2 colontmpD_;					NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_11;
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
					if (!(res <= ((NI) 3))) goto LA4;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
#line 1791 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
					nimln_(1791, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");					i = res;
#line 1792 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
					nimln_(1792, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");					{
#line 1792 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"

#line 1792 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
						if (!!((i == ((NI) 0)))) goto LA7_;

#line 1793 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
						nimln_(1793, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");						nimAddCharV1((&result), 46);					}
					LA7_: ;

#line 1794 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
					nimln_(1794, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");
#line 1794 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
					if (!(((2 &((NU8)1<<((NU)(address.family)&7U)))!=0))){ raiseFieldError(TM__XqsrSBxhOTPgLQ9cX4MmV4A_8); goto BeforeRet_;}					if ((NU)(i) > (NU)(3)){ raiseIndexError2(i, 3); goto BeforeRet_;}
#line 1794 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
					colontmpD_ = dollar___M2d4UEGH9cZOvte6rEhvUTQ(((NU64) (address._family_2.address_v4[(i)- 0])));					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;					prepareAdd((&result), colontmpD_.len + 0);appendString((&result), colontmpD_);
#line 80 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
					nimln_(80, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");					if (nimAddInt(res, ((NI) 1), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_11)) { raiseOverflow(); goto BeforeRet_;};					res = (NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_11);
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
					nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
					eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
				} LA4: ;
			}
		}
	}
	break;
	case ((tyEnum_IpAddressFamily__iqqacz9cr9bcNjYY74E10wPA) 0):
	{		NI currentZeroStart;		NI currentZeroCount;		NI biggestZeroStart;		NI biggestZeroCount;
#line 1797 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
		nimln_(1797, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");		currentZeroStart = ((NI) -1);
#line 1798 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
		nimln_(1798, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");		currentZeroCount = ((NI) 0);
#line 1799 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
		nimln_(1799, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");		biggestZeroStart = ((NI) -1);
#line 1800 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
		nimln_(1800, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");		biggestZeroCount = ((NI) 0);		{			NI i_2;			NI res_2;			i_2 = (NI)0;
#line 77 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
			nimln_(77, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");			res_2 = ((NI) 0);			{
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
				nimln_(78, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");				while (1) {					NIM_BOOL isZero;					NIM_BOOL T13_;					NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_14;					NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_16;					NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_17;					NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_19;
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
					if (!(res_2 <= ((NI) 7))) goto LA12;

#line 1802 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
					nimln_(1802, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");					i_2 = res_2;
#line 1803 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
					nimln_(1803, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");
#line 1803 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
					T13_ = (NIM_BOOL)0;
#line 1803 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
					if (!(((1 &((NU8)1<<((NU)(address.family)&7U)))!=0))){ raiseFieldError(TM__XqsrSBxhOTPgLQ9cX4MmV4A_13); goto BeforeRet_;}
#line 1803 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
					if (nimMulInt(i_2, ((NI) 2), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_14)) { raiseOverflow(); goto BeforeRet_;};					if ((NU)((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_14)) > (NU)(15)){ raiseIndexError2((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_14), 15); goto BeforeRet_;}					T13_ = (address._family_1.address_v6[((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_14))- 0] == ((NU8) 0));					if (!(T13_)) goto LA14_;

#line 1803 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
					if (!(((1 &((NU8)1<<((NU)(address.family)&7U)))!=0))){ raiseFieldError(TM__XqsrSBxhOTPgLQ9cX4MmV4A_15); goto BeforeRet_;}
#line 1803 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"

#line 1803 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
					if (nimMulInt(i_2, ((NI) 2), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_16)) { raiseOverflow(); goto BeforeRet_;};					if (nimAddInt((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_16), ((NI) 1), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_17)) { raiseOverflow(); goto BeforeRet_;};					if ((NU)((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_17)) > (NU)(15)){ raiseIndexError2((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_17), 15); goto BeforeRet_;}					T13_ = (address._family_1.address_v6[((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_17))- 0] == ((NU8) 0));					LA14_: ;
					isZero = T13_;
#line 1804 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
					nimln_(1804, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");					{						if (!isZero) goto LA17_;

#line 1805 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
						nimln_(1805, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");						{
#line 1805 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							if (!(currentZeroStart == ((NI) -1))) goto LA21_;

#line 1806 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(1806, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");							currentZeroStart = i_2;
#line 1807 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(1807, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");							currentZeroCount = ((NI) 1);						}
						goto LA19_;
						LA21_: ;
						{							NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_18;
#line 1809 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(1809, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");							if (nimAddInt(currentZeroCount, ((NI) 1), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_18)) { raiseOverflow(); goto BeforeRet_;};							currentZeroCount = (NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_18);						}
						LA19_: ;

#line 1810 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
						nimln_(1810, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");						{
#line 1810 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							if (!(biggestZeroCount < currentZeroCount)) goto LA26_;

#line 1811 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(1811, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");							biggestZeroCount = currentZeroCount;
#line 1812 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(1812, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");							biggestZeroStart = currentZeroStart;						}
						LA26_: ;
					}
					goto LA15_;
					LA17_: ;
					{
#line 1814 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
						nimln_(1814, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");						currentZeroStart = ((NI) -1);					}
					LA15_: ;

#line 80 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
					nimln_(80, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");					if (nimAddInt(res_2, ((NI) 1), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_19)) { raiseOverflow(); goto BeforeRet_;};					res_2 = (NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_19);				} LA12: ;
			}
		}

#line 1816 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
		nimln_(1816, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");		{
#line 1816 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
			if (!(biggestZeroCount == ((NI) 8))) goto LA31_;

#line 1817 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
			nimln_(1817, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");			prepareAdd((&result), 2);appendString((&result), TM__XqsrSBxhOTPgLQ9cX4MmV4A_21);		}
		goto LA29_;
		LA31_: ;
		{			NIM_BOOL printedLastGroup;
#line 1819 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
			nimln_(1819, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");			printedLastGroup = NIM_FALSE;			{				NI i_3;				NI res_3;				i_3 = (NI)0;
#line 77 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
				nimln_(77, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");				res_3 = ((NI) 0);				{
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
					nimln_(78, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");					while (1) {						NU16 word;						NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_23;						NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_25;						NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_26;						NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_30;
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
						if (!(res_3 <= ((NI) 7))) goto LA36;

#line 1820 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
						nimln_(1820, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");						i_3 = res_3;
#line 1821 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
						nimln_(1821, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");
#line 1821 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
						if (!(((1 &((NU8)1<<((NU)(address.family)&7U)))!=0))){ raiseFieldError(TM__XqsrSBxhOTPgLQ9cX4MmV4A_22); goto BeforeRet_;}
#line 1821 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
						if (nimMulInt(i_3, ((NI) 2), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_23)) { raiseOverflow(); goto BeforeRet_;};						if ((NU)((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_23)) > (NU)(15)){ raiseIndexError2((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_23), 15); goto BeforeRet_;}						word = (NU16)((NU32)(((NU16) (address._family_1.address_v6[((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_23))- 0]))) << (NU32)(((NI) 8)));
#line 1822 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
						nimln_(1822, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");
#line 1822 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
						if (!(((1 &((NU8)1<<((NU)(address.family)&7U)))!=0))){ raiseFieldError(TM__XqsrSBxhOTPgLQ9cX4MmV4A_24); goto BeforeRet_;}
#line 1822 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"

#line 1822 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
						if (nimMulInt(i_3, ((NI) 2), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_25)) { raiseOverflow(); goto BeforeRet_;};						if (nimAddInt((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_25), ((NI) 1), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_26)) { raiseOverflow(); goto BeforeRet_;};						if ((NU)((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_26)) > (NU)(15)){ raiseIndexError2((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_26), 15); goto BeforeRet_;}						word = (NU16)(word | ((NU16) (address._family_1.address_v6[((NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_26))- 0])));
#line 1824 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
						nimln_(1824, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");						{							NIM_BOOL T39_;							NIM_BOOL T41_;							NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_27;
#line 1824 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							T39_ = (NIM_BOOL)0;
#line 1824 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"

#line 1824 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							T39_ = !((biggestZeroCount == ((NI) 0)));							if (!(T39_)) goto LA40_;

#line 1825 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(1825, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");							T41_ = (NIM_BOOL)0;
#line 1825 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							T41_ = (biggestZeroStart <= i_3);							if (!(T41_)) goto LA42_;

#line 1825 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"

#line 1825 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							if (nimAddInt(biggestZeroStart, biggestZeroCount, &TM__XqsrSBxhOTPgLQ9cX4MmV4A_27)) { raiseOverflow(); goto BeforeRet_;};							T41_ = (i_3 < (NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_27));							LA42_: ;
							T39_ = T41_;							LA40_: ;
							if (!T39_) goto LA43_;

#line 1826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(1826, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");							{
#line 1826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
								if (!(i_3 == biggestZeroStart)) goto LA47_;

#line 1827 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
								nimln_(1827, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");								prepareAdd((&result), 2);appendString((&result), TM__XqsrSBxhOTPgLQ9cX4MmV4A_28);							}
							LA47_: ;

#line 1828 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(1828, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");							printedLastGroup = NIM_FALSE;						}
						goto LA37_;
						LA43_: ;
						{							NIM_BOOL afterLeadingZeros;							NU16 mask;
#line 1830 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(1830, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");							{								if (!printedLastGroup) goto LA52_;

#line 1831 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
								nimln_(1831, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");								nimAddCharV1((&result), 58);							}
							LA52_: ;

#line 1833 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(1833, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");							afterLeadingZeros = NIM_FALSE;
#line 1834 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(1834, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");							mask = ((NU16) 61440);							{								NU16 j;								NI res_4;								j = (NU16)0;
#line 77 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
								nimln_(77, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");								res_4 = ((NI) 0);								{
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
									nimln_(78, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");									while (1) {										NU16 val;										NI TM__XqsrSBxhOTPgLQ9cX4MmV4A_29;
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
										if (!(res_4 <= ((NI) 3))) goto LA56;

#line 1835 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
										nimln_(1835, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");										j = ((NU16) (res_4));
#line 1836 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
										nimln_(1836, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");
#line 1836 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"

#line 1836 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"

#line 1836 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"

#line 1836 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
										val = (NU16)((NU16)((NU16)(mask & word)) >> (NU16)((NU16)((NU16)(((NU16) 4)) * (NU16)((NU16)((NU16)(((NU16) 3)) - (NU16)(j))))));
#line 1837 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
										nimln_(1837, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");										{											NIM_BOOL T59_;
#line 1837 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
											T59_ = (NIM_BOOL)0;
#line 1837 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"

#line 1837 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
											T59_ = !((val == ((NU16) 0)));											if (T59_) goto LA60_;
											T59_ = afterLeadingZeros;											LA60_: ;
											if (!T59_) goto LA61_;

#line 1838 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
											nimln_(1838, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");											{
#line 1838 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
												if (!((NU16)(val) < (NU16)(((NU16) 10)))) goto LA65_;

#line 1839 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
												nimln_(1839, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");
#line 1839 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"

#line 1839 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
												if (((NU16)((NU16)(((NU16) 48)) + (NU16)(val))) < ((NI) 0) || ((NU16)((NU16)(((NU16) 48)) + (NU16)(val))) > ((NI) 255)){ raiseRangeErrorI((NU16)((NU16)(((NU16) 48)) + (NU16)(val)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}												nimAddCharV1((&result), ((NIM_CHAR) (((NI) ((NU16)((NU16)(((NU16) 48)) + (NU16)(val)))))));											}
											goto LA63_;
											LA65_: ;
											{
#line 1841 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
												nimln_(1841, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");
#line 1841 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"

#line 1841 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"

#line 1841 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
												if (((NU16)((NU16)((NU16)((NU16)(((NU16) 97)) + (NU16)(val))) - (NU16)(((NU16) 10)))) < ((NI) 0) || ((NU16)((NU16)((NU16)((NU16)(((NU16) 97)) + (NU16)(val))) - (NU16)(((NU16) 10)))) > ((NI) 255)){ raiseRangeErrorI((NU16)((NU16)((NU16)((NU16)(((NU16) 97)) + (NU16)(val))) - (NU16)(((NU16) 10))), ((NI) 0), ((NI) 255)); goto BeforeRet_;}												nimAddCharV1((&result), ((NIM_CHAR) (((NI) ((NU16)((NU16)((NU16)((NU16)(((NU16) 97)) + (NU16)(val))) - (NU16)(((NU16) 10))))))));											}
											LA63_: ;

#line 1842 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
											nimln_(1842, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");											afterLeadingZeros = NIM_TRUE;										}
										LA61_: ;

#line 1843 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
										nimln_(1843, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");
#line 1843 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
										mask = (NU16)((NU16)(mask) >> (NU32)(((NI) 4)));
#line 80 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
										nimln_(80, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");										if (nimAddInt(res_4, ((NI) 1), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_29)) { raiseOverflow(); goto BeforeRet_;};										res_4 = (NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_29);									} LA56: ;
								}
							}

#line 1845 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(1845, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");							{
#line 1845 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
								if (!!(afterLeadingZeros)) goto LA70_;

#line 1846 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
								nimln_(1846, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");								nimAddCharV1((&result), 48);							}
							LA70_: ;

#line 1848 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim"
							nimln_(1848, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/net.nim");							printedLastGroup = NIM_TRUE;						}
						LA37_: ;

#line 80 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
						nimln_(80, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");						if (nimAddInt(res_3, ((NI) 1), &TM__XqsrSBxhOTPgLQ9cX4MmV4A_30)) { raiseOverflow(); goto BeforeRet_;};						res_3 = (NI)(TM__XqsrSBxhOTPgLQ9cX4MmV4A_30);					} LA36: ;
				}
			}
		}
		LA29_: ;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();	return result;}
