/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#include "lwip/ip4_addr.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__bl0bSVWGY9awnrUbJL6olrQ)(tySequence__uB9b75OUPRENsBAu4AnoePA x, NimStringV2 prefix, NimStringV2 separator, NimStringV2 suffix);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__iwHTMWG9c27MDj69bdm9bZJBQ)(NimStringV2* s, tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__ARWLtdz6aJCA2LIYS9cFiGQ)(NimStringV2* s, NCSTRING x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__Eys2fLM61EBlquSM8n9cIsw)(NimStringV2* s, NI x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringV2 msg);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
N_NIMCALL(NimStringV2, mnewString)(NI len_0);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__C0YoABEefTaYbWLv9aVOzZA)(NimStringV2* s);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__DMSWtl26Af0OtoygyWiFow)(NimStringV2* s, NU32 x);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_4 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_5 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_4};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_6 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_7 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_6};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_8 = { 8 | NIM_STRLIT_FLAG, "procname" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_9 = {8, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_8};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_10 = { 2 | NIM_STRLIT_FLAG, ": " };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_11 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_10};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_12 = { 3 | NIM_STRLIT_FLAG, "nil" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_13 = {3, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_12};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_14 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_6};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_15 = { 4 | NIM_STRLIT_FLAG, "line" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_16 = {4, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_15};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_17 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_10};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_18 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_6};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_19 = { 8 | NIM_STRLIT_FLAG, "filename" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_20 = {8, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_19};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_21 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_10};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_22 = {3, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_12};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_23 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_24 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_23};
static const struct {
  NI cap; NIM_CHAR data[141+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_25 = { 141 | NIM_STRLIT_FLAG, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.ni"
"m(204, 11) `len(a) == L` the length of the seq changed while ite"
"rating over it" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_26 = {141, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_25};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_27 = { 2 | NIM_STRLIT_FLAG, "@[" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_28 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_27};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_29 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_6};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_30 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_31 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_30};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_32 = { 1 | NIM_STRLIT_FLAG, "0" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_33 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_32};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_34 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_4};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_35 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_6};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_36 = { 7 | NIM_STRLIT_FLAG, "address" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_37 = {7, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_36};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_38 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_10};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_39 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_23};

/* section: NIM_merge_VARS */
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 11 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size) {	void* T1_;
#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source_0, ((size_t) (size)));}

#line 2186 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size) {
#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"

#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimCopyMem(dest, source_0, size);
}

#line 94 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {{
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	{		void* T5_;		void* T6_;		NI TM__n49a9aYp5BrbXv9a6OCpJYm0g_2;		NI TM__n49a9aYp5BrbXv9a6OCpJYm0g_3;
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (!(((NI) 0) < src.len)) goto LA3_;

#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		T5_ = (void*)0;		T5_ = ((void*) ((&(*(*dest).p).data[(*dest).len])));		T6_ = (void*)0;		T6_ = ((void*) ((&(*src.p).data[((NI) 0)])));
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (nimAddInt(src.len, ((NI) 1), &TM__n49a9aYp5BrbXv9a6OCpJYm0g_2)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_2)) < ((NI) 0) || ((NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_2)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_2), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(T5_, T6_, ((NI) ((NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_2))));

#line 98 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (nimAddInt((*dest).len, src.len, &TM__n49a9aYp5BrbXv9a6OCpJYm0g_3)) { raiseOverflow(); goto BeforeRet_;};		(*dest).len = (NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_3);	}
	LA3_: ;
	}BeforeRet_: ;
}

#line 544 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;

#line 546 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 106 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___WrYXAVecSG9ckDg0dVMv4oQ)(tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA x) {	NimStringV2 result;	NI count_1;	nimfr_("$", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	result.len = 0; result.p = NIM_NIL;
#line 114 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(114, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_5;
#line 116 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(116, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	count_1 = ((NI) 0);
#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(118, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	{
#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		if (!(((NI) 0) < count_1)) goto LA3_;

#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		prepareAdd((&result), 2);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_7);	}
	LA3_: ;

#line 120 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(120, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	prepareAdd((&result), 8);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_9);
#line 121 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(121, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	prepareAdd((&result), 2);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_11);
#line 122 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(122, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	count_1 += ((NI) 1);
#line 125 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(125, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	{
#line 125 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		if (!(x.procname == 0)) goto LA7_;

#line 125 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		prepareAdd((&result), 3);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_13);	}
	goto LA5_;
	LA7_: ;
	{
#line 126 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		nimln_(126, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");
#line 126 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		addQuoted__ARWLtdz6aJCA2LIYS9cFiGQ((&result), x.procname);
	}
	LA5_: ;

#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(118, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	{
#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		if (!(((NI) 0) < count_1)) goto LA12_;

#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		prepareAdd((&result), 2);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_14);	}
	LA12_: ;

#line 120 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(120, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	prepareAdd((&result), 4);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_16);
#line 121 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(121, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	prepareAdd((&result), 2);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_17);
#line 122 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(122, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	count_1 += ((NI) 1);
#line 128 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(128, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");
#line 128 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	addQuoted__Eys2fLM61EBlquSM8n9cIsw((&result), x.line);

#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(118, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	{
#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		if (!(((NI) 0) < count_1)) goto LA16_;

#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		prepareAdd((&result), 2);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_18);	}
	LA16_: ;

#line 120 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(120, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	prepareAdd((&result), 8);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_20);
#line 121 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(121, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	prepareAdd((&result), 2);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_21);
#line 122 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(122, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	count_1 += ((NI) 1);
#line 125 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(125, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	{
#line 125 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		if (!(x.filename == 0)) goto LA20_;

#line 125 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		prepareAdd((&result), 3);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_22);	}
	goto LA18_;
	LA20_: ;
	{
#line 126 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		nimln_(126, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");
#line 126 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		addQuoted__ARWLtdz6aJCA2LIYS9cFiGQ((&result), x.filename);
	}
	LA18_: ;

#line 134 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(134, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	prepareAdd((&result), 1);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_24);	popFrame();	return result;}

#line 414 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 137 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__bl0bSVWGY9awnrUbJL6olrQ)(tySequence__uB9b75OUPRENsBAu4AnoePA x, NimStringV2 prefix, NimStringV2 separator, NimStringV2 suffix) {	NimStringV2 result;	NIM_BOOL firstElement;NIM_BOOL* nimErr_;	nimfr_("collectionToString", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
	eqcopy___aBBXmHFBEivKqERloP6zmA((&result), prefix);

#line 139 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(139, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	firstElement = NIM_TRUE;	{		tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA* value;		NI i;		NI L;		NI T2_;		value = (tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA*)0;
#line 199 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
		nimln_(199, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.ni"
"m");		i = ((NI) 0);
#line 200 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
		nimln_(200, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.ni"
"m");
#line 200 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
		T2_ = x.len;		L = T2_;		{
#line 201 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
			nimln_(201, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.ni"
"m");			while (1) {
#line 201 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
				if (!(i < L)) goto LA4;

#line 140 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
				nimln_(140, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");				value = (&x.p->data[i]);
#line 141 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
				nimln_(141, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");				{					if (!firstElement) goto LA7_;

#line 142 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
					nimln_(142, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");					firstElement = NIM_FALSE;				}
				goto LA5_;
				LA7_: ;
				{
#line 144 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
					nimln_(144, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");					prepareAdd((&result), separator.len + 0);appendString((&result), separator);				}
				LA5_: ;

#line 153 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
				nimln_(153, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");
#line 153 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
				addQuoted__iwHTMWG9c27MDj69bdm9bZJBQ((&result), (*value));

#line 203 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
				nimln_(203, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.ni"
"m");				i += ((NI) 1);
#line 204 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
				nimln_(204, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.ni"
"m");				{					NI T12_;
#line 204 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"

#line 204 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"

#line 204 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
					T12_ = x.len;					if (!!((T12_ == L))) goto LA13_;

#line 204 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"

#line 204 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
					failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__n49a9aYp5BrbXv9a6OCpJYm0g_26);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;				}
				LA13_: ;
			} LA4: ;
		}
	}

#line 154 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(154, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	prepareAdd((&result), suffix.len + 0);appendString((&result), suffix);	}BeforeRet_: ;
	popFrame();	return result;}

#line 164 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___7AQ19bV7URzlCmoau9c79cWbw)(tySequence__uB9b75OUPRENsBAu4AnoePA x) {	NimStringV2 result;NIM_BOOL* nimErr_;	nimfr_("$", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;
#line 170 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(170, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");
#line 170 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	result = collectionToString__bl0bSVWGY9awnrUbJL6olrQ(x, TM__n49a9aYp5BrbXv9a6OCpJYm0g_28, TM__n49a9aYp5BrbXv9a6OCpJYm0g_29, TM__n49a9aYp5BrbXv9a6OCpJYm0g_31);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s) {
#line 169 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	{		NIM_BOOL T3_;
#line 169 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		T3_ = (NIM_BOOL)0;
#line 169 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"

#line 169 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		T3_ = !(((*s).p == ((NimStrPayload*) NIM_NIL)));		if (!(T3_)) goto LA4_;

#line 169 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"

#line 169 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		T3_ = ((NI)((*(*s).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));		LA4_: ;
		if (!T3_) goto LA5_;

#line 170 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"

#line 170 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		nimPrepareStrMutationImpl__C0YoABEefTaYbWLv9aVOzZA(s);
	}
	LA5_: ;
}

#line 23 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___M2d4UEGH9cZOvte6rEhvUTQ)(NU64 x) {	NimStringV2 result;	nimfr_("$", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	result.len = 0; result.p = NIM_NIL;
#line 26 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(26, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	{
#line 26 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		if (!(x == 0ULL)) goto LA3_;

#line 27 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		nimln_(27, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");		result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_33;	}
	goto LA1_;
	LA3_: ;
	{		NimStringV2 T6_;		NI i;		NU64 n;		NI half;
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
		nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 29 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		nimln_(29, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");
#line 29 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		T6_.len = 0; T6_.p = NIM_NIL;		T6_ = mnewString(((NI) 60));
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
		nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");		eqsink___aBBXmHFBEivKqERloP6zmA_2((&result), T6_);

#line 30 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		nimln_(30, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");		i = ((NI) 0);
#line 31 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		nimln_(31, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");		n = x;		{
#line 32 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
			nimln_(32, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");			while (1) {				NU64 nn;
#line 32 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"

#line 32 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
				if (!!((n == 0ULL))) goto LA8;

#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
				nimln_(33, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");
#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
				nn = (NU64)((NU64)(n) / (NU64)(10ULL));				nimPrepareStrMutationV2((&result));
#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
				nimln_(34, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");
#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"

#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"

#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
				result.p->data[i] = ((NIM_CHAR) ((NU64)((NU64)((NU64)((NU64)(n) - (NU64)((NU64)((NU64)(10ULL) * (NU64)(nn))))) + (NU64)(48ULL))));
#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
				nimln_(35, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");				i += ((NI) 1);
#line 36 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
				nimln_(36, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");				n = nn;			} LA8: ;
		}

#line 37 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		nimln_(37, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");		setLengthStrV2((&result), ((NI) (i)));
#line 39 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		nimln_(39, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");
#line 39 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		half = (NI)(i / ((NI) 2));		{			NI t;			NI colontmp_;			NI res;			t = (NI)0;			colontmp_ = (NI)0;
#line 41 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
			nimln_(41, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");
#line 41 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
			colontmp_ = (NI)(half - ((NI) 1));
#line 77 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
			nimln_(77, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");			res = ((NI) 0);			{
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
				nimln_(78, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");				while (1) {					NIM_CHAR T12_;
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
					if (!(res <= colontmp_)) goto LA11;

#line 41 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
					nimln_(41, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");					t = res;
#line 41 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
					nimPrepareStrMutationV2((&result));					nimPrepareStrMutationV2((&result));					T12_ = (NIM_CHAR)0;
#line 41 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"

#line 41 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
					T12_ = result.p->data[t];					result.p->data[t] = result.p->data[(NI)((NI)(i - t) - ((NI) 1))];					result.p->data[(NI)((NI)(i - t) - ((NI) 1))] = T12_;
#line 80 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
					nimln_(80, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");					res += ((NI) 1);				} LA11: ;
			}
		}
	}
	LA1_: ;
	popFrame();	return result;}

#line 106 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___Ai9a6F9b9aMiawDJZ2TeoENGQ)(ip4_addr_t x) {	NimStringV2 result;	NI count_1;	nimfr_("$", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	result.len = 0; result.p = NIM_NIL;
#line 114 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(114, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_34;
#line 116 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(116, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	count_1 = ((NI) 0);
#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(118, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	{
#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		if (!(((NI) 0) < count_1)) goto LA3_;

#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
		prepareAdd((&result), 2);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_35);	}
	LA3_: ;

#line 120 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(120, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	prepareAdd((&result), 7);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_37);
#line 121 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(121, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	prepareAdd((&result), 2);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_38);
#line 122 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(122, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	count_1 += ((NI) 1);
#line 128 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(128, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");
#line 128 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	addQuoted__DMSWtl26Af0OtoygyWiFow((&result), x.addr);

#line 134 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim"
	nimln_(134, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/dollars.nim");	prepareAdd((&result), 1);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_39);	popFrame();	return result;}
