/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <errno.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct TNimTypeV2 {void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
void* typeInfoV1;
};
struct RootObj {TNimTypeV2* m_type;};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {  Exception Sup;};
struct tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA {  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;NI32 errorCode;
};


#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA*, newOSError__JXEuze9ctNbkn51HYBflQLg)(NI32 errorCode, NimStringV2 additionalInfo);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___atv3i14bWKtHLJtkExojTA)(tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA** dest);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, osErrorMsg__33xViSVWAmDrexoKkLfMhg)(NI32 errorCode);
static N_INLINE(NIM_CHAR, X5BX5D___okzHJ6GE9cv0bYG3b4r5KCAsystem)(NimStringV2 s, NI i);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__45fPtFhY4FavRaYwDhRfuA)(NimStringV2* s, NimStringV2 x);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_3 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_2};
extern TNimTypeV2 NTIv2__BeJgrOdDsczOwEWOZbRfKA_;
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_7 = { 17 | NIM_STRLIT_FLAG, "Additional info: " };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_8 = {17, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_7};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_11 = { 16 | NIM_STRLIT_FLAG, "unknown OS error" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_12 = {16, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_11};

/* section: NIM_merge_VARS */
N_LIB_PRIVATE NIM_THREADVAR tySequence__sM4lkSb7zS6F7OVMvW9cffQ environment__mlhK49b6YMgc9cgrcYkKq9a3g;
N_LIB_PRIVATE NIM_THREADVAR NIM_BOOL envComputed__LLyFo9bsdu1ZXMDvAe8DhrQ;
extern NCSTRING* environ;
extern int cmdCount;
extern NCSTRING* cmdLine;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__9bUWNxbcGnToMWA9b79aTXLIw)(void) {	NI32 result;	result = (NI32)0;
#line 119 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	result = errno;	return result;}

#line 544 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;

#line 546 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 18 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, osErrorMsg__33xViSVWAmDrexoKkLfMhg)(NI32 errorCode) {	NimStringV2 result;	nimfr_("osErrorMsg", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");	result.len = 0; result.p = NIM_NIL;
#line 39 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	nimln_(39, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");	result = TM__yu6cxgKBBXbNsTkT9cyMd4g_3;
#line 57 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	nimln_(57, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");	{		NCSTRING T5_;		NimStringV2 T6_;
#line 57 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"

#line 57 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
		if (!!((errorCode == ((NI32) 0)))) goto LA3_;

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
		nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 58 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
		nimln_(58, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");
#line 58 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"

#line 58 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
		T5_ = (NCSTRING)0;		T5_ = strerror(errorCode);		T6_.len = 0; T6_.p = NIM_NIL;		T6_ = cstrToNimstr(T5_);
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
		nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");		eqsink___aBBXmHFBEivKqERloP6zmA_2((&result), T6_);
	}
	LA3_: ;
	popFrame();	return result;}

#line 2590 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
static N_INLINE(NIM_CHAR, X5BX5D___okzHJ6GE9cv0bYG3b4r5KCAsystem)(NimStringV2 s, NI i) {	NIM_CHAR result;	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_4;	nimfr_("[]", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");{	result = (NIM_CHAR)0;
#line 2590 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimln_(2590, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");
#line 2590 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"

#line 2590 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	if (nimSubInt(s.len, i, &TM__yu6cxgKBBXbNsTkT9cyMd4g_4)) { raiseOverflow(); goto BeforeRet_;};	if ((NU)((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_4)) >= (NU)s.len){ raiseIndexError2((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_4),s.len-1); goto BeforeRet_;}	result = s.p->data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_4)];	}BeforeRet_: ;
	popFrame();	return result;}

#line 65 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c) {	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_5;	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_6;{
#line 67 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"

#line 67 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	prepareAdd(s, ((NI) 1));

#line 68 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	(*(*s).p).data[(*s).len] = c;
#line 69 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	if (nimAddInt((*s).len, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_5)) { raiseOverflow(); goto BeforeRet_;};
#line 69 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	(*(*s).p).data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_5)] = 0;
#line 70 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	if (nimAddInt((*s).len, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_6)) { raiseOverflow(); goto BeforeRet_;};	(*s).len = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_6);	}BeforeRet_: ;
}

#line 11 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size) {	void* T1_;
#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source_0, ((size_t) (size)));}

#line 2186 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size) {
#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"

#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimCopyMem(dest, source_0, size);
}

#line 94 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {{
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	{		void* T5_;		void* T6_;		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_9;		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_10;
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (!(((NI) 0) < src.len)) goto LA3_;

#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		T5_ = (void*)0;		T5_ = ((void*) ((&(*(*dest).p).data[(*dest).len])));		T6_ = (void*)0;		T6_ = ((void*) ((&(*src.p).data[((NI) 0)])));
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (nimAddInt(src.len, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_9)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_9)) < ((NI) 0) || ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_9)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_9), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(T5_, T6_, ((NI) ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_9))));

#line 98 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (nimAddInt((*dest).len, src.len, &TM__yu6cxgKBBXbNsTkT9cyMd4g_10)) { raiseOverflow(); goto BeforeRet_;};		(*dest).len = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_10);	}
	LA3_: ;
	}BeforeRet_: ;
}

#line 414 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 60 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
N_LIB_PRIVATE N_NOINLINE(tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA*, newOSError__JXEuze9ctNbkn51HYBflQLg)(NI32 errorCode, NimStringV2 additionalInfo) {	tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA* result;	tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA* e;	NimStringV2 T2_;NIM_BOOL oldNimErrFin1_;NIM_BOOL* nimErr_;	nimfr_("newOSError", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");{nimErr_ = nimErrorFlag();	result = (tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA*)0;	e = (tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA*)0;
#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	nimln_(43, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");
#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	eqdestroy___atv3i14bWKtHLJtkExojTA(&e);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 78 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	nimln_(78, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");	e = (tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA*) nimNewObj(sizeof(tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA), NIM_ALIGNOF(tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA));	(*e).Sup.Sup.Sup.m_type = (&NTIv2__BeJgrOdDsczOwEWOZbRfKA_);	(*e).Sup.Sup.name = "OSError";
#line 79 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	nimln_(79, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");	(*e).errorCode = errorCode;
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 80 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	nimln_(80, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");
#line 80 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	T2_.len = 0; T2_.p = NIM_NIL;	T2_ = osErrorMsg__33xViSVWAmDrexoKkLfMhg(errorCode);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");	eqsink___aBBXmHFBEivKqERloP6zmA_2((&(*e).Sup.Sup.message), T2_);

#line 81 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	nimln_(81, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");	{
#line 81 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"

#line 81 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
		if (!(((NI) 0) < additionalInfo.len)) goto LA5_;

#line 82 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
		nimln_(82, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");		{			NIM_BOOL T9_;			NIM_CHAR T11_;
#line 82 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
			T9_ = (NIM_BOOL)0;
#line 82 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"

#line 82 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
			T9_ = (((NI) 0) < (*e).Sup.Sup.message.len);			if (!(T9_)) goto LA10_;

#line 82 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"

#line 82 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"

#line 82 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"

#line 82 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
			T11_ = (NIM_CHAR)0;			T11_ = X5BX5D___okzHJ6GE9cv0bYG3b4r5KCAsystem((*e).Sup.Sup.message, ((NI) 1));			T9_ = !(((NU8)(T11_) == (NU8)(10)));			LA10_: ;
			if (!T9_) goto LA12_;

#line 82 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
			nimAddCharV1((&(*e).Sup.Sup.message), 10);		}
		LA12_: ;

#line 83 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
		nimln_(83, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");		prepareAdd((&(*e).Sup.Sup.message), 17);appendString((&(*e).Sup.Sup.message), TM__yu6cxgKBBXbNsTkT9cyMd4g_8);
#line 84 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
		nimln_(84, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");
#line 84 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
		addQuoted__45fPtFhY4FavRaYwDhRfuA((&(*e).Sup.Sup.message), additionalInfo);
	}
	LA5_: ;

#line 85 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	nimln_(85, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");	{
#line 85 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
		if (!((*e).Sup.Sup.message.len == 0)) goto LA16_;

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
		nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
		eqsink___aBBXmHFBEivKqERloP6zmA_2((&(*e).Sup.Sup.message), TM__yu6cxgKBBXbNsTkT9cyMd4g_12);
	}
	LA16_: ;

#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	nimln_(87, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");
#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	result = e;
#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	e = 0;
#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	nimln_(43, "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.n"
"im");
#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
	eqdestroy___atv3i14bWKtHLJtkExojTA(&e);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	goto BeforeRet_;
	{		LA1_:;	}
	{		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"

#line 43 "/home/elcritch/projects/bessel/mcus/nesper/src/nesper/general.nim"
		eqdestroy___atv3i14bWKtHLJtkExojTA(&e);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		*nimErr_ = oldNimErrFin1_;	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 89 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__CWyPYlyH9a6rAuZckFyVxPA)(NI32 errorCode, NimStringV2 additionalInfo) {	tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA* T1_;NIM_BOOL* nimErr_;	nimfr_("raiseOSError", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");{nimErr_ = nimErrorFlag();
#line 94 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	nimln_(94, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim");
#line 94 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	T1_ = (tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA*)0;	T1_ = newOSError__JXEuze9ctNbkn51HYBflQLg(errorCode, additionalInfo);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 94 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr.nim"
	raiseExceptionEx((Exception*)T1_, "OSError", "raiseOSError", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/includes/oserr"
".nim", 94);	goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}
