/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_Table__qagh2zcXAhSb9aRfetCb26g tyObject_Table__qagh2zcXAhSb9aRfetCb26g;
typedef struct tySequence__JiteSJxrvz63iP2o9bcn2Sg tySequence__JiteSJxrvz63iP2o9bcn2Sg;
typedef struct tySequence__JiteSJxrvz63iP2o9bcn2Sg_Content tySequence__JiteSJxrvz63iP2o9bcn2Sg_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__g1w83cyyBYiVU9c8WEJWnjQ tyTuple__g1w83cyyBYiVU9c8WEJWnjQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
struct tySequence__JiteSJxrvz63iP2o9bcn2Sg {
  NI len; tySequence__JiteSJxrvz63iP2o9bcn2Sg_Content* p;
};
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyTuple__g1w83cyyBYiVU9c8WEJWnjQ {
NI Field0;
NimStringV2 Field1;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ Field2;
};
struct tyObject_Table__qagh2zcXAhSb9aRfetCb26g {tySequence__JiteSJxrvz63iP2o9bcn2Sg data;
NI counter;
};
struct TNimTypeV2 {void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
void* typeInfoV1;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {NI rc;
NI rootIdx;
};
struct RootObj {TNimTypeV2* m_type;};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {  Exception Sup;};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;};
struct tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag {  tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw Sup;};


#ifndef tySequence__JiteSJxrvz63iP2o9bcn2Sg_Content_PP
#define tySequence__JiteSJxrvz63iP2o9bcn2Sg_Content_PP
struct tySequence__JiteSJxrvz63iP2o9bcn2Sg_Content { NI cap; tyTuple__g1w83cyyBYiVU9c8WEJWnjQ data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__JiteSJxrvz63iP2o9bcn2Sg_Content_PP
#define tySequence__JiteSJxrvz63iP2o9bcn2Sg_Content_PP
struct tySequence__JiteSJxrvz63iP2o9bcn2Sg_Content { NI cap; tyTuple__g1w83cyyBYiVU9c8WEJWnjQ data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___rVMSIO7FeB1qXZmZBVjm9bA)(tySequence__JiteSJxrvz63iP2o9bcn2Sg* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___0RiuPw9cXhtLB9a2rQ2jA69cg)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p, NI align);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___niuAxNwqyG9a9a74kbKT3Jvg)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___RHcedK7oceGcKZDLXASTFg)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* dest, void* env);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___Bw6rkbisohGssVnyybEBXw)(tySequence__JiteSJxrvz63iP2o9bcn2Sg* dest, void* env);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___kDvIcrGphqE2lmGa3RNr5A)(NimStringV2* dest, void* env);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___Pk9aHRwCWYoh6bHcnpHP9cjA)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest, void* env);
N_LIB_PRIVATE N_NIMCALL(void, eqdispose___niuAxNwqyG9a9a74kbKT3Jvg_2)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdispose___rVMSIO7FeB1qXZmZBVjm9bA_2)(tySequence__JiteSJxrvz63iP2o9bcn2Sg* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdispose___0RiuPw9cXhtLB9a2rQ2jA69cg_2)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___fdWoyreyLeQYniNrjPllWQ)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g** dest);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___ic9a3GZ2Kbgw2QwLw0A1dMQ)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* dest, tyObject_Table__qagh2zcXAhSb9aRfetCb26g src);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__qagh2zcXAhSb9aRfetCb26g, initTable__SqfOLrJ2jX4F8voe66ZkMA)(NI initialSize);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NI, slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables)(NI count_0);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__v2qC0V55wqa9bmqc7eHTz8A)(NI x);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize, NI elemAlign);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___r6aagoRVuov7HvfEjIi3Uw)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest, tySequence__sM4lkSb7zS6F7OVMvW9cffQ src);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___mN6pEafN35VS9clM9cSab8RQ)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t, NimStringV2 key_0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ val);
static N_INLINE(NI, rawGet__a59cxMy3qya79c49c6saGCAYQtables)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g t, NimStringV2 key_0, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash__6PCYkKlCNhq9cnRLnqWKkwQ)(NimStringV2 x);
static N_INLINE(NIM_BOOL, isFilled__5Qpmu5QqwDY0esVXn6wf7wtables)(NI hcode);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b);
static N_INLINE(NIM_BOOL, equalMem__Bj9c9cm9cBM9coLsuNsT5BvZ9awsystem)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
static N_INLINE(NI, nextTry__rkF6R1GhqjFh3qSAPaT2Cwtables)(NI h, NI maxHash);
static N_INLINE(NIM_BOOL, mustRehash__Cw5tu1F8pT6sRMGgcm4llwtables)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g t);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringV2 msg);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__9bDxMze9c2f8NEFsPxeJU0pw)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__33xmfwuCZJNeqIPBi0H8pw)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t, tySequence__JiteSJxrvz63iP2o9bcn2Sg* data, NimStringV2 key_0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ val, NI hc, NI h);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(NI, rawGetKnownHC__pRA9b9bdkleBl5PhvlctfVdwtables)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g t, NimStringV2 key_0, NI hc);
N_LIB_PRIVATE N_NIMCALL(void, del__lDa9cDK9bq8jxuc4T2AsuSpw)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t, NimStringV2 key_0);
static N_INLINE(NIM_BOOL, isEmpty__5Qpmu5QqwDY0esVXn6wf7w_2tables)(NI hcode);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___BX2JqNf2E8tN5tqtm9b9aGeg)(tyTuple__g1w83cyyBYiVU9c8WEJWnjQ* dest, tyTuple__g1w83cyyBYiVU9c8WEJWnjQ src);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__wwb7zLiuOeGGoJCfnH0nvQ)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g t, NimStringV2 key_0);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, X5BX5D___089bL9acZbwGZxIQ4YKu4uOg)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t, NimStringV2 key_0);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);

/* section: NIM_merge_DATA */
N_LIB_PRIVATE TNimTypeV2 NTIv2__qagh2zcXAhSb9aRfetCb26g_;
static const struct {
  NI cap; NIM_CHAR data[108+1];
} TM__4SoG2KRQy3oMm9aUzSLtGrA_9 = { 108 | NIM_STRLIT_FLAG, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim(34, 9) `\012t.counter < t.dataLen` " };
static const NimStringV2 TM__4SoG2KRQy3oMm9aUzSLtGrA_10 = {108, (NimStrPayload*)&TM__4SoG2KRQy3oMm9aUzSLtGrA_9};
extern TNimTypeV2 NTIv2__t7nhKLvXTQS9cS8ByJU9bIag_;
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__4SoG2KRQy3oMm9aUzSLtGrA_21 = { 15 | NIM_STRLIT_FLAG, "key not found: " };
static const NimStringV2 TM__4SoG2KRQy3oMm9aUzSLtGrA_22 = {15, (NimStrPayload*)&TM__4SoG2KRQy3oMm9aUzSLtGrA_21};

/* section: NIM_merge_VARS */
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___rVMSIO7FeB1qXZmZBVjm9bA)(tySequence__JiteSJxrvz63iP2o9bcn2Sg* dest) {	NI colontmp_;
#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	colontmp_ = ((NI) 0);	{
#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		while (1) {			NI T3_;
#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			T3_ = (*dest).len;			if (!(colontmp_ < T3_)) goto LA2;

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).p->data[colontmp_].Field1));

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			eqdestroy___0RiuPw9cXhtLB9a2rQ2jA69cg((&(*dest).p->data[colontmp_].Field2));

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			colontmp_ += ((NI) 1);		} LA2: ;
	}

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) { alignedDealloc((*dest).p, NIM_ALIGNOF(tyTuple__g1w83cyyBYiVU9c8WEJWnjQ));}}

#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___niuAxNwqyG9a9a74kbKT3Jvg)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* dest) {
#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	eqdestroy___rVMSIO7FeB1qXZmZBVjm9bA((&(*dest).data));
}

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___Bw6rkbisohGssVnyybEBXw)(tySequence__JiteSJxrvz63iP2o9bcn2Sg* dest, void* env) {	NI colontmp_;
#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	colontmp_ = ((NI) 0);	{
#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		while (1) {			NI T3_;
#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			T3_ = (*dest).len;			if (!(colontmp_ < T3_)) goto LA2;

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			eqtrace___kDvIcrGphqE2lmGa3RNr5A((&(*dest).p->data[colontmp_].Field1), env);

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			eqtrace___Pk9aHRwCWYoh6bHcnpHP9cjA((&(*dest).p->data[colontmp_].Field2), env);

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			colontmp_ += ((NI) 1);		} LA2: ;
	}
}

#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___RHcedK7oceGcKZDLXASTFg)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* dest, void* env) {
#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	eqtrace___Bw6rkbisohGssVnyybEBXw((&(*dest).data), env);
}

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdispose___rVMSIO7FeB1qXZmZBVjm9bA_2)(tySequence__JiteSJxrvz63iP2o9bcn2Sg* dest) {	NI colontmp_;
#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	colontmp_ = ((NI) 0);	{
#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		while (1) {			NI T3_;
#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			T3_ = (*dest).len;			if (!(colontmp_ < T3_)) goto LA2;

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			eqdispose___dS1BF3Vxjg9aJMmmhVJKSpQ_2((&(*dest).p->data[colontmp_].Field1));

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			eqdispose___0RiuPw9cXhtLB9a2rQ2jA69cg_2((&(*dest).p->data[colontmp_].Field2));

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			colontmp_ += ((NI) 1);		} LA2: ;
	}

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) { alignedDealloc((*dest).p, NIM_ALIGNOF(tyTuple__g1w83cyyBYiVU9c8WEJWnjQ));}}

#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdispose___niuAxNwqyG9a9a74kbKT3Jvg_2)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* dest) {
#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	eqdispose___rVMSIO7FeB1qXZmZBVjm9bA_2((&(*dest).data));
}

#line 544 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;

#line 546 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 436 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics.nim"
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {	NI result;	nimfr_("-%", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics."
"nim");	result = (NI)0;
#line 437 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics.nim"
	nimln_(437, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics."
"nim");
#line 441 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics.nim"
	nimln_(441, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arithmetics."
"nim");	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));	popFrame();	return result;}

#line 186 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {	NIM_BOOL result;	nimfr_("nimDecRefIsLast", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");{	result = (NIM_BOOL)0;
#line 187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
	nimln_(187, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");	{		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;		NI T5_;
#line 187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"

#line 187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		if (!!((p == NIM_NIL))) goto LA3_;

#line 188 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		nimln_(188, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		nimln_(63, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		T5_ = (NI)0;		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 8));		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
#line 195 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
		nimln_(195, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");		{
#line 195 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"

#line 195 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
			if (!((NI)((*cell).rc & ((NI) -16)) == ((NI) 0))) goto LA8_;

#line 196 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
			nimln_(196, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");			result = NIM_TRUE;		}
		goto LA6_;
		LA8_: ;
		{			NI TM__4SoG2KRQy3oMm9aUzSLtGrA_2;
#line 200 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim"
			nimln_(200, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/arc.nim");			if (nimSubInt((*cell).rc, ((NI) 16), &TM__4SoG2KRQy3oMm9aUzSLtGrA_2)) { raiseOverflow(); goto BeforeRet_;};			(*cell).rc = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_2);		}
		LA6_: ;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqsink___d7gAg5L4VylfG9broPtLixg)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g** dest, tyObject_Table__qagh2zcXAhSb9aRfetCb26g* src) {
#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	{		NIM_BOOL T3_;
#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLast((*dest));		if (!T3_) goto LA4_;

#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
		eqdestroy___niuAxNwqyG9a9a74kbKT3Jvg((*dest));

#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
		nimRawDispose((*dest), ((NI) 4));
	}
	LA4_: ;

#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	(*dest) = src;}

#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___fdWoyreyLeQYniNrjPllWQ)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g** dest) {
#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	{		NIM_BOOL T3_;
#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLast((*dest));		if (!T3_) goto LA4_;

#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
		eqdestroy___niuAxNwqyG9a9a74kbKT3Jvg((*dest));

#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
		nimRawDispose((*dest), ((NI) 4));
	}
	LA4_: ;
}

#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqsink___ic9a3GZ2Kbgw2QwLw0A1dMQ)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* dest, tyObject_Table__qagh2zcXAhSb9aRfetCb26g src) {
#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	if ((*dest).data.p != src.data.p) {
#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	eqdestroy___rVMSIO7FeB1qXZmZBVjm9bA((&(*dest).data));
	}(*dest).data.len = src.data.len; (*dest).data.p = src.data.p;
#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	(*dest).counter = src.counter;}

#line 22 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 24 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 414 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 33 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 122 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 117 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 117 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 117 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		T3_ = (a == ((NI) (-2147483647 -1)));		if (!(T3_)) goto LA4_;

#line 117 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		T3_ = (b == ((NI) -1));		LA4_: ;
		if (!T3_) goto LA5_;

#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	goto LA1_;
	LA5_: ;
	{
#line 120 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"

#line 120 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/integerops.nim"
		(*res) = (NI)(a / b);	}
	LA1_: ;
	return result;}

#line 37 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
static N_INLINE(NI, slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables)(NI count_0) {	NI result;	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_3;	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_4;	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_5;NIM_BOOL* nimErr_;	nimfr_("slotsNeeded", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");{nimErr_ = nimErrorFlag();	result = (NI)0;
#line 39 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	nimln_(39, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 39 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 39 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 39 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	if (nimMulInt(((NI) (count_0)), ((NI) 3), &TM__4SoG2KRQy3oMm9aUzSLtGrA_3)) { raiseOverflow(); goto BeforeRet_;};	if (((NI) 2) == 0){ raiseDivByZero(); goto BeforeRet_;}	if (nimDivInt((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_3), ((NI) 2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_4)) { raiseOverflow(); goto BeforeRet_;};	if (nimAddInt((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_4), ((NI) 4), &TM__4SoG2KRQy3oMm9aUzSLtGrA_5)) { raiseOverflow(); goto BeforeRet_;};
#line 39 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	result = nextPowerOfTwo__v2qC0V55wqa9bmqc7eHTz8A((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_5));	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 288 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__qagh2zcXAhSb9aRfetCb26g, initTable__SqfOLrJ2jX4F8voe66ZkMA)(NI initialSize) {	tyObject_Table__qagh2zcXAhSb9aRfetCb26g result;	NI correctSizeX60gensym0_;NIM_BOOL* nimErr_;	nimfr_("initTable", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");{nimErr_ = nimErrorFlag();	nimZeroMem((void*)(&result), sizeof(tyObject_Table__qagh2zcXAhSb9aRfetCb26g));
#line 163 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	nimln_(163, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");	if ((initialSize) < ((NI) 0) || (initialSize) > ((NI) 2147483647)){ raiseRangeErrorI(initialSize, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 163 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	correctSizeX60gensym0_ = slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables(((NI) (initialSize)));	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 167 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	nimln_(167, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");	result.counter = ((NI) 0);
#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	nimln_(168, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");	if ((correctSizeX60gensym0_) < ((NI) 0) || (correctSizeX60gensym0_) > ((NI) 2147483647)){ raiseRangeErrorI(correctSizeX60gensym0_, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}	result.data.len = ((NI) (correctSizeX60gensym0_)); result.data.p = (tySequence__JiteSJxrvz63iP2o9bcn2Sg_Content*) newSeqPayload(((NI) (correctSizeX60gensym0_)), sizeof(tyTuple__g1w83cyyBYiVU9c8WEJWnjQ), NIM_ALIGNOF(tyTuple__g1w83cyyBYiVU9c8WEJWnjQ));	}BeforeRet_: ;
	popFrame();	return result;}

#line 798 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__qagh2zcXAhSb9aRfetCb26g*, newTable__j9aovL9c5jjTLwk0JUYr9b7Tg)(NI initialSize) {	tyObject_Table__qagh2zcXAhSb9aRfetCb26g* result;	tyObject_Table__qagh2zcXAhSb9aRfetCb26g T1_;NIM_BOOL* nimErr_;	nimfr_("newTable", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");{nimErr_ = nimErrorFlag();	result = (tyObject_Table__qagh2zcXAhSb9aRfetCb26g*)0;
#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(826, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");
#line 826 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	eqdestroy___fdWoyreyLeQYniNrjPllWQ(&result);

#line 810 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(810, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");	result = (tyObject_Table__qagh2zcXAhSb9aRfetCb26g*) nimNewObj(sizeof(tyObject_Table__qagh2zcXAhSb9aRfetCb26g), NIM_ALIGNOF(tyObject_Table__qagh2zcXAhSb9aRfetCb26g));
#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(332, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");
#line 811 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(811, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");
#line 811 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	T1_ = initTable__SqfOLrJ2jX4F8voe66ZkMA(initialSize);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 332 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(332, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");	eqsink___ic9a3GZ2Kbgw2QwLw0A1dMQ((&(*result)), T1_);
	}BeforeRet_: ;
	popFrame();	return result;}

#line 1062 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(void, clear__07MLq9aB3eLozSrm47FsXlQ)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t) {	nimfr_("clear", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");{	{		NI i;		NI colontmp_;		NI T2_;		NI i_2;		i = (NI)0;		colontmp_ = (NI)0;
#line 149 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		nimln_(149, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");
#line 149 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		T2_ = (*t).data.len;		colontmp_ = T2_;
#line 106 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
		nimln_(106, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");		i_2 = ((NI) 0);		{
#line 107 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
			nimln_(107, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");			while (1) {				NimStringV2 T5_;				tySequence__sM4lkSb7zS6F7OVMvW9cffQ T6_;				NI TM__4SoG2KRQy3oMm9aUzSLtGrA_6;
#line 107 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
				if (!(i_2 < colontmp_)) goto LA4;

#line 149 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
				nimln_(149, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");				i = i_2;				if ((NU)(i) >= (NU)(*t).data.len){ raiseIndexError2(i,(*t).data.len-1); goto BeforeRet_;}
#line 151 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
				nimln_(151, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");				(*t).data.p->data[i].Field0 = ((NI) 0);
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
				nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");				if ((NU)(i) >= (NU)(*t).data.len){ raiseIndexError2(i,(*t).data.len-1); goto BeforeRet_;}
#line 152 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
				nimln_(152, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");				T5_.len = 0; T5_.p = NIM_NIL;
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
				nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");				eqsink___aBBXmHFBEivKqERloP6zmA_2((&(*t).data.p->data[i].Field1), T5_);

#line 2214 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
				nimln_(2214, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");				if ((NU)(i) >= (NU)(*t).data.len){ raiseIndexError2(i,(*t).data.len-1); goto BeforeRet_;}
#line 153 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
				nimln_(153, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");				T6_.len = 0; T6_.p = NIM_NIL;
#line 2214 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
				nimln_(2214, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");				eqsink___r6aagoRVuov7HvfEjIi3Uw((&(*t).data.p->data[i].Field2), T6_);

#line 109 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
				nimln_(109, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");				if (nimAddInt(i_2, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_6)) { raiseOverflow(); goto BeforeRet_;};				i_2 = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_6);			} LA4: ;
		}
	}

#line 154 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	nimln_(154, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");	(*t).counter = ((NI) 0);	}BeforeRet_: ;
	popFrame();}

#line 26 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
static N_INLINE(NIM_BOOL, isFilled__5Qpmu5QqwDY0esVXn6wf7wtables)(NI hcode) {	NIM_BOOL result;	nimfr_("isFilled", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");	result = (NIM_BOOL)0;
#line 27 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	nimln_(27, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 27 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 27 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	result = !((hcode == ((NI) 0)));	popFrame();	return result;}

#line 36 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {	int result;	result = (int)0;
#line 38 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 38 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	result = memcmp(a, b, ((size_t) (size)));	return result;}

#line 2194 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
static N_INLINE(NIM_BOOL, equalMem__Bj9c9cm9cBM9coLsuNsT5BvZ9awsystem)(void* a, void* b, NI size) {	NIM_BOOL result;	int T1_;	result = (NIM_BOOL)0;
#line 2195 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"

#line 2195 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"

#line 2195 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"

#line 2195 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	T1_ = (int)0;	T1_ = nimCmpMem(a, b, size);	result = (T1_ == ((NI32) 0));	return result;}

#line 23 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.nim"
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b) {	NIM_BOOL result;	NI alen;	NI blen;	nimfr_("eqStrings", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.ni"
"m");{	result = (NIM_BOOL)0;
#line 24 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.nim"
	nimln_(24, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.ni"
"m");
#line 24 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.nim"
	alen = a.len;
#line 25 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.nim"
	nimln_(25, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.ni"
"m");
#line 25 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.nim"
	blen = b.len;
#line 26 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.nim"
	nimln_(26, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.ni"
"m");	{
#line 26 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.nim"
		if (!(alen == blen)) goto LA3_;

#line 27 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.nim"
		nimln_(27, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.ni"
"m");		{
#line 27 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.nim"
			if (!(alen == ((NI) 0))) goto LA7_;

#line 27 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.nim"

#line 27 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.nim"
			result = NIM_TRUE;			goto BeforeRet_;
		}
		LA7_: ;

#line 28 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.nim"
		nimln_(28, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.ni"
"m");
#line 28 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.nim"

#line 28 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strmantle.nim"
		result = equalMem__Bj9c9cm9cBM9coLsuNsT5BvZ9awsystem(((void*) ((&a.p->data[((NI) 0)]))), ((void*) ((&b.p->data[((NI) 0)]))), ((NI) (alen)));		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 29 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
static N_INLINE(NI, nextTry__rkF6R1GhqjFh3qSAPaT2Cwtables)(NI h, NI maxHash) {	NI result;	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_7;	nimfr_("nextTry", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");{	result = (NI)0;
#line 30 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	nimln_(30, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 30 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 30 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	if (nimAddInt(h, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_7)) { raiseOverflow(); goto BeforeRet_;};	result = (NI)((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_7) & maxHash);	}BeforeRet_: ;
	popFrame();	return result;}

#line 82 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
static N_INLINE(NI, rawGet__a59cxMy3qya79c49c6saGCAYQtables)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g t, NimStringV2 key_0, NI* hc) {	NI result;	NI T1_;	NI h;	NI T11_;	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_8;NIM_BOOL* nimErr_;	nimfr_("rawGet", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");{nimErr_ = nimErrorFlag();	result = (NI)0;
#line 69 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	nimln_(69, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 69 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	T1_ = (NI)0;	T1_ = hash__6PCYkKlCNhq9cnRLnqWKkwQ(key_0);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	(*hc) = T1_;
#line 79 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	nimln_(79, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");	{
#line 70 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
		nimln_(70, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");		if (!((*hc) == ((NI) 0))) goto LA4_;

#line 71 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
		nimln_(71, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");		(*hc) = ((NI) 314159265);	}
	LA4_: ;

#line 52 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	nimln_(52, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");	{		NI T8_;
#line 52 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 52 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
		T8_ = t.data.len;		if (!(T8_ == ((NI) 0))) goto LA9_;

#line 53 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
		nimln_(53, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 53 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
		result = ((NI) -1);		goto BeforeRet_;
	}
	LA9_: ;

#line 54 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	nimln_(54, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 54 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 54 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	T11_ = (t.data.len-1);	h = (NI)((*hc) & T11_);	{
#line 55 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
		nimln_(55, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");		while (1) {			NIM_BOOL T14_;			NI T21_;
#line 55 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
			if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;}
#line 55 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
			T14_ = (NIM_BOOL)0;			T14_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables(t.data.p->data[h].Field0);			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;			if (!T14_) goto LA13;

#line 60 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
			nimln_(60, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");			{				NIM_BOOL T17_;
#line 60 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
				T17_ = (NIM_BOOL)0;
#line 60 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;}				T17_ = (t.data.p->data[h].Field0 == (*hc));				if (!(T17_)) goto LA18_;

#line 60 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;}				T17_ = eqStrings(t.data.p->data[h].Field1, key_0);				LA18_: ;
				if (!T17_) goto LA19_;

#line 61 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
				nimln_(61, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 61 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
				result = h;				goto BeforeRet_;
			}
			LA19_: ;

#line 62 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
			nimln_(62, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 62 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
			T21_ = (t.data.len-1);
#line 62 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
			h = nextTry__rkF6R1GhqjFh3qSAPaT2Cwtables(h, T21_);			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		} LA13: ;
	}

#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	nimln_(63, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	if (nimSubInt(((NI) -1), h, &TM__4SoG2KRQy3oMm9aUzSLtGrA_8)) { raiseOverflow(); goto BeforeRet_;};	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_8);	}BeforeRet_: ;
	popFrame();	return result;}

#line 32 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
static N_INLINE(NIM_BOOL, mustRehash__Cw5tu1F8pT6sRMGgcm4llwtables)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g t) {	NIM_BOOL result;	NIM_BOOL T6_;	NI T7_;	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_11;	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_12;	NI T9_;	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_13;NIM_BOOL* nimErr_;	nimfr_("mustRehash", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");{nimErr_ = nimErrorFlag();	result = (NIM_BOOL)0;
#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	nimln_(34, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");	{		NI T3_;
#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
		T3_ = t.data.len;		if (!!((t.counter < T3_))) goto LA4_;

#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 34 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__4SoG2KRQy3oMm9aUzSLtGrA_10);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA4_: ;

#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	nimln_(35, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	T6_ = (NIM_BOOL)0;
#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	T7_ = t.data.len;	if (nimMulInt(T7_, ((NI) 2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_11)) { raiseOverflow(); goto BeforeRet_;};
#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	if (nimMulInt(t.counter, ((NI) 3), &TM__4SoG2KRQy3oMm9aUzSLtGrA_12)) { raiseOverflow(); goto BeforeRet_;};	T6_ = ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_11) < (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_12));	if (T6_) goto LA8_;

#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	T9_ = t.data.len;	if (nimSubInt(T9_, t.counter, &TM__4SoG2KRQy3oMm9aUzSLtGrA_13)) { raiseOverflow(); goto BeforeRet_;};	T6_ = ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_13) < ((NI) 4));	LA8_: ;
	result = T6_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 29 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__33xmfwuCZJNeqIPBi0H8pw)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t, tySequence__JiteSJxrvz63iP2o9bcn2Sg* data, NimStringV2 key_0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ val, NI hc, NI h) {	nimfr_("rawInsert", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");{
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");	if ((NU)(h) >= (NU)(*data).len){ raiseIndexError2(h,(*data).len-1); goto BeforeRet_;}
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
	eqcopy___aBBXmHFBEivKqERloP6zmA((&(*data).p->data[h].Field1), key_0);

#line 2214 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimln_(2214, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");	if ((NU)(h) >= (NU)(*data).len){ raiseIndexError2(h,(*data).len-1); goto BeforeRet_;}
#line 2214 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	eqsink___r6aagoRVuov7HvfEjIi3Uw((&(*data).p->data[h].Field2), val);
	if ((NU)(h) >= (NU)(*data).len){ raiseIndexError2(h,(*data).len-1); goto BeforeRet_;}
#line 24 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	nimln_(24, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");	(*data).p->data[h].Field0 = hc;	}BeforeRet_: ;
	popFrame();}

#line 266 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(void, enlarge__9bDxMze9c2f8NEFsPxeJU0pw)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t) {	tySequence__JiteSJxrvz63iP2o9bcn2Sg n;	NI T1_;	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_14;	tySequence__JiteSJxrvz63iP2o9bcn2Sg T2_;NIM_BOOL* nimErr_;	nimfr_("enlarge", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");{nimErr_ = nimErrorFlag();	n.len = 0; n.p = NIM_NIL;
#line 268 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(268, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");
#line 268 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 268 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	T1_ = (*t).data.len;	if (nimMulInt(T1_, ((NI) 2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_14)) { raiseOverflow(); goto BeforeRet_;};	if (((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_14)) < ((NI) 0) || ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_14)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_14), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}	n.len = ((NI) ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_14))); n.p = (tySequence__JiteSJxrvz63iP2o9bcn2Sg_Content*) newSeqPayload(((NI) ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_14))), sizeof(tyTuple__g1w83cyyBYiVU9c8WEJWnjQ), NIM_ALIGNOF(tyTuple__g1w83cyyBYiVU9c8WEJWnjQ));
#line 269 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(269, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");	T2_.len = 0; T2_.p = NIM_NIL;	T2_ = (*t).data;	(*t).data = n;	n = T2_;	{		NI i;		NI colontmp_;		NI T4_;		NI res;		i = (NI)0;		colontmp_ = (NI)0;
#line 270 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
		nimln_(270, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");
#line 270 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
		T4_ = (n.len-1);		colontmp_ = T4_;
#line 56 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
		nimln_(56, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");		res = ((NI) 0);		{
#line 57 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
			nimln_(57, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");			while (1) {				NI eh;				NI TM__4SoG2KRQy3oMm9aUzSLtGrA_15;
#line 57 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
				if (!(res <= colontmp_)) goto LA6;

#line 270 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
				nimln_(270, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");				i = res;
#line 271 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
				nimln_(271, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");				if ((NU)(i) >= (NU)n.len){ raiseIndexError2(i,n.len-1); goto BeforeRet_;}				eh = n.p->data[i].Field0;
#line 272 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
				nimln_(272, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");				{					NIM_BOOL T9_;					NimStringV2 colontmpD_;					NI j;					NI T12_;					tyObject_Table__qagh2zcXAhSb9aRfetCb26g* T17_;					NimStringV2 T18_;					tySequence__sM4lkSb7zS6F7OVMvW9cffQ T19_;
#line 272 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 272 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
					T9_ = (NIM_BOOL)0;					T9_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables(eh);					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;					if (!T9_) goto LA10_;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
#line 273 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
					nimln_(273, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");
#line 273 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 273 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
					T12_ = ((*t).data.len-1);					j = (NI)(eh & T12_);					{
#line 274 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
						nimln_(274, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");						while (1) {							NIM_BOOL T15_;							NI T16_;
#line 274 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
							if ((NU)(j) >= (NU)(*t).data.len){ raiseIndexError2(j,(*t).data.len-1); goto BeforeRet_;}
#line 274 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
							T15_ = (NIM_BOOL)0;							T15_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables((*t).data.p->data[j].Field0);							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;							if (!T15_) goto LA14;

#line 275 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
							nimln_(275, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");
#line 275 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
							T16_ = ((*t).data.len-1);
#line 275 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
							j = nextTry__rkF6R1GhqjFh3qSAPaT2Cwtables(j, T16_);							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;						} LA14: ;
					}

#line 279 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
					nimln_(279, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");					T17_ = (tyObject_Table__qagh2zcXAhSb9aRfetCb26g*)0;					T17_ = t;
#line 279 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 279 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
					if ((NU)(i) >= (NU)n.len){ raiseIndexError2(i,n.len-1); goto BeforeRet_;}					colontmpD_ = n.p->data[i].Field1;					n.p->data[i].Field1.len = 0; n.p->data[i].Field1.p = NIM_NIL;					T18_.len = 0; T18_.p = NIM_NIL;					T18_ = colontmpD_;
#line 279 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
					if ((NU)(i) >= (NU)n.len){ raiseIndexError2(i,n.len-1); goto BeforeRet_;}					T19_.len = 0; T19_.p = NIM_NIL;					T19_ = n.p->data[i].Field2;					n.p->data[i].Field2.len = 0; n.p->data[i].Field2.p = NIM_NIL;
#line 279 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
					rawInsert__33xmfwuCZJNeqIPBi0H8pw(T17_, (&(*t).data), T18_, T19_, eh, j);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
					nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
					eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
				}
				LA10_: ;

#line 59 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1.nim"
				nimln_(59, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators_1."
"nim");				if (nimAddInt(res, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_15)) { raiseOverflow(); goto BeforeRet_;};				res = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_15);			} LA6: ;
		}
	}

#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	nimln_(168, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");
#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	eqdestroy___rVMSIO7FeB1qXZmZBVjm9bA((&n));
	}BeforeRet_: ;
	popFrame();}

#line 65 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
static N_INLINE(NI, rawGetKnownHC__pRA9b9bdkleBl5PhvlctfVdwtables)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g t, NimStringV2 key_0, NI hc) {	NI result;	NI h;	NI T6_;	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_16;NIM_BOOL* nimErr_;	nimfr_("rawGetKnownHC", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");{nimErr_ = nimErrorFlag();	result = (NI)0;
#line 52 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	nimln_(52, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");	{		NI T3_;
#line 52 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 52 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
		T3_ = t.data.len;		if (!(T3_ == ((NI) 0))) goto LA4_;

#line 53 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
		nimln_(53, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 53 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
		result = ((NI) -1);		goto BeforeRet_;
	}
	LA4_: ;

#line 54 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	nimln_(54, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 54 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"

#line 54 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	T6_ = (t.data.len-1);	h = (NI)(hc & T6_);	{
#line 55 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
		nimln_(55, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");		while (1) {			NIM_BOOL T9_;			NI T16_;
#line 55 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
			if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;}
#line 55 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
			T9_ = (NIM_BOOL)0;			T9_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables(t.data.p->data[h].Field0);			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;			if (!T9_) goto LA8;

#line 60 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
			nimln_(60, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");			{				NIM_BOOL T12_;
#line 60 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
				T12_ = (NIM_BOOL)0;
#line 60 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;}				T12_ = (t.data.p->data[h].Field0 == hc);				if (!(T12_)) goto LA13_;

#line 60 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;}				T12_ = eqStrings(t.data.p->data[h].Field1, key_0);				LA13_: ;
				if (!T12_) goto LA14_;

#line 61 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
				nimln_(61, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 61 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
				result = h;				goto BeforeRet_;
			}
			LA14_: ;

#line 62 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
			nimln_(62, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 62 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
			T16_ = (t.data.len-1);
#line 62 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
			h = nextTry__rkF6R1GhqjFh3qSAPaT2Cwtables(h, T16_);			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		} LA8: ;
	}

#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	nimln_(63, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 63 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	if (nimSubInt(((NI) -1), h, &TM__4SoG2KRQy3oMm9aUzSLtGrA_16)) { raiseOverflow(); goto BeforeRet_;};	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_16);	}BeforeRet_: ;
	popFrame();	return result;}

#line 303 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___mN6pEafN35VS9clM9cSab8RQ)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t, NimStringV2 key_0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ val) {	NI hc;	NI index;NIM_BOOL* nimErr_;	nimfr_("[]=", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");{nimErr_ = nimErrorFlag();
#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	nimln_(35, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");	{		NI T3_;		NI correctSizeX60gensym3_;
#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"

#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		T3_ = (*t).data.len;		if (!(T3_ == ((NI) 0))) goto LA4_;

#line 163 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		nimln_(163, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");
#line 163 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		correctSizeX60gensym3_ = slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables(((NI) 32));		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 167 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		nimln_(167, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");		(*t).counter = ((NI) 0);
#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		nimln_(168, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");		if ((correctSizeX60gensym3_) < ((NI) 0) || (correctSizeX60gensym3_) > ((NI) 2147483647)){ raiseRangeErrorI(correctSizeX60gensym3_, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}		(*t).data.len = ((NI) (correctSizeX60gensym3_)); (*t).data.p = (tySequence__JiteSJxrvz63iP2o9bcn2Sg_Content*) newSeqPayload(((NI) (correctSizeX60gensym3_)), sizeof(tyTuple__g1w83cyyBYiVU9c8WEJWnjQ), NIM_ALIGNOF(tyTuple__g1w83cyyBYiVU9c8WEJWnjQ));	}
	LA4_: ;
	hc = (NI)0;
#line 58 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	nimln_(58, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");
#line 58 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	index = rawGet__a59cxMy3qya79c49c6saGCAYQtables((*t), key_0, (&hc));	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 317 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(317, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");	{
#line 59 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		nimln_(59, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");		if (!(((NI) 0) <= index)) goto LA8_;

#line 2214 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
		nimln_(2214, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");		if ((NU)(index) >= (NU)(*t).data.len){ raiseIndexError2(index,(*t).data.len-1); goto BeforeRet_;}
#line 2214 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
		eqsink___r6aagoRVuov7HvfEjIi3Uw((&(*t).data.p->data[index].Field2), val);
	}
	goto LA6_;
	LA8_: ;
	{		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_17;		tyObject_Table__qagh2zcXAhSb9aRfetCb26g* T21_;		tySequence__sM4lkSb7zS6F7OVMvW9cffQ blitTmp;		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_18;
#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		nimln_(35, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");		{			NI T13_;			NI correctSizeX60gensym8_;
#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"

#line 35 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			T13_ = (*t).data.len;			if (!(T13_ == ((NI) 0))) goto LA14_;

#line 163 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			nimln_(163, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");
#line 163 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			correctSizeX60gensym8_ = slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables(((NI) 32));			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 167 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			nimln_(167, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");			(*t).counter = ((NI) 0);
#line 168 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			nimln_(168, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");			if ((correctSizeX60gensym8_) < ((NI) 0) || (correctSizeX60gensym8_) > ((NI) 2147483647)){ raiseRangeErrorI(correctSizeX60gensym8_, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}			(*t).data.len = ((NI) (correctSizeX60gensym8_)); (*t).data.p = (tySequence__JiteSJxrvz63iP2o9bcn2Sg_Content*) newSeqPayload(((NI) (correctSizeX60gensym8_)), sizeof(tyTuple__g1w83cyyBYiVU9c8WEJWnjQ), NIM_ALIGNOF(tyTuple__g1w83cyyBYiVU9c8WEJWnjQ));		}
		LA14_: ;

#line 48 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		nimln_(48, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");		{			NIM_BOOL T18_;
#line 48 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"

#line 48 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			T18_ = (NIM_BOOL)0;			T18_ = mustRehash__Cw5tu1F8pT6sRMGgcm4llwtables((*t));			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;			if (!T18_) goto LA19_;

#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			enlarge__9bDxMze9c2f8NEFsPxeJU0pw(t);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 50 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			nimln_(50, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");
#line 50 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
			index = rawGetKnownHC__pRA9b9bdkleBl5PhvlctfVdwtables((*t), key_0, hc);			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		}
		LA19_: ;

#line 51 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		nimln_(51, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");
#line 51 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		if (nimSubInt(((NI) -1), index, &TM__4SoG2KRQy3oMm9aUzSLtGrA_17)) { raiseOverflow(); goto BeforeRet_;};		index = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_17);
#line 52 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		nimln_(52, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");		T21_ = (tyObject_Table__qagh2zcXAhSb9aRfetCb26g*)0;		T21_ = t;
#line 52 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		blitTmp = val;
#line 52 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		rawInsert__33xmfwuCZJNeqIPBi0H8pw(T21_, (&(*t).data), key_0, blitTmp, hc, index);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 60 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		nimln_(60, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");		if (nimAddInt((*t).counter, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_18)) { raiseOverflow(); goto BeforeRet_;};		(*t).counter = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_18);	}
	LA6_: ;
	}BeforeRet_: ;
	popFrame();}

#line 860 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___cCZ4Lm3CwSTyjJEZ4An8yw)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t, NimStringV2 key_0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ val) {	tySequence__sM4lkSb7zS6F7OVMvW9cffQ blitTmp;NIM_BOOL* nimErr_;	nimfr_("[]=", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");{nimErr_ = nimErrorFlag();
#line 874 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(874, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");
#line 874 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	blitTmp = val;
#line 874 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	X5BX5Deq___mN6pEafN35VS9clM9cSab8RQ(t, key_0, blitTmp);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 23 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
static N_INLINE(NIM_BOOL, isEmpty__5Qpmu5QqwDY0esVXn6wf7w_2tables)(NI hcode) {	NIM_BOOL result;	nimfr_("isEmpty", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");	result = (NIM_BOOL)0;
#line 24 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	nimln_(24, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ha"
"shcommon.nim");
#line 24 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/hashcommon.nim"
	result = (hcode == ((NI) 0));	popFrame();	return result;}

#line 937 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqsink___BX2JqNf2E8tN5tqtm9b9aGeg)(tyTuple__g1w83cyyBYiVU9c8WEJWnjQ* dest, tyTuple__g1w83cyyBYiVU9c8WEJWnjQ src) {
#line 937 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	(*dest).Field0 = src.Field0;
#line 937 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	if ((*dest).Field1.p != src.Field1.p) {
#line 937 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"

#line 937 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).Field1));
	}(*dest).Field1.len = src.Field1.len; (*dest).Field1.p = src.Field1.p;
#line 937 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	if ((*dest).Field2.p != src.Field2.p) {
#line 937 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"

#line 937 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	eqdestroy___0RiuPw9cXhtLB9a2rQ2jA69cg((&(*dest).Field2));
	}(*dest).Field2.len = src.Field2.len; (*dest).Field2.p = src.Field2.p;}

#line 519 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(void, del__lDa9cDK9bq8jxuc4T2AsuSpw)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t, NimStringV2 key_0) {	NI hc;	NI i;	NI mskX60gensym36_;	NI T1_;NIM_BOOL* nimErr_;	nimfr_("del", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");{nimErr_ = nimErrorFlag();	hc = (NI)0;
#line 136 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	nimln_(136, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");
#line 136 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	i = rawGet__a59cxMy3qya79c49c6saGCAYQtables((*t), key_0, (&hc));	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 112 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	nimln_(112, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");
#line 112 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
	T1_ = ((*t).data.len-1);	mskX60gensym36_ = T1_;
#line 532 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(532, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");	{		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_19;
#line 113 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		nimln_(113, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");		if (!(((NI) 0) <= i)) goto LA4_;

#line 114 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
		nimln_(114, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");		if (nimSubInt((*t).counter, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_19)) { raiseOverflow(); goto BeforeRet_;};		(*t).counter = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_19);		{			{
#line 116 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
				nimln_(116, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");				while (1) {					NI jX60gensym36_;					NI rX60gensym36_;					NimStringV2 T9_;					tySequence__sM4lkSb7zS6F7OVMvW9cffQ T10_;					tyTuple__g1w83cyyBYiVU9c8WEJWnjQ T32_;
#line 117 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
					nimln_(117, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");					jX60gensym36_ = i;
#line 118 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
					nimln_(118, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");					rX60gensym36_ = jX60gensym36_;					if ((NU)(i) >= (NU)(*t).data.len){ raiseIndexError2(i,(*t).data.len-1); goto BeforeRet_;}
#line 515 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
					nimln_(515, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");					(*t).data.p->data[i].Field0 = ((NI) 0);
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
					nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");					if ((NU)(i) >= (NU)(*t).data.len){ raiseIndexError2(i,(*t).data.len-1); goto BeforeRet_;}
#line 120 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
					nimln_(120, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");					T9_.len = 0; T9_.p = NIM_NIL;
#line 49 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim"
					nimln_(49, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/fatal.nim");					eqsink___aBBXmHFBEivKqERloP6zmA_2((&(*t).data.p->data[i].Field1), T9_);

#line 2214 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
					nimln_(2214, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");					if ((NU)(i) >= (NU)(*t).data.len){ raiseIndexError2(i,(*t).data.len-1); goto BeforeRet_;}
#line 121 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
					nimln_(121, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");					T10_.len = 0; T10_.p = NIM_NIL;
#line 2214 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
					nimln_(2214, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");					eqsink___r6aagoRVuov7HvfEjIi3Uw((&(*t).data.p->data[i].Field2), T10_);
					{
#line 122 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
						nimln_(122, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");						while (1) {							NI TM__4SoG2KRQy3oMm9aUzSLtGrA_20;
#line 123 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
							nimln_(123, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");
#line 123 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"

#line 123 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
							if (nimAddInt(i, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_20)) { raiseOverflow(); goto BeforeRet_;};							i = (NI)((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_20) & mskX60gensym36_);
#line 124 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
							nimln_(124, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");							{								NIM_BOOL T15_;
#line 124 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								if ((NU)(i) >= (NU)(*t).data.len){ raiseIndexError2(i,(*t).data.len-1); goto BeforeRet_;}
#line 124 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								T15_ = (NIM_BOOL)0;								T15_ = isEmpty__5Qpmu5QqwDY0esVXn6wf7w_2tables((*t).data.p->data[i].Field0);								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;								if (!T15_) goto LA16_;

#line 125 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								nimln_(125, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");								goto LA6;
							}
							LA16_: ;

#line 126 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
							nimln_(126, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");
#line 126 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
							if ((NU)(i) >= (NU)(*t).data.len){ raiseIndexError2(i,(*t).data.len-1); goto BeforeRet_;}							rX60gensym36_ = (NI)((*t).data.p->data[i].Field0 & mskX60gensym36_);
#line 127 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
							nimln_(127, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");							{								NIM_BOOL T20_;								NIM_BOOL T21_;								NIM_BOOL T22_;								NIM_BOOL T25_;								NIM_BOOL T28_;
#line 127 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"

#line 127 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								T20_ = (NIM_BOOL)0;
#line 127 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								T21_ = (NIM_BOOL)0;
#line 127 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								T22_ = (NIM_BOOL)0;
#line 127 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								T22_ = (rX60gensym36_ <= i);								if (!(T22_)) goto LA23_;

#line 127 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								T22_ = (jX60gensym36_ < rX60gensym36_);								LA23_: ;
								T21_ = T22_;								if (T21_) goto LA24_;

#line 127 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								T25_ = (NIM_BOOL)0;
#line 127 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								T25_ = (jX60gensym36_ < rX60gensym36_);								if (!(T25_)) goto LA26_;

#line 127 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								T25_ = (i < jX60gensym36_);								LA26_: ;
								T21_ = T25_;								LA24_: ;
								T20_ = T21_;								if (T20_) goto LA27_;

#line 127 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								T28_ = (NIM_BOOL)0;
#line 127 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								T28_ = (i < jX60gensym36_);								if (!(T28_)) goto LA29_;

#line 127 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								T28_ = (rX60gensym36_ <= i);								LA29_: ;
								T20_ = T28_;								LA27_: ;
								if (!!(T20_)) goto LA30_;

#line 128 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
								nimln_(128, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");								goto LA11;
							}
							LA30_: ;
						}
					} LA11: ;

#line 937 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
					nimln_(937, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");					if ((NU)(jX60gensym36_) >= (NU)(*t).data.len){ raiseIndexError2(jX60gensym36_,(*t).data.len-1); goto BeforeRet_;}
#line 132 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tableimpl.nim"
					nimln_(132, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bleimpl.nim");					if ((NU)(i) >= (NU)(*t).data.len){ raiseIndexError2(i,(*t).data.len-1); goto BeforeRet_;}					T32_ = (*t).data.p->data[i];					nimZeroMem((void*)(&(*t).data.p->data[i]), sizeof(tyTuple__g1w83cyyBYiVU9c8WEJWnjQ));
#line 937 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
					nimln_(937, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim");					eqsink___BX2JqNf2E8tN5tqtm9b9aGeg((&(*t).data.p->data[jX60gensym36_]), T32_);
				}
			}
		} LA6: ;
	}
	LA4_: ;
	}BeforeRet_: ;
	popFrame();}

#line 1015 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(void, del__kuoXANiRixWCLT0f7qTDSA)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t, NimStringV2 key_0) {NIM_BOOL* nimErr_;	nimfr_("del", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");{nimErr_ = nimErrorFlag();
#line 1030 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(1030, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");
#line 1030 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	del__lDa9cDK9bq8jxuc4T2AsuSpw(t, key_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 997 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(NI, len__J4hnoSPhc6KiK07n7KgZ9cQ)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t) {	NI result;	nimfr_("len", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");	result = (NI)0;
#line 1003 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(1003, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");	result = (*t).counter;	popFrame();	return result;}

#line 374 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__wwb7zLiuOeGGoJCfnH0nvQ)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g t, NimStringV2 key_0) {	NIM_BOOL result;	NI hc;	NI T1_;NIM_BOOL* nimErr_;	nimfr_("hasKey", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");{nimErr_ = nimErrorFlag();	result = (NIM_BOOL)0;	hc = (NI)0;
#line 390 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(390, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");
#line 390 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 390 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"

#line 390 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	T1_ = (NI)0;	T1_ = rawGet__a59cxMy3qya79c49c6saGCAYQtables(t, key_0, (&hc));	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	result = (((NI) 0) <= T1_);	}BeforeRet_: ;
	popFrame();	return result;}

#line 876 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__W32mVXeOomM1v9brOiEZsMQ)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t, NimStringV2 key_0) {	NIM_BOOL result;NIM_BOOL* nimErr_;	nimfr_("hasKey", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");{nimErr_ = nimErrorFlag();	result = (NIM_BOOL)0;
#line 892 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(892, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");
#line 892 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	result = hasKey__wwb7zLiuOeGGoJCfnH0nvQ((*t), key_0);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 11 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size) {	void* T1_;
#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"

#line 13 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source_0, ((size_t) (size)));}

#line 2186 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source_0, NI size) {
#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"

#line 2187 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system.nim"
	nimCopyMem(dest, source_0, size);
}

#line 94 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {{
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	{		void* T5_;		void* T6_;		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_23;		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_24;
#line 95 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (!(((NI) 0) < src.len)) goto LA3_;

#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		T5_ = (void*)0;		T5_ = ((void*) ((&(*(*dest).p).data[(*dest).len])));		T6_ = (void*)0;		T6_ = ((void*) ((&(*src.p).data[((NI) 0)])));
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (nimAddInt(src.len, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_23)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_23)) < ((NI) 0) || ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_23)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_23), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 97 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(T5_, T6_, ((NI) ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_23))));

#line 98 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (nimAddInt((*dest).len, src.len, &TM__4SoG2KRQy3oMm9aUzSLtGrA_24)) { raiseOverflow(); goto BeforeRet_;};		(*dest).len = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_24);	}
	LA3_: ;
	}BeforeRet_: ;
}

#line 358 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, X5BX5D___089bL9acZbwGZxIQ4YKu4uOg)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t, NimStringV2 key_0) {	tySequence__sM4lkSb7zS6F7OVMvW9cffQ* result;	NI hcX60gensym22_;	NI indexX60gensym22_;NIM_BOOL* nimErr_;	nimfr_("[]", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");{nimErr_ = nimErrorFlag();	result = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ*)0;	hcX60gensym22_ = (NI)0;
#line 258 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(258, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");
#line 258 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	indexX60gensym22_ = rawGet__a59cxMy3qya79c49c6saGCAYQtables((*t), key_0, (&hcX60gensym22_));	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 372 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(372, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");	{
#line 259 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
		nimln_(259, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");		if (!(((NI) 0) <= indexX60gensym22_)) goto LA3_;

#line 259 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
		if ((NU)(indexX60gensym22_) >= (NU)(*t).data.len){ raiseIndexError2(indexX60gensym22_,(*t).data.len-1); goto BeforeRet_;}		result = (&(*t).data.p->data[indexX60gensym22_].Field2);	}
	goto LA1_;
	LA3_: ;
	{		tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag* T6_;		NimStringV2 T7_;		T6_ = (tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag*)0;		T6_ = (tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag*) nimNewObj(sizeof(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag), NIM_ALIGNOF(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag));		(*T6_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__t7nhKLvXTQS9cS8ByJU9bIag_);		(*T6_).Sup.Sup.Sup.name = "KeyError";
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
		nimln_(262, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");		T7_.len = 0; T7_.p = NIM_NIL;		T7_ = rawNewString(key_0.len + 15);appendString((&T7_), TM__4SoG2KRQy3oMm9aUzSLtGrA_22);appendString((&T7_), key_0);		(*T6_).Sup.Sup.Sup.message = T7_;		(*T6_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
#line 262 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
		raiseExceptionEx((Exception*)T6_, "KeyError", "[]", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim", 262);		goto BeforeRet_;	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 836 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, X5BX5D___Nb82lIHpq89cl6q2YU4EZlg)(tyObject_Table__qagh2zcXAhSb9aRfetCb26g* t, NimStringV2 key_0) {	tySequence__sM4lkSb7zS6F7OVMvW9cffQ* result;NIM_BOOL* nimErr_;	nimfr_("[]", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");{nimErr_ = nimErrorFlag();	result = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ*)0;
#line 858 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	nimln_(858, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/ta"
"bles.nim");
#line 858 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/pure/collections/tables.nim"
	result = X5BX5D___089bL9acZbwGZxIQ4YKu4uOg(t, key_0);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_tablesDatInit000)(void) {

#line 999999 "generated_not_to_break_here"

/* section: NIM_merge_TYPE_INIT3 */
NTIv2__qagh2zcXAhSb9aRfetCb26g_.destructor = (void*)eqdestroy___niuAxNwqyG9a9a74kbKT3Jvg; NTIv2__qagh2zcXAhSb9aRfetCb26g_.size = sizeof(tyObject_Table__qagh2zcXAhSb9aRfetCb26g); NTIv2__qagh2zcXAhSb9aRfetCb26g_.align = NIM_ALIGNOF(tyObject_Table__qagh2zcXAhSb9aRfetCb26g); NTIv2__qagh2zcXAhSb9aRfetCb26g_.name = "|stdlib.tables.Table|";
; NTIv2__qagh2zcXAhSb9aRfetCb26g_.traceImpl = (void*)eqtrace___RHcedK7oceGcKZDLXASTFg; NTIv2__qagh2zcXAhSb9aRfetCb26g_.disposeImpl = (void*)eqdispose___niuAxNwqyG9a9a74kbKT3Jvg_2;}

