/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;

/* section: NIM_merge_TYPES */
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);

/* section: NIM_merge_VARS */
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */

#line 90 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {	NCSTRING result;	result = (NCSTRING)0;
#line 91 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
	{
#line 91 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		if (!(s.len == ((NI) 0))) goto LA3_;

#line 91 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		result = "";	}
	goto LA1_;
	LA3_: ;
	{
#line 92 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/strs_v2.nim"
		result = ((NCSTRING) ((*s.p).data));	}
	LA1_: ;
	return result;}

#line 544 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 545 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;

#line 546 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 549 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	{
#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"

#line 553 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 783 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim"
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args, NI argsLen_0) {	int T6_;	int T7_;	nimfr_("echoBinSafe", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim");{	{		NimStringV2* s;		NI i;		s = (NimStringV2*)0;
#line 8 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
		nimln_(8, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.ni"
"m");		i = ((NI) 0);		{
#line 9 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
			nimln_(9, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.ni"
"m");			while (1) {				void* T4_;				int T5_;				NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_2;
#line 9 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"

#line 9 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
				if (!(i < argsLen_0)) goto LA3;

#line 797 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim"
				nimln_(797, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim");				if ((NU)(i) >= (NU)(argsLen_0)){ raiseIndexError2(i,argsLen_0-1); goto BeforeRet_;}				s = (&args[i]);
#line 801 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim"
				nimln_(801, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim");
#line 801 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim"
				T4_ = (void*)0;				T4_ = ((void*) (nimToCStringConv((*s))));
#line 801 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim"

#line 801 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim"
				T5_ = (int)0;				T5_ = fwrite(T4_, ((size_t) ((*s).len)), ((size_t) 1), stdout);				(void)(T5_);

#line 11 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.nim"
				nimln_(11, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/iterators.ni"
"m");				if (nimAddInt(i, ((NI) 1), &TM__MnCJ0VAmeZ9aTATUB39cx60Q_2)) { raiseOverflow(); goto BeforeRet_;};				i = (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_2);			} LA3: ;
		}
	}

#line 803 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim"
	nimln_(803, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim");
#line 803 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim"

#line 803 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim"
	T6_ = (int)0;	T6_ = fwrite(((void*) ("\012")), ((size_t) 1), ((size_t) 1), stdout);	(void)(T6_);

#line 804 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim"
	nimln_(804, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim");
#line 804 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim"

#line 804 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim"
	T7_ = (int)0;	T7_ = fflush(stdout);	(void)(T7_);
	}BeforeRet_: ;
	popFrame();}

#line 337 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim"
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, setInheritable__avyDiy1HdQrfaD3Ql9b63EQ)(int f, NIM_BOOL inheritable) {	NIM_BOOL result;	nimfr_("setInheritable", "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim");	result = (NIM_BOOL)0;
#line 347 "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim"
	nimln_(347, "/home/elcritch/.asdf/installs/nim/1.4.6/lib/system/io.nim");	result = NIM_TRUE;	popFrame();	return result;}
